// Further component and workmanship records for the universal How-to library.

export const componentHowToGuides = [
  {
    group: "Roofing and roof structure",
    id: "roof-asphalt-shingle",
    title: "Asphalt or composition shingle roof",
    image: "/schematic-components/roof-mounting-system.jpg",
    summary: "Use a listed flashed attachment fixed into confirmed framing without relying on shingles or decking alone.",
    keywords: ["asphalt roof", "shingle roof", "composition roof", "flashed foot", "rafter mount"],
    whatItIs: "A layered roof of shingles over underlay and deck, normally attached to rafters or trusses below.",
    whatItDoes: "The shingle sheds water; the selected flashing integrates the solar attachment into that water-shedding layer.",
    buy: ["Attachment/flashing listed for the exact roof and mounting family", "Structural fastener specified for confirmed framing", "Compatible sealant only where the flashing manual requires it", "Rails/clamps/bonding parts from the engineered system"],
    tools: ["Rafter-location and inspection method", "Shingle/flashing tools", "Correct pilot/driver and torque tools", "Roof access/fall controls"],
    before: ["Record shingle layers, age, condition and warranty", "Confirm rafter position and deck condition", "Stop for brittle, curled, leaking or structurally uncertain roofs"],
    steps: ["Set out engineered attachment positions over confirmed framing", "Lift/separate shingles using the product method", "Prepare the fixing point without damaging surrounding underlay", "Fix the attachment into framing to the specified embedment", "Lap flashing beneath upper courses and over lower courses as designed", "Apply only specified sealant details", "Fit rail, bonding and cable support", "Photograph each completed flashing before modules conceal it"],
    checks: ["Fastener enters confirmed framing", "Flashing laps follow water flow", "No lifted, split or unsealed shingle", "Attachment spacing and torque match engineering"],
    source: "Use the exact flashed-attachment, roof-covering and structural engineering instructions for the Site."
  },
  {
    group: "Roofing and roof structure",
    id: "roof-brittle-asbestos-stop",
    title: "Brittle, damaged or asbestos-suspect roof: stop",
    image: "/schematic-components/roof-mounting-system.jpg",
    summary: "Do not walk, drill, cut or disturb a roof that may be brittle or contain asbestos until it is professionally identified and managed.",
    keywords: ["asbestos roof", "fibro", "fibre cement", "brittle roof", "old roof", "cracked roof", "stop work"],
    whatItIs: "Older fibre-cement sheets, translucent panels, corroded metal, damaged tiles and some rooflights may fail under a person's weight or release hazardous fibres when disturbed.",
    whatItDoes: "A stop decision prevents an ordinary solar survey from becoming a fall, contamination or structural incident.",
    before: ["Treat unknown older fibre-cement products as suspect", "Keep people away from the roof surface and area below", "Do not take a sample unless the local licensed process permits it"],
    steps: ["Stop roof access and any drilling/cutting", "Photograph only from a safe location", "Record age, product clues and damaged areas", "Arrange competent identification and a structural/roof condition assessment", "Obtain the required remediation/removal/access plan", "Redesign for another mounting area if the roof cannot be safely used", "Resume only under the approved controls"],
    checks: ["Hazard status is recorded", "No generic mounting guide overrides the stop", "Required specialist documents are attached to the Site"],
    source: "Work-at-height and asbestos controls are location-specific; use the local workplace/building authority before disturbing suspect material."
  },
  {
    group: "Solar panels and module types",
    id: "read-module-label",
    title: "Read a solar-panel label and datasheet",
    image: "/schematic-components/solar-panel-pv-module.jpg",
    summary: "Capture the numbers Wattson needs: Voc, Vmp, Isc, Imp, power, fuse limit, system voltage, dimensions and clamp zones.",
    keywords: ["panel sticker", "solar label", "Voc", "Vmp", "Isc", "Imp", "panel watts", "datasheet"],
    whatItIs: "The rear label identifies the module model and electrical ratings at stated test conditions; the datasheet/manual adds temperature coefficients and mechanical limits.",
    whatItDoes: "These values determine string voltage/current, inverter compatibility, conductor/protection design and mounting method.",
    tools: ["Clear camera/label scanner", "Current manufacturer datasheet and installation manual", "Cold-temperature and current worksheet"],
    before: ["Do not infer ratings from panel size or appearance", "Keep model suffix and connector type—small suffix changes can matter"],
    steps: ["Photograph the entire label square-on", "Record manufacturer, full model and serial number", "Record rated power, Voc, Vmp, Isc and Imp", "Record maximum system voltage and maximum series-fuse rating", "Find voltage/current temperature coefficients", "Record dimensions, weight and permitted clamp zones", "Record factory connector manufacturer/family", "Attach the datasheet/manual to the Site component record"],
    checks: ["Every value is tied to the exact model", "Voc is not confused with Vmp and Isc is not confused with Imp", "Temperature and mechanical data are present before design"],
    source: "Use the exact module label, current datasheet and installation manual."
  },
  {
    group: "Solar panels and module types",
    id: "shade-bypass-strings",
    title: "Shade, bypass diodes and string grouping",
    image: "/schematic-components/solar-panel-pv-module.jpg",
    summary: "Map when and where shade falls, then group modules so one roof face or shaded area does not unnecessarily control another.",
    keywords: ["tree shade", "chimney shade", "panel shadow", "bypass diode", "multiple roof faces", "MPPT", "mismatch"],
    whatItIs: "Modules contain bypass sections, while strings and MPPT inputs electrically group modules. Shade changes the available current and operating point.",
    whatItDoes: "A considered layout reduces avoidable mismatch and identifies when separate MPPTs, optimisers or microinverters may be useful.",
    tools: ["Seasonal shade survey or modelling", "Roof-face direction/tilt record", "Module bypass-diode layout", "Inverter MPPT limits"],
    before: ["Map trees, chimneys, vents, ridges and future growth", "Check morning, midday, afternoon and seasonal effects", "Do not promise that module electronics erase lost sunlight"],
    steps: ["Divide modules by direction, tilt and shade pattern", "Estimate when each group is affected", "Place compatible groups on appropriate MPPTs", "Check minimum/maximum string voltage for every group", "Compare plain strings, optimisers and microinverters with actual compatibility data", "Keep access to likely service points", "Save shade assumptions with the production estimate"],
    checks: ["Different directions are not casually mixed on one tracker", "Electronics remain inside module/inverter current and voltage limits", "Production estimate includes real shade rather than marketing gain"],
    source: "Use the exact module bypass layout, inverter MPPT rules and any optimiser/microinverter compatibility documentation."
  },
  {
    group: "Mounting systems and hardware",
    id: "carport-pergola-canopy",
    title: "Solar carport, pergola or canopy",
    image: "/schematic-components/roof-mounting-system.jpg",
    summary: "Design the supporting structure, waterproofing, vehicle/public clearance and cable protection as one building—not as panels added later.",
    keywords: ["solar carport", "solar pergola", "canopy", "patio solar", "shade structure", "waterproof panels"],
    whatItIs: "A freestanding or building-attached structure where the solar array may also provide shade or shelter.",
    whatItDoes: "It supports panels at a useful orientation while managing rain, wind, impact, access and exposed cable routes.",
    buy: ["Engineered posts, beams, bracing, foundations and module supports", "Designed drainage/gutter or weather-sealing system", "Impact/UV-protected cable pathways and guarded equipment", "Bonding/earthing and required vehicle-clearance protection"],
    before: ["Check planning/building approval, boundaries and vehicle movement", "Assess wind/snow/seismic and foundation conditions", "Decide whether it must be weatherproof or only provide shade"],
    steps: ["Set usable clearance and footprint", "Engineer foundations and frame", "Plan panel joints, drainage and gutters", "Plan protected DC/AC routes before enclosing posts/beams", "Build and inspect the structure", "Install supports, modules, bonding and cable guards", "Water-test where shelter is claimed", "Record buried foundations/services and clearances"],
    checks: ["Structure and foundations are approved", "No reachable exposed connector or cable", "Drainage does not discharge into unsafe areas", "Vehicle impact and maintenance access are addressed"],
    source: "Use local building/planning requirements and the exact structural, mounting, module and electrical designs."
  },
  {
    group: "Batteries and charging",
    id: "battery-bms",
    title: "Battery management system (BMS)",
    image: "/schematic-components/bms-battery-management-system.jpg",
    summary: "The BMS protects and reports on battery cells; inverter settings and communications must respect its limits.",
    keywords: ["BMS", "battery communication", "CAN", "battery protect", "cell voltage", "charge limit", "discharge limit"],
    whatItIs: "Electronics that measure cells and temperature, balance cells where designed, communicate limits and open or command protection under unsafe conditions.",
    whatItDoes: "It prevents operation outside the battery maker's cell, temperature, charge and discharge limits—but it does not replace all required fuses, isolation or correct inverter settings.",
    buy: ["Battery/BMS combination supported by the battery maker", "Inverter communication cable/interface and terminators", "Required contactors, pre-charge and external protection"],
    before: ["Confirm exact battery-inverter compatibility and firmware", "Identify CAN/RS485 pinout—physical plug shape is not proof", "Record maximum charge/discharge currents and temperature limits"],
    steps: ["Set battery addresses and bank topology", "Connect communication in the stated daisy-chain/star arrangement", "Fit correct terminators", "Configure inverter battery protocol", "Confirm reported voltage, current, temperature and state", "Test charge/discharge limit response", "Save firmware and configuration"],
    checks: ["No homemade communication pinout without manufacturer approval", "Inverter obeys dynamic BMS limits", "Every battery appears correctly", "Independent overcurrent protection remains present"],
    source: "Use the exact battery, BMS and inverter compatibility/communication manuals."
  },
  {
    group: "Batteries and charging",
    id: "dc-busbars-distribution",
    title: "Positive and negative DC busbars",
    image: "/schematic-components/busbar.jpg",
    summary: "Use a rated, covered distribution point when several cables must share the same positive or negative battery connection.",
    keywords: ["bus bar", "battery distribution", "positive bar", "negative bar", "terminal block", "too many battery lugs", "busbar size", "mount busbar", "busbar height"],
    whatItIs: "A busbar is a solid copper or plated conductive bar with several studs or terminals. Every connection on one bar is electrically the same point—so a positive bar and a negative bar must never touch or be confused.",
    whatItDoes: "It replaces an unsafe pile of cable lugs on a battery or inverter stud with an orderly, coverable distribution point. It also makes fusing, balanced battery connections, shunt measurement, labels and later servicing easier to understand.",
    usedFor: ["Battery-bank DC distribution", "Connecting several chargers or DC loads", "Parallel battery connections", "Feeding an inverter through a main protected path", "Creating one measured system-negative point after a shunt"],
    types: [
      { name: "Positive DC busbar", description: "Distributes battery positive to protected outgoing circuits.", bestFor: "One covered positive point feeding inverter, chargers and DC distribution.", watchFor: "It normally sits after the designed main battery protection; each smaller outgoing cable may need its own protection." },
      { name: "Negative DC busbar", description: "Collects return conductors from chargers, inverter and DC loads.", bestFor: "Keeping all system returns together and, with a battery monitor, on the system side of the shunt.", watchFor: "A return connected directly to battery negative can bypass the shunt and make state-of-charge readings wrong." },
      { name: "Combined distribution module", description: "A covered assembly may contain separate positive and negative bars, fuse positions, a disconnect or a shunt.", bestFor: "Compact, documented battery systems using one compatible product family.", watchFor: "The internal ratings and diagram still control; a shared enclosure does not mean positive and negative are electrically joined." },
      { name: "AC, neutral and earth bars", description: "Switchboards also contain busbars, neutral bars and protective-earth bars designed for AC distribution.", bestFor: "Their exact approved switchboard purpose only.", watchFor: "Do not substitute an AC neutral/earth bar or generic terminal strip for a high-current battery DC busbar unless it is explicitly rated and approved for that duty." }
    ],
    questions: [
      { question: "Why would I use a busbar?", answer: "Use one when several cables need the same electrical connection and the battery/equipment terminal cannot safely or neatly accept them. It gives each cable a proper stud, makes covers and labels possible, and creates a clear place for distribution and testing." },
      { question: "Do I have to use one?", answer: "Not always. A very simple system may have one correctly fused cable connected directly between the battery and one device if both manuals permit it. Once there are several batteries, chargers, inverters or DC loads, a correctly rated busbar or purpose-built distribution module is usually the clearer solution. The approved schematic decides." },
      { question: "Does its size matter?", answer: "Yes. Check maximum system voltage, continuous current, short-duration or fault duty, conductor/stud size, allowed number of lugs, enclosure temperature and environment. The bar must carry the worst combined current without excessive heating; physical length alone is not its rating." },
      { question: "Do I need both a positive and a negative busbar?", answer: "Only if the circuit layout needs distribution on both sides. Many multi-device battery systems use both. Some use a positive fused distribution module but only a negative bar, or vice versa. They remain separate components and must never be bridged together." },
      { question: "Can I use only one side of a two-bar unit?", answer: "Possibly, if the manufacturer permits it and unused live parts are safely covered, but the unused bar must not create confusion or an accidental connection. Record it on the schematic and label it clearly." },
      { question: "Is a busbar DC or AC?", answer: "It is only suitable for the voltage, current, fault duty and application stated by its manufacturer. Battery bars must be rated for the intended DC system. Switchboard AC busbars, neutral bars and earth bars have different approved jobs and are not automatic substitutes." },
      { question: "Where should it be mounted?", answer: "Mount it on a rigid, non-conductive or purpose-designed insulated base, normally inside a suitable covered enclosure close enough to the battery/distribution equipment to keep high-current cables short. Keep it dry, ventilated as required, protected from dropped tools and metal objects, away from fuel or ignition hazards, and positioned so cable weight cannot pull sideways on studs." },
      { question: "Is there a regulated mounting height?", answer: "There is no single global busbar height. The correct height and accessibility depend on the country, installation type, enclosure, battery/equipment manual, touch-protection rules and who may access the space. Use the Site location rules. Regardless of height, live parts must be guarded, serviceable and inaccessible to children or untrained people where required." }
    ],
    buy: ["Busbar explicitly rated for the system DC voltage, combined continuous current and expected fault duty", "Enough correctly sized studs/terminals without unsupported lug stacking", "Insulated base, finger-safe cover or suitable enclosure", "Correct lugs, washers/nuts specified by the maker, boots and durable positive/negative labels"],
    tools: ["Approved DC schematic and maximum-current calculation", "Correct cable-lug crimper", "Insulated hand tools", "Calibrated torque wrench", "Drill/template for the enclosure mounting pattern"],
    before: ["Sum simultaneous continuous and surge currents through each section of bar", "Check voltage, fault rating, terminal count, stud size, lug stacking and torque limits", "Choose a dry, guarded and serviceable mounting position", "Place positive distribution relative to main and branch protection exactly as designed", "Place system negative after the battery shunt where fitted so no load or charger bypasses measurement"],
    steps: ["Draw every proposed cable on the positive and negative bars before drilling", "Choose the bar ratings and number of terminals from that drawing", "Mount each bar rigidly on its insulated base inside the selected enclosure", "Keep positive and negative separated and unmistakably labelled", "Route cables with bend radius and strain support so lugs sit flat", "Fit one lug per stud where possible or only the stack expressly permitted", "Hold the stud as required and torque the nut to the maker's value", "Fit all covers and terminal boots", "Photograph, label and update the schematic before energising"],
    checks: ["Voltage, continuous current and fault-duty ratings exceed the designed duty", "Positive and negative bars cannot touch or be mistaken for each other", "Positive live metal is fully guarded", "No load or charger bypasses the shunt", "No unsupported lug stack or cable strain", "Mounting position meets local access/touch-protection requirements", "Every terminal torque and connected circuit is recorded"],
    source: "Use the exact busbar, fuse, shunt and connected-equipment terminal manuals."
  },
  {
    group: "AC wiring and connections",
    id: "rcd-rcbo-selection",
    title: "RCD, RCBO and inverter leakage requirements",
    image: "/schematic-components/rcd-rccb.jpg",
    summary: "Residual-current protection type and arrangement must match the inverter, circuit, earthing system and local rules.",
    keywords: ["RCD", "RCBO", "GFCI", "earth leakage", "nuisance tripping", "type A", "type B"],
    whatItIs: "An RCD/GFCI detects current imbalance to earth; an RCBO combines residual-current and overcurrent protection. Different sensing types respond to different residual waveforms.",
    whatItDoes: "It provides additional shock/fire protection where required, but incorrect type, neutral routing or grouping can cause loss of protection or unwanted tripping.",
    buy: ["Protection type and rating required by inverter and local design", "Correct poles, breaking capacity and enclosure", "Dedicated neutral arrangement and labels where required"],
    before: ["Read the inverter's stated residual-current protection requirements", "Confirm earthing/neutral arrangement in grid and backup modes", "Calculate/select overcurrent protection separately"],
    steps: ["Mark protected circuits and all active/neutral paths", "Select required RCD/RCBO sensing type", "Coordinate rating with cable and upstream protection", "Keep circuit neutrals in their correct protected group", "Install and torque through the authorised process", "Perform required trip-time/current tests", "Record device type and results"],
    checks: ["No shared/misrouted neutral defeats protection", "Type matches inverter residual behaviour", "Test button and instrument tests both pass", "Backup/changeover modes are included in testing"],
    source: "This is local regulated AC work; use the exact inverter manual, protection maker data and local wiring/test requirements."
  },
  {
    group: "Monitoring and communications",
    id: "ct-clamp-direction",
    title: "CT clamps: location, direction and phase",
    image: "/schematic-components/current-transformer-ct-clamp.jpg",
    summary: "A CT on the wrong conductor, backwards or assigned to the wrong phase makes import look like export and breaks control decisions.",
    keywords: ["CT", "current transformer", "clamp meter sensor", "import export wrong", "meter arrow", "phase mapping"],
    whatItIs: "A current transformer clips around one conductor and reports current direction/magnitude to a meter, inverter or export controller.",
    whatItDoes: "Correctly placed CTs measure grid flow, load or generation without being placed in series with the conductor.",
    buy: ["CT model/rating specified by the meter or inverter", "Correct cable/extension and connector", "Required multi-phase set and meter/gateway"],
    before: ["Identify the exact measurement point and conductor", "Confirm arrow/source-load convention", "Match each CT to its voltage phase", "Use an authorised person where enclosure access is restricted"],
    steps: ["Label phases and planned CT IDs", "Open the CT and close it fully around one permitted conductor only", "Orient the arrow/mark as the selected manual states", "Route the CT lead away from damage and interference", "Connect each CT to the matching meter input", "Apply known load/generation and verify direction", "Correct configuration/orientation before enabling export control"],
    checks: ["CT surrounds one conductor, not an entire multicore cable", "Jaw is fully closed", "Phase mapping and direction are proven by a test", "Loss/disconnection behaviour is understood"],
    source: "Use the exact meter/inverter/export-control CT installation and commissioning manual."
  },
  {
    group: "Tools and workmanship",
    id: "meter-safe-use",
    title: "Meters and testers: know the safe boundary",
    image: "/schematic-components/energy-meter.jpg",
    summary: "Choose a correctly rated instrument and test method; a familiar multimeter can still be unsafe on PV strings, batteries or mains.",
    keywords: ["multimeter", "test voltage", "clamp meter", "CAT rating", "prove dead", "insulation tester", "PV tester"],
    whatItIs: "Meters measure voltage, current, resistance or insulation, but their category, voltage, leads, fusing and method must suit the energy source.",
    whatItDoes: "A controlled test confirms circuit condition without exposing the user or instrument to energy beyond its rating.",
    buy: ["Instrument with suitable voltage/category and DC capability", "Approved fused/shrouded leads and probes", "Proving unit or approved known-source method", "PV-specific tester where required by the test plan"],
    before: ["Know whether the work is legally restricted", "Check maximum possible PV open-circuit voltage and battery fault energy", "Inspect case, leads, tips, fuses and battery", "Never use resistance/current modes on an energised voltage source"],
    steps: ["Select the required test from the approved plan", "Confirm instrument and lead ratings", "Inspect and prove the tester", "Select function/range before touching the circuit", "Use controlled probe placement and required PPE/access controls", "Read and record the result", "Withdraw safely and prove the tester again where required", "Stop for unexpected readings"],
    checks: ["Instrument rating exceeds the circuit duty", "Correct sockets/function/range used", "Test-before/test-after process completed where required", "Result is tied to the correct circuit and conditions"],
    source: "Follow the exact test-instrument manual and local safe-isolation/licensing rules; this guide does not authorise live electrical work."
  }
] as const;
