// Global, beginner-first EV charging records. Regional connector and installation
// requirements are deliberately verified from the saved Site rather than assumed.

export const evChargingHowToGuides = [
  {
    group: "EV charging and transport",
    id: "ev-charging-equipment",
    title: "EV charging equipment: portable leads, wallboxes and rapid chargers",
    image: "/guides/ev/ev-charging-path.svg",
    summary: "Recognise the box, cable and connector that safely tell an electric vehicle how much power it may take.",
    aliases: ["EVSE", "EV charger", "car charger", "wallbox", "charge point", "charging station", "granny charger"],
    keywords: ["home EV charging", "AC charging", "DC fast charging", "portable EV lead", "tethered charger", "untethered charger"],
    whatItIs: "Most equipment called an EV charger is EV supply equipment, or EVSE. It controls and protects the connection; during ordinary AC charging, the vehicle's onboard charger converts AC into battery DC. A DC rapid charger performs that conversion outside the vehicle.",
    whatItDoes: "It checks that the vehicle is connected, communicates the permitted current, switches power under controlled conditions and provides the protection functions required by the exact equipment and local installation.",
    usedFor: ["Charging at home", "Workplace and fleet charging", "Using spare solar production", "Scheduling around tariffs or generator capacity", "Public destination charging", "DC rapid charging"],
    types: [
      { name: "Portable in-cable EVSE", image: "/guides/ev/portable-evse.svg", description: "A plug-in supply lead with a control-and-protection box in the cable.", bestFor: "Supported occasional or lower-power charging from a suitable dedicated outlet and circuit.", watchFor: "Outlet condition, continuous-load rating, heat, extension leads, weather exposure, earthing and the vehicle/EVSE manual. A domestic plug is not automatically suitable for repeated maximum-current charging." },
      { name: "Fixed AC wallbox", image: "/guides/ev/ac-wallbox.svg", description: "A permanently mounted EVSE, either with a fixed vehicle cable (tethered) or a vehicle socket requiring a separate lead (untethered).", bestFor: "Regular home or workplace charging with a circuit and power limit designed for the Site.", watchFor: "Single/three phase, maximum current, vehicle onboard-charger limit, required residual-current/DC leakage protection, cable reach, impact/weather rating and load management." },
      { name: "AC pedestal or multi-port station", image: "/guides/ev/ac-pedestal.svg", description: "One freestanding or wall-mounted station supplies one or more parking spaces and may include access control, metering and network communications.", bestFor: "Shared homes, workplaces, accommodation, fleets and destination charging.", watchFor: "How available power is shared, simultaneous vehicles, bollard/impact protection, accessibility, payment/network dependency and loss of communications." },
      { name: "DC rapid or fast charger", image: "/guides/ev/dc-fast-charger.svg", description: "Large equipment converts its AC or DC supply into controlled high-voltage DC delivered directly to a compatible vehicle battery.", bestFor: "Shorter public or fleet charging stops where substantial grid/site capacity and compatible vehicles support it.", watchFor: "Not an ordinary home wallbox. Connector/protocol, vehicle charge curve, supply capacity, cooling, demand, civil works, access and specialist commissioning all matter." },
    ],
    questions: [
      { question: "Is the box on my wall actually the charger?", answer: "During AC charging, the wallbox is normally EVSE and the car contains the AC-to-DC charger. During DC rapid charging, the large external unit performs the conversion and supplies controlled DC to the battery." },
      { question: "Does a larger wallbox always charge the car faster?", answer: "No. Charging is limited by the smallest relevant limit: Site/circuit capacity, EVSE setting, cable/connector rating, the vehicle's onboard AC charger, battery conditions and any load-management command." },
      { question: "Can I use an extension lead?", answer: "Do not make an extension lead the assumed charging design. EV charging is a long-duration load and plug/socket heat or weather exposure can become critical. Follow the exact vehicle/portable-EVSE instructions and local electrical requirements." },
      { question: "Where should a home charger go?", answer: "Where the parked vehicle can connect without stretching or creating a trip/drive-over path, and where the enclosure, cable holster, impact protection, flooding/weather exposure, ventilation and service access suit the product. The local Site rules determine regulated clearances or accessibility." },
    ],
    buy: ["EVSE approved for the destination country, supply and vehicle connector", "Tethered cable or separate lead of the correct connector/current arrangement", "Designed dedicated circuit, isolation and protection required by the equipment and local rules", "Load-management hardware if the Site supply or off-grid inverter cannot support unrestricted charging", "Cable holster, mounting and impact/weather accessories for the real parking position"],
    tools: ["Vehicle charging specifications", "EVSE installation and user manuals", "Site maximum-demand and supply/inverter records", "Measured parking position and cable route", "Authorised test equipment and commissioning application required locally"],
    before: ["Record vehicle inlet and maximum AC/DC charging capability", "Identify supply voltage, phase arrangement and safe spare capacity", "Decide normal daily energy needed rather than assuming the EV must charge from empty every night", "Check solar, stationary battery, tariff and outage objectives", "Confirm regional circuit, protection, inspection and network requirements"],
    steps: ["Measure the parking and cable route", "Match the vehicle inlet and regional connector", "Choose portable, fixed AC or specialist DC equipment for the actual charging job", "Calculate the circuit and Site power limit", "Add dynamic load control when unrestricted charging could overload the supply or inverter", "Mount and route the cable so it is supported, reachable and protected", "Complete required circuit work, testing and commissioning", "Set a conservative charging schedule/current", "Verify plug temperature, power, energy delivered and load-control response", "Save the model, settings, circuit and shutdown information"],
    checks: ["Vehicle, EVSE, connector and supply are compatible", "Charging current cannot overload the Site, inverter, generator or circuit", "Cable cannot be crushed, driven over or left across an unsafe path", "Protection and loss-of-supply behavior were tested", "User knows how to stop, isolate and report a damaged connector"],
    source: "IEC 61851-1 defines general EV supply-equipment and connection requirements; use the exact equipment instructions and Site-country rules.",
    sourceUrl: "https://webstore.iec.ch/en/publication/33644",
  },
  {
    group: "EV charging and transport",
    id: "ev-connectors-cables-adapters",
    title: "EV charging connectors, sockets, cables and adapters",
    image: "/guides/ev/connector-families.svg",
    summary: "Identify the vehicle inlet and regional charging system before buying a wallbox, cable or adapter.",
    aliases: ["Type 1", "J1772", "Type 2", "Mennekes", "CCS", "Combo", "CHAdeMO", "NACS", "J3400", "GB/T", "EV plug"],
    keywords: ["EV connector types", "charging cable", "tethered", "untethered", "EV adapter", "wrong plug"],
    whatItIs: "The connector is the hand-held plug fitted to the vehicle inlet. AC and DC families have different contact layouts, signalling and regional use. A similar outline does not prove electrical or communication compatibility.",
    whatItDoes: "The connector carries power, protective-earth and control/communication functions while mechanical latching and temperature/current limits keep the charging session controlled.",
    usedFor: ["Matching a vehicle to home EVSE", "Choosing tethered or socketed equipment", "Selecting a replacement charging lead", "Planning imported-vehicle support", "Recognising public charging options", "Checking adapter limitations"],
    types: [
      { name: "Type 1 / SAE J1772 AC", image: "/guides/ev/type-1-j1772.svg", description: "A round, five-contact single-phase AC vehicle connector common on older or region-specific vehicles.", bestFor: "A vehicle inlet and country/equipment ecosystem explicitly supporting Type 1/J1772.", watchFor: "Do not confuse the vehicle end with the building plug. Confirm phase, current, latch and imported-vehicle support." },
      { name: "Type 2 / IEC 62196-2 AC", image: "/guides/ev/type-2.svg", description: "A seven-contact AC connector widely used across many regions and capable of supported single- or three-phase arrangements.", bestFor: "Compatible vehicles and regional Mode 3 wallboxes or stations.", watchFor: "The shape does not guarantee every phase/current capability; vehicle, cable and station limits still apply." },
      { name: "CCS / Combined Charging System", image: "/guides/ev/ccs-combo.svg", description: "A Type 1 or Type 2-style upper section is combined with two large DC contacts for compatible rapid charging.", bestFor: "CCS1 or CCS2 vehicles and stations in the applicable region.", watchFor: "CCS1 and CCS2 differ. Confirm inlet, protocol, voltage and actual station cable rather than relying on the word CCS." },
      { name: "CHAdeMO", image: "/guides/ev/chademo.svg", description: "A separate round DC rapid-charging family found on particular vehicles and markets.", bestFor: "Vehicles with a CHAdeMO inlet and a compatible station.", watchFor: "Availability varies considerably and an adapter may not reproduce every charging or bidirectional feature." },
      { name: "NACS / SAE J3400", image: "/guides/ev/nacs-j3400.svg", description: "A compact connector family used for supported AC and DC charging in North America and related deployments.", bestFor: "Vehicles, EVSE and networks explicitly supporting the applicable J3400/NACS arrangement.", watchFor: "Physical fit, adapter availability, voltage, authentication and network access are separate compatibility questions." },
      { name: "GB/T and other regional families", image: "/guides/ev/gbt-connector.svg", description: "China and other markets use additional standardised AC/DC connector and communication arrangements.", bestFor: "The vehicle's original approved market or a documented conversion/adapter ecosystem.", watchFor: "Imported vehicles can require more than a plug adapter. Check signalling, locking, voltage, phase, approval and service support." },
    ],
    questions: [
      { question: "Can I tell the connector from the car model?", answer: "Do not rely on model name alone; the same model can have different inlets by country and year. Photograph the open inlet and rating labels, then confirm against the vehicle manual." },
      { question: "Is an adapter always safe if it fits?", answer: "No. Confirm the adapter's exact supported direction, AC/DC function, current, voltage, signalling, latching, temperature monitoring, approval and vehicle/EVSE maker acceptance." },
      { question: "Tethered or untethered wallbox?", answer: "Tethered is convenient and guarantees the lead is present; socketed equipment can support replaceable or differently ended leads. Compare weather/handling, theft, cable length, vehicle changes and regional rules." },
    ],
    buy: ["Connector matching the photographed vehicle inlet and regional charging method", "Cable with adequate voltage/current/phase/contact-temperature rating", "Weather caps, holster and strain relief", "Only documented adapters approved for the exact direction and charging mode"],
    tools: ["Clear vehicle-inlet photograph", "Vehicle and EVSE manuals", "Cable label/rating photograph", "Regional charging-network compatibility information"],
    before: ["Identify vehicle year and destination market", "Separate AC capability from DC rapid capability", "Confirm station/EVSE socket or tethered end", "Check cable current and phase arrangement", "Treat every adapter as an additional compatibility check"],
    steps: ["Open and photograph the complete vehicle inlet", "Match contact layout and official connector name", "Read vehicle maximum AC and DC capabilities", "Match the Site EVSE or public station", "Inspect pins, seals, latch and cable before use", "Insert without forcing and confirm the vehicle/station handshake", "Support and holster the cable after charging"],
    checks: ["No bent, wet, contaminated, loose or overheated contact", "Connector latches without force", "Cable and adapter ratings cover the session", "The vehicle reports the expected AC or DC charging mode"],
    source: "Connector names and availability vary globally; the US DOE AFDC provides one illustrated regional comparison. Verify the saved Site and exact vehicle manual.",
    sourceUrl: "https://afdc.energy.gov/fuels/electricity-stations?lv=true",
  },
  {
    group: "EV charging and transport",
    id: "smart-solar-ev-charging-v2x",
    title: "Solar-aware EV charging, load management and V2H/V2G",
    image: "/guides/ev/solar-aware-ev-charging.svg",
    summary: "Control when and how hard the vehicle charges so it works with the Site supply, solar, stationary battery and other loads.",
    aliases: ["smart charging", "solar surplus charging", "dynamic load balancing", "V2H", "V2B", "V2G", "bidirectional charging", "vehicle to load"],
    keywords: ["charge from solar", "avoid grid export", "EV overload", "EV with off grid inverter", "EV backup house", "OCPP"],
    whatItIs: "Smart charging varies time or current using a schedule, tariff, solar/export measurement or Site-capacity limit. Bidirectional systems can also transfer supported vehicle energy outward to a load, building or grid.",
    whatItDoes: "It can prevent the EV from overloading the Site, favour surplus solar, coordinate several chargers and—only with a complete compatible bidirectional system—support selected loads or grid services.",
    usedFor: ["Charging from surplus PV", "Protecting a limited grid connection", "Charging from an off-grid or hybrid inverter", "Coordinating several vehicles", "Avoiding peak tariffs", "Supported backup or grid export from a vehicle"],
    types: [
      { name: "Time-scheduled charging", image: "/guides/ev/scheduled-charging.svg", description: "The vehicle or EVSE starts, stops or limits charging at chosen times.", bestFor: "Simple tariff windows, generator schedules or avoiding known household peaks.", watchFor: "A fixed clock does not know whether solar is actually spare or another load has unexpectedly started." },
      { name: "Solar-surplus charging", image: "/guides/ev/solar-surplus-charging.svg", description: "A meter/controller varies EV current in response to measured Site import, export or PV surplus.", bestFor: "Using otherwise-exported solar while respecting the vehicle's minimum/stable charging behavior.", watchFor: "Meter direction, phase measurement, cloud dependency, response speed, minimum current and rapidly changing clouds/loads." },
      { name: "Dynamic Site load balancing", image: "/guides/ev/dynamic-load-balancing.svg", description: "The EVSE reduces charging when the building, inverter or group of charge points approaches a defined capacity.", bestFor: "Limited service connections, hybrid/off-grid supplies, fleets or multiple EVSE.", watchFor: "Define a safe fallback for meter, current-transformer, communications or controller failure." },
      { name: "Bidirectional V2H, V2B or V2G", image: "/guides/ev/bidirectional-v2x.svg", description: "Compatible vehicle, charger, controls and transfer/grid interface permit energy to flow from the traction battery to selected home/building loads or the network.", bestFor: "A specifically supported vehicle/charger/market combination with approved islanding, transfer and export behavior.", watchFor: "A vehicle capable of powering an appliance is not automatically approved for house backup or grid export. Warranty, connector protocol, neutral/earth, anti-islanding and network permission are system-level requirements." },
    ],
    questions: [
      { question: "Can my EV charge directly from solar panels?", answer: "Normally the vehicle charges through coordinated power equipment: grid/hybrid inverter and AC EVSE, or a specifically designed DC path. A solar-aware controller measures available power and adjusts charging; panels are not connected directly to an ordinary vehicle inlet." },
      { question: "Will solar-only mode keep stopping under clouds?", answer: "A good controller uses a minimum charging threshold, delay and hysteresis, and may allow a chosen amount of grid or battery support. Exact behavior depends on EVSE, vehicle, inverter and meter integration." },
      { question: "Can any EV run my house during an outage?", answer: "No. Vehicle-to-load, V2H/V2B and V2G are different capabilities. The exact vehicle, bidirectional charger, transfer/islanding system, firmware, connector protocol and local approval must all support the intended use." },
      { question: "Should the home battery charge the EV?", answer: "That is an operating choice, not an automatic rule. Compare the EV departure need, stationary reserve, forecast solar, upstream source and conversion losses. PVIntell should expose the priority rather than silently draining backup storage." },
    ],
    buy: ["EVSE/controller supporting the required scheduling or dynamic-current method", "Compatible Site meter or current sensors in the correct location and direction", "Local communications that fail safely", "For V2X, an explicitly compatible vehicle, bidirectional charger, transfer/grid interface and approval path"],
    tools: ["Whole-Site power-flow schematic", "Vehicle and EVSE control specifications", "Inverter/grid-service capacity and response limits", "Meter/CT orientation plan", "Commissioning log covering communications failure"],
    before: ["Define minimum departure energy and time", "Choose whether grid, generator or stationary battery may supplement solar", "Map the meter point so import/export direction is unambiguous", "Set the Site or inverter capacity that must never be exceeded", "For V2X, verify exact compatibility and local islanding/export requirements before purchase"],
    steps: ["Draw PV, grid/generator, stationary battery, building loads, EVSE and vehicle", "Set the hard Site power limit", "Install and orient the required meter/CT through the authorised process", "Connect local/network communications", "Set schedule, solar threshold, minimum current and reserve priorities", "Test rising building load and falling solar", "Test communications/meter failure", "For approved V2X, test transfer, islanding and reconnection", "Save settings and measured power flows"],
    checks: ["EV current falls before Site capacity is exceeded", "Import/export signs are correct", "Cloud or communications failure has a safe predictable result", "Stationary-battery reserve is not silently consumed", "Bidirectional operation is recorded only when the full compatible system was commissioned"],
    source: "Open Charge Alliance documents smart charging, load balancing and bidirectional-capable protocol functions; product and regional support remain specific.",
    sourceUrl: "https://openchargealliance.org/faq/",
  },
] as const;
