// Plain-language decision guides. These sit before component instructions so a
// novice can choose the job the system must do before being shown parts.

export const planningHowToGuides = [
  {
    group: "Start here: system choices",
    id: "system-shapes",
    title: "The four common shapes of a home solar system",
    image: "/guides/panels/string-inverter-layout.png",
    summary: "Start with the outcome: lower bills, outage backup, no grid export, or independent off-grid power.",
    keywords: ["where do I start", "what system", "overwhelmed", "grid tied", "hybrid", "off grid", "backup", "self sufficient"],
    whatItIs: "A plain comparison of grid-tied solar, solar with batteries, a grid-connected backup system, and a fully off-grid system.",
    whatItDoes: "It prevents parts shopping before the user has chosen what must happen during sunshine, at night, during an outage and when batteries are empty.",
    before: ["Gather 12 months of energy use if available", "List essential outage loads separately from the whole home", "Record grid/export rules and planned future loads", "State the budget and whether the system must expand in stages"],
    steps: ["Choose whether the grid remains available", "Choose whether any solar may export", "Choose what must work during a blackout", "Choose the required backup duration", "Choose whether the first stage needs batteries now or only battery-ready equipment", "Compare the four resulting energy-flow pictures", "Keep uncertain answers visible for Wattson to resolve one at a time"],
    checks: ["The selected architecture matches grid and outage goals", "Backup loads are not confused with total daily use", "No equipment model has been chosen before the energy-flow decision"],
    source: "US Department of Energy: PV modules are only one part of a complete system; inverters, mounting and optional storage serve different jobs.",
    sourceUrl: "https://www.energy.gov/cmei/systems/solar-photovoltaic-system-design-basics"
  },
  {
    group: "Start here: system choices",
    id: "energy-vs-power",
    title: "kW and kWh: how big, and for how long?",
    image: "/schematic-components/energy-meter.jpg",
    summary: "Separate power used right now from energy used across a day; both numbers are needed.",
    keywords: ["kW vs kWh", "75 kwh", "daily use", "peak load", "surge", "how many batteries", "how many panels"],
    whatItIs: "Kilowatts (kW) describe the rate of power at one moment. Kilowatt-hours (kWh) describe accumulated energy over time.",
    whatItDoes: "Peak and surge kW influence inverter size; daily/night-time kWh influence solar production and battery capacity.",
    tools: ["Recent bills or meter totals", "Appliance/load list", "Clamp meter or interval-monitoring data where safely available", "Daily and seasonal use record"],
    before: ["Do not size from one bill total alone", "Separate summer cooling/heating peaks from ordinary days", "Identify motors, pumps, welders, compressors and electric heating"],
    steps: ["Record average and worst daily kWh by season", "List loads that can operate together", "Record large starting/surge loads", "Split daytime use from night-time use", "Split essential backup loads from optional loads", "Decide what can be scheduled when solar is abundant", "Use these separate values in solar, inverter and battery sizing"],
    checks: ["Daily energy and peak power are separate fields", "Seasonal worst case is visible", "Unknown loads remain estimates rather than false precision"],
    source: "US Department of Energy: storage energy capacity and power capacity perform different tasks.",
    sourceUrl: "https://www.energy.gov/cmei/systems/solar-integration-solar-energy-and-storage-basics"
  },
  {
    group: "Start here: system choices",
    id: "zero-export",
    title: "Keep the grid but do not export solar",
    image: "/schematic-components/current-transformer-ct-clamp.jpg",
    summary: "A zero-export design measures power at the grid connection and controls compatible generation so export stays within the approved limit.",
    keywords: ["no backfeed", "zero export", "export limit", "self consumption", "do not sell power", "CT clamp"],
    whatItIs: "A grid-connected control arrangement using a compatible inverter, meter or CT sensors and an approved grid profile to limit energy flowing out to the utility.",
    whatItDoes: "It can retain grid supply while directing solar toward local loads and/or batteries, but it does not automatically provide blackout power.",
    buy: ["Inverter/control platform that explicitly supports the required export limit", "Approved meter/CT hardware and communications", "Required gateway, grid profile and grid-connection protection"],
    tools: ["Utility/network export requirements", "Whole-site single-line drawing", "Meter/CT direction and phase plan", "Commissioning and witness-test procedure where required"],
    before: ["Confirm whether the permitted limit is zero or another value", "Confirm every source the controller must manage", "Ask separately whether blackout operation is required"],
    steps: ["Draw the grid connection, loads, solar and battery energy paths", "Select a control family approved for the local grid", "Place the meter/CT at the required point of common connection", "Check phase count, CT direction and communications", "Configure the approved export profile/limit", "Test under load and generation conditions", "Save settings, measured results and utility approval"],
    checks: ["Zero export is not described as off-grid", "Loss of meter/communications has a defined safe response", "Every generating inverter is included in the control scheme", "Commissioning proves the limit rather than assuming it"],
    source: "Enphase export-limitation technical guidance illustrates that export control depends on correct Site measurement and configuration; use the selected platform and local network process.",
    sourceUrl: "https://enphase.com/en-gb/download/g100-2-export-and-import-limitation-configuration-and-witness-testing-tech-brief"
  },
  {
    group: "Start here: system choices",
    id: "staged-expansion",
    title: "Build in stages without buying everything twice",
    image: "/schematic-components/ac-distribution-board.jpg",
    summary: "Plan the final destination now, then define safe, useful stages that work within today's budget.",
    keywords: ["add later", "expandable", "future proof", "start small", "budget", "more batteries later", "more panels later"],
    whatItIs: "A staged design records the final load/backup goal and the limits/interfaces of each affordable intermediate system.",
    whatItDoes: "It reserves physical, electrical and communication capacity while exposing components that cannot simply be enlarged later.",
    before: ["Write the likely final daily energy, peak power and backup goal", "Record available roof/ground area and grid limit", "Set a budget and expected timing for each stage"],
    steps: ["Draw the final energy-flow schematic first", "Mark inverter input, output, MPPT, battery and communication limits", "Check which batteries permit later parallel additions and under what conditions", "Reserve board space, cable paths, mounting area and service clearance", "Choose a complete useful first stage", "Document the change required for every future stage", "Review compatibility again at each purchase because product revisions change"],
    checks: ["First stage works safely on its own", "Future panel strings stay inside voltage/current limits", "Future battery additions are explicitly permitted", "Reserved cable/board/physical capacity is recorded", "Expansion assumptions are not presented as guaranteed"],
    source: "Staging is product-specific; use current module, inverter, battery/BMS, board and network limits for every stage."
  },
  {
    group: "Inverters and power conversion",
    id: "inverter-types",
    title: "String, hybrid, off-grid and inverter/charger choices",
    image: "/schematic-components/string-inverter.jpg",
    summary: "The boxes may look similar, but their grid, battery, backup and generator jobs are not interchangeable.",
    keywords: ["which inverter", "string inverter", "hybrid inverter", "offgrid inverter", "inverter charger", "grid forming", "grid following"],
    whatItIs: "String inverters normally convert a PV string to AC; hybrid units combine PV and battery functions; inverter/chargers manage a battery and AC sources; off-grid/grid-forming units create a local supply without relying on the utility waveform.",
    whatItDoes: "The selected type determines energy paths, blackout behaviour, battery compatibility, grid approval and which other boxes are needed.",
    buy: ["Nothing until required operating modes are written down", "Exact compatible battery/BMS and meter/control hardware", "Required PV controller, transfer, protection and communication accessories"],
    before: ["Define grid present/absent, export, blackout, generator and battery requirements", "Record continuous, surge and unbalanced/phase loads", "Check whether the unit can start without the grid"],
    steps: ["Compare required modes against each candidate's wiring diagrams", "Check PV voltage/current/MPPT limits", "Check battery voltage/current/BMS list", "Check continuous, surge, temperature and phase ratings", "Check backup transfer time and neutral/earth method", "Check generator and export-control support", "Save the exact approved configuration—not only the model name"],
    checks: ["Grid-following solar is not assumed to work in a blackout", "Battery-ready marketing is supported by an actual compatible battery path", "Every operating mode has a valid schematic"],
    source: "US Department of Energy inverter overview; final behaviour comes from the exact inverter manual and local approval.",
    sourceUrl: "https://www.energy.gov/cmei/systems/solar-integration-inverters-and-grid-services-basics"
  },
  {
    group: "AC wiring and connections",
    id: "generator-integration",
    title: "Add a generator without unsafe backfeed",
    image: "/schematic-components/generator.jpg",
    summary: "Treat a generator as a controlled AC source so it cannot accidentally energise the grid, another inverter output, or a circuit someone believes is switched off.",
    keywords: ["genset", "generator backup", "generator inlet", "shore power", "AC input", "auto start", "backfeed", "suicide lead", "changeover", "transfer switch", "interlock"],
    whatItIs: "A generator connection starts with its destination: a documented inverter generator/AC input, or a switchboard supply path. Each route needs the applicable connection, isolation and protection; changeover or transfer equipment is added only where the sources and local rules require it. Unsafe backfeed means generator power is allowed to flow backwards into wiring that should be isolated.",
    whatItDoes: "It lets the generator power selected loads or charge batteries when solar is insufficient while physically or electrically preventing power from feeding the public grid, another AC source, an inverter output, or a disconnected circuit.",
    usedFor: ["Off-grid generator charging", "Hybrid inverter AC input", "Backup loads during outages", "Manual changeover switches", "Automatic transfer switches", "Shore-power style inlets"],
    types: [
      { name: "Hybrid-inverter generator input", image: "/schematic-components/hybrid-inverter.jpg", description: "The generator feeds an AC/generator input that the exact inverter documents for this purpose, through the required isolation and circuit protection.", bestFor: "Hybrid or inverter/charger systems whose approved wiring diagram includes generator input and internal transfer behaviour.", watchFor: "Confirm whether the input is dedicated or shared with grid AC, its voltage/frequency acceptance, current limit, neutral/earth behaviour and battery-free operating support." },
      { name: "Generator AC input breaker", image: "/schematic-components/generator-ac-input-breaker-v2.png", description: "A suitably configured AC circuit breaker protects the generator feed before its approved inverter or switchboard destination.", bestFor: "The overcurrent-protection point required by the exact inverter or generator connection diagram.", watchFor: "Do not assume 63 A from another installation. Confirm the manual's required current, poles, trip behaviour and breaking capacity, then coordinate the breaker with the cable, terminals, source fault conditions and local rules. It counts as an isolation point only when the selected device and rules permit that use." },
      { name: "DIN-rail breaker enclosure", image: "/schematic-components/din-rail-enclosure-unbranded.png", description: "A covered enclosure houses the generator-input breaker and other approved DIN-rail devices while providing cable entry, access and protection from contact and the surrounding environment.", bestFor: "A separate breaker location where the device is not already inside a suitable switchboard or equipment enclosure.", watchFor: "Choose the usable module width, cable-entry and gland arrangement, cover, material, fire properties and ingress-protection rating for the actual indoor or outdoor location. Follow the equipment instructions and local accessibility, labelling, segregation and earthing rules." },
      { name: "Approved generator inlet", image: "/schematic-components/generator-inlet-box.jpg", description: "A fixed inlet or hardwired connection point that feeds the selected inverter or switchboard route in the intended direction.", bestFor: "Connecting a portable generator without exposed live plug pins or informal leads.", watchFor: "An inlet does not by itself provide source transfer, fault protection or prove the downstream connection is compliant." },
      { name: "Manual changeover switch", image: "/schematic-components/ac-disconnect-isolator.jpg", description: "A mechanically controlled switch that selects one AC source while disconnecting the other.", bestFor: "Simple systems where a person starts the generator and changes source deliberately.", watchFor: "The switch must break and make the required poles for the local earthing/neutral arrangement." },
      { name: "Automatic transfer switch", image: "/schematic-components/automatic-transfer-switch-ats.jpg", description: "A device that changes source automatically under defined voltage/frequency and timing rules.", bestFor: "Systems needing automatic generator or grid transfer.", watchFor: "ATS ratings, neutral switching, source priority and failure modes must match the inverter/generator design." },
      { name: "Remote start controller", image: "/schematic-components/automatic-transfer-switch-ats.jpg", description: "A compatible relay or controller asks a remote-start-capable generator to start and stop under defined conditions.", bestFor: "Systems that explicitly require automatic operation based on supported conditions such as load, battery state or source failure.", watchFor: "Auto-start is separate from source transfer. Confirm failed-start handling, warm-up, cool-down, minimum run time, communications failure and safe unattended operation." }
    ],
    questions: [
      { question: "What is unsafe backfeed in plain English?", answer: "It is electricity going backwards into a wire, switchboard, grid line or appliance circuit that is supposed to be off or supplied from somewhere else. With a generator, that can put live voltage on grid lines during an outage or make two AC sources fight each other." },
      { question: "Why is a male-to-male generator lead dangerous?", answer: "One end can have exposed live pins, and it can feed power backwards into a building circuit without a proper transfer switch, protection, earthing or isolation." },
      { question: "Does turning off the main breaker prevent backfeed?", answer: "Not necessarily. The approved design must show the actual interlock or transfer device, which poles are switched, and every source that can energise the board." },
      { question: "Can a generator and inverter both feed the same loads?", answer: "Only through an arrangement designed for that. The transfer, synchronisation or inverter AC-input rules decide whether they are separated, passed through, charged from, or paralleled." },
      { question: "Does every hybrid inverter need a separate changeover switch?", answer: "No. If the exact inverter manual provides an approved generator input and internal transfer path, the external design may instead need the specified inlet or fixed connection, isolation and protection. A switchboard feed or competing AC sources can still require separate changeover or transfer equipment." },
      { question: "Is the generator-input breaker always 63 A?", answer: "No. A 63 A breaker appears in some inverter wiring instructions, while other models specify smaller or larger values. Use the exact model's manual and coordinate its maximum AC-input current, required poles, trip behaviour and fault rating with the cable and local electrical rules." },
      { question: "Does the breaker need its own DIN-rail enclosure?", answer: "Only when it is not already mounted in a suitable approved switchboard or equipment enclosure. A separate box must have enough DIN space and must suit the location, cable entries, environmental exposure, access, labelling and local installation rules." },
      { question: "What should the schematic show?", answer: "Show the generator's actual destination first, then its inlet or fixed connection, isolation, protection, any source transfer or interlock, grid and inverter AC paths, neutral/earth behaviour and the loads energised in each operating mode." }
    ],
    buy: ["Generator suitable for the expected loads and inverter/charger", "AC input breaker or other protection specified for the chosen route", "Suitable DIN-rail enclosure when the breaker is not housed in existing approved equipment", "Connection and isolation equipment required by the exact manuals and local rules", "Changeover/transfer equipment only when the source topology requires it", "Optional remote-start controller only when requested and supported"],
    before: ["Resolve the Site country, jurisdiction and any connected network operator", "Confirm generator voltage, frequency, continuous/surge rating and waveform requirements", "Choose whether the generator feeds the inverter input or switchboard", "Define neutral/earth arrangement in generator mode", "Identify every source that could energise the same AC conductors", "Plan exhaust, fuel, noise, weather and safe operating location"],
    steps: ["Draw every AC source and its destination", "Apply the current local installation, stand-alone-system and network requirements", "Mark which circuits are live from grid, generator and inverter in each operating mode", "Check generator starting and continuous capability", "Read the exact inverter generator-input diagram and record its breaker, cable, poles, enclosure and connection requirements", "Set the inverter/charger input-current limit where applicable", "Install the approved connection, isolation, protection and any required transfer equipment", "Configure acceptance, charging and optional auto-start rules", "Test that grid/inverter/generator sources cannot backfeed each other", "Test transfer with increasing loads", "Test shutdown, failed-start and low-fuel scenarios", "Save the source documents, review dates and final operating card"],
    checks: ["Grid backfeed is physically/control-system prevented", "Generator-input breaker and conductors are coordinated to the exact equipment manual and fault conditions", "Any separate enclosure suits its devices, cable entries, access and installation environment", "No exposed live plug pins or improvised generator lead exists", "Generator cannot be paralleled with an inverter or grid source unless the exact system is designed for it", "Generator cannot be operated in an unsafe location", "Charging plus loads stay within generator rating", "Neutral/earth operation is tested in each mode"],
    source: "Topology guide informed by inverter generator-input/transfer documentation. For New Zealand Sites, also check the current Electricity (Safety) Regulations, WorkSafe guidance, AS/NZS 3000, AS/NZS 3010 or AS/NZS 4509.1 as applicable, plus the local network's rules. Other jurisdictions require their own current official overlay.",
    sourceUrl: "https://www.worksafe.govt.nz/about-us/news-and-media/connecting-a-generator-to-the-wiring-of-a-house-or-building-following-an-emergency/"
  },
  {
    group: "Protection and isolation",
    id: "fuse-breaker-isolator",
    title: "Fuse, breaker or isolator: three different jobs",
    image: "/schematic-components/dc-fuse.jpg",
    summary: "A switch is not automatically fault protection, and a fuse is not automatically a safe everyday switch.",
    keywords: ["fuse vs breaker", "disconnect", "shutoff", "safety switch", "MCB", "MCCB", "isolator"],
    whatItIs: "A fuse opens by melting under excess current; a circuit breaker trips and may be reset; an isolator/disconnect provides a defined switching and isolation point. Product combinations can perform more than one stated function.",
    whatItDoes: "Correctly selected devices protect conductors/equipment and provide controllable shutdown zones.",
    buy: ["Device explicitly rated for circuit DC or AC voltage/current and duty", "Adequate interrupt rating for available fault current", "Correct poles, enclosure, terminals and fuse class where applicable"],
    before: ["Trace every possible source into the cable section", "Determine conductor capacity and equipment protection limits", "Check whether the device may interrupt load current or only isolate after shutdown"],
    steps: ["Mark the protected cable/equipment on the schematic", "Assign the required job: overcurrent protection, isolation or both", "Calculate ratings and interrupt duty", "Choose a listed device for that exact job and polarity/topology", "Place it where the required zone can be safely reached", "Label source/load and shutdown order", "Test operation and save the exact part/rating"],
    checks: ["No AC-only breaker on PV/battery DC", "Isolator switching category matches the real load", "Fuse holder and fuse are a compatible pair", "Every cable leaving a high-current source has accounted-for protection"],
    source: "Use the circuit design, local wiring rules and exact fuse/breaker/isolator application data."
  },
  {
    group: "Mounting systems and hardware",
    id: "flat-roof-ballast",
    title: "Flat-roof ballast, membrane and wind zones",
    image: "/guides/mounting/flat-roof-tilt-frame-web.jpg",
    summary: "A weighted frame still needs a structural, wind and waterproofing design; more concrete is not a universal answer.",
    keywords: ["flat roof", "ballasted solar", "concrete blocks", "membrane roof", "tilt frame", "wind uplift"],
    whatItIs: "A ballasted array uses distributed weight and aerodynamic layout instead of—or alongside—roof penetrations.",
    whatItDoes: "It resists sliding and uplift while pads and layout protect the roof membrane and drainage.",
    buy: ["Engineered ballasted mounting family", "Compatible membrane protection/separation pads", "Specified ballast, wind deflectors, bonding and cable supports"],
    tools: ["Roof and structural survey", "Ballast/layout schedule", "Lifting/weight-handling plan", "Torque and alignment tools"],
    before: ["Confirm roof load capacity and membrane compatibility", "Map drains, ponding, edges, corners, fire/access paths and maintenance zones", "Use the Site wind/snow/seismic design"],
    steps: ["Survey levels, membrane condition and drainage", "Set out each wind zone and row", "Place approved pads without trapping debris or water", "Assemble frames and deflectors to the schedule", "Place the specified ballast at each exact location", "Install modules, bonding and cable support", "Record every ballast quantity and final roof condition"],
    checks: ["Total and point loads are approved", "Edge/corner zones match the engineering", "No blocked drain or damaged membrane", "Ballast cannot move or damage cables"],
    source: "Use the exact flat-roof system engineering, roof manufacturer requirements and Site structural/wind design."
  },
  {
    group: "Mounting systems and hardware",
    id: "ground-mount-foundations",
    title: "Ground-mount posts, foundations and cable approach",
    image: "/guides/mounting/manufactured-metal-ground-rack.png",
    summary: "Start below ground: soil, foundations, drainage, corrosion, services and cable entry control the frame above.",
    keywords: ["ground solar", "posts", "concrete footing", "ground screws", "pile", "solar frame", "garden array"],
    whatItIs: "A ground array is a freestanding engineered structure using driven posts, ground screws, concrete footings or another site-specific foundation.",
    whatItDoes: "It supports array wind, snow and seismic loads while keeping modules and cables clear of vegetation, flooding, animals and people.",
    buy: ["Engineered frame/foundation system", "Corrosion-compatible posts, rails and fasteners", "Protected underground cable entry, bonding and warning/guarding parts"],
    before: ["Locate underground services and boundaries", "Assess soil, slope, drainage/flooding and corrosion exposure", "Check planning/setback/fence requirements and future shading"],
    steps: ["Survey and stake array corners and row lines", "Verify service clearances", "Install foundations to engineered depth/geometry", "Set posts plumb and consistent", "Fit bracing, rails and bonding", "Install protected cable risers before modules restrict access", "Fit modules/clamps and animal/public protection", "Record foundation locations and buried services"],
    checks: ["Foundation evidence matches the Site design", "Frame is square, braced and corrosion-protected", "No exposed reachable cable or connector", "Drainage and vegetation maintenance remain possible"],
    source: "Use the exact ground-mount engineering and local structural, planning, excavation and electrical requirements."
  },
  {
    group: "Pools and controllable loads",
    id: "pool-solar-thermal",
    title: "Solar-thermal pool heating",
    image: "/schematic-components/solar-panel-pv-module.jpg",
    summary: "Use roof or ground collectors to move heat directly into pool water through a filtered, controlled plumbing loop.",
    keywords: ["heat pool", "pool solar", "rubber pool panels", "solar pool mat", "pool collector", "spa heating"],
    whatItIs: "Unglazed or glazed thermal collectors heat circulating pool water rather than producing electricity.",
    whatItDoes: "It can extend the swimming season with low electrical input beyond the circulation pump, depending on climate, collector area, cover and operating schedule.",
    buy: ["Pool-rated collectors and mounting system", "Compatible pipe, valves, check/vacuum relief and controller/sensors", "Pump capacity or dedicated pump arrangement", "Pool cover where practical"],
    tools: ["Pool volume and target-temperature record", "Roof/ground area and hydraulic route survey", "Plumbing flow/head calculation", "Collector and roof manuals"],
    before: ["Separate thermal collectors from PV electrical panels", "Check roof load, penetrations, drainage and freeze/stagnation requirements", "Record pool chemistry/material compatibility"],
    steps: ["Measure pool volume, season and target temperature", "Estimate heat loss and useful collector area", "Choose collector location and plumbing route", "Check pump flow/head and filtration connection point", "Design isolation, drainage and control sensors", "Install mounts/collectors and supported pipework", "Commission flow, control and leak checks", "Record winterising and shutdown procedure"],
    checks: ["Collector/plumbing materials suit pool chemistry and climate", "Roof and water details remain serviceable", "Flow direction and controls are clear", "The owner understands seasonal drain/freeze/overheat needs"],
    source: "Use the selected pool-heating collector, controller, pump and roof-system manuals plus local plumbing/building requirements."
  },
  {
    group: "Pools and controllable loads",
    id: "pool-heat-pump",
    title: "Pool heat pump powered around solar hours",
    image: "/schematic-components/smart-load-relay-controller.jpg",
    summary: "Treat the pool heat pump and circulation pump as controllable loads, then schedule them when solar and outdoor conditions are favourable.",
    keywords: ["pool heatpump", "pool heater", "swimming pool power", "timer", "solar diversion", "excess solar"],
    whatItIs: "An electric heat pump transfers heat from ambient air into pool water; it also depends on water circulation and adequate airflow.",
    whatItDoes: "It can turn daytime solar production into stored heat in the pool, but its electrical input, start behaviour and seasonal performance still affect inverter/grid sizing.",
    buy: ["Pool heat pump sized for climate, volume and season", "Required circulation/flow equipment and bypass", "Correct AC circuit/protection and approved control interface", "Pool cover where practical"],
    tools: ["Pool volume/heat-loss worksheet", "Electrical nameplate and starting data", "Hydraulic flow/head data", "Solar/energy monitoring"],
    before: ["Record target temperature, season and recovery time", "Check minimum airflow, drainage, noise and service clearances", "Confirm whether control input permits solar-aware scheduling without defeating safety controls"],
    steps: ["Estimate required heat and select a climate-appropriate unit", "Include circulation-pump energy", "Check AC continuous/start load against supply/inverter", "Design plumbing bypass and minimum flow", "Place equipment with required airflow and condensate drainage", "Set daytime/solar-priority scheduling", "Monitor energy, water temperature and runtime", "Adjust schedule before adding battery capacity solely for heating"],
    checks: ["Heat-pump and pump loads appear in Site energy data", "Flow and airflow stay inside manufacturer limits", "Control never bypasses freeze/flow/safety interlocks", "Performance expectations reflect local air temperature"],
    source: "Use the exact pool heat-pump, circulation and control manuals; heat pumps move heat rather than creating it by resistance.",
    sourceUrl: "https://www.energy.gov/energysaver/heat-pump-systems"
  }
] as const;
