// The How-to library is deliberately separate from the page component so it can
// grow into a proper reference catalogue without making navigation code harder
// to maintain. Every guide stays product-neutral until an exact model is known.

export const expandedHowToGuides = [
  {
    group: "Roofing and roof structure",
    id: "roof-find-structure",
    title: "Find rafters, battens and purlins",
    image: "/guides/mounting/corrugated-metal-timber.png",
    summary: "Identify what actually holds the roof up before choosing a solar fixing or drilling a hole.",
    keywords: ["roof timber", "roof steel", "wooden purlin", "rafter", "batten", "truss", "stud finder", "roof screw"],
    whatItIs: "Rafters, trusses and purlins are structural members. Battens may support roof cladding, but are not automatically suitable for solar loads. Roof sheet, tile and membrane are weather layers, not proof of structure.",
    whatItDoes: "A confirmed structural fixing path transfers panel wind and weight loads into the building instead of relying on thin cladding.",
    tools: ["Roof framing drawings or builder records", "Safe access to inspect the roof from below", "Tape, camera and non-permanent marker", "A detection tool only as a clue, never as the sole proof"],
    before: ["Record the roof material, pitch, age and condition", "Stop for asbestos-suspect, brittle, corroded or inaccessible roofs", "Have the mounting layout and local wind/snow design available"],
    steps: ["Inspect the framing from inside the roof space where safe access exists", "Identify member direction, spacing, dimensions and material", "Relate internal framing to visible external reference points", "Mark a test location and confirm it using a permitted non-destructive or controlled method", "Record photos and measured centres on the Site roof plan", "Give the confirmed substrate details to the mounting designer before selecting fasteners"],
    checks: ["Every proposed fixing line maps to confirmed structure", "Timber/steel type and relevant dimensions are recorded", "Uncertain areas remain marked unverified"],
    source: "Roof structure and fixing capacity must be verified for the Site; detection tools do not replace structural evidence."
  },
  {
    group: "Roofing and roof structure",
    id: "roof-entries-flashing",
    title: "Cable roof entries, flashing and waterproofing",
    image: "/schematic-components/roof-mounting-system.jpg",
    summary: "Bring cables through the roof using a planned weatherproof entry that preserves drainage, cable protection and service access.",
    keywords: ["roof gland", "cable gland", "flashing", "sealant", "roof leak", "conduit", "deck seal", "penetration"],
    whatItIs: "A roof entry is a compatible flashing, gland or service penetration that joins the roof weather layer to cable conduit or a protected cable route.",
    whatItDoes: "It prevents water, abrasion, sunlight and movement from damaging the roof or cables where they pass into the building.",
    buy: ["Entry/flashing made for the exact roof profile or membrane", "UV- and environment-rated gland, conduit and cable support", "Roof-manufacturer-approved primer/sealant where specified", "Edge protection and internal fire/weather sealing required by the local design"],
    tools: ["Template and non-permanent marker", "Correct hole/cutting tool with swarf capture", "Surface preparation tools", "Torque tool for glands where specified"],
    before: ["Choose a high, drained location away from valleys and ponding", "Check structure, hidden services and access on both sides", "Confirm roof warranty and flashing compatibility"],
    steps: ["Mark the complete entry footprint and cable bend path", "Prepare the roof exactly as the entry maker specifies", "Cut only the required opening and remove all sharp edges and debris", "Fit the flashing in the correct water-shedding order", "Fit conduit/glands without crushing cable and maintain bend radius", "Support and label cables on both sides", "Photograph the open and completed weather detail"],
    checks: ["Water flows over and around the entry without a dam", "No exposed sharp edge or unsupported cable", "Gland, flashing and sealant match the roof and cable", "The entry remains accessible for inspection"],
    source: "Use the exact roof, flashing, gland and cable-system instructions; sealant alone is not a universal flashing detail."
  },
  {
    group: "Mounting systems and hardware",
    id: "mount-direct-attach",
    title: "Rail-less and direct-attach mounts",
    image: "/schematic-components/roof-mounting-system.jpg",
    summary: "Attach modules with a tested direct-mount family only when its roof, module frame and structural load tables all match.",
    keywords: ["railless", "rail free", "direct mount", "mini rail", "short rail", "roof foot"],
    whatItIs: "A direct-attach or short-rail system replaces long rails with small tested attachment points beneath module clamp zones.",
    whatItDoes: "It reduces rail material but makes accurate structural placement, roof-profile fit, module clamp zones and array alignment especially important.",
    buy: ["Complete tested attachment family", "Correct roof interface and structural fastener", "Approved module clamps, bonding parts and cable supports"],
    tools: ["Accurate layout tools", "Correct driver/socket", "Calibrated torque wrench", "Roof-profile and structure records"],
    before: ["Confirm module frame/clamp compatibility", "Use the engineered attachment spacing for local loads", "Check roof drainage and thermal movement"],
    steps: ["Map confirmed structural fixing points", "Set the first row square and to the product layout", "Install and weatherproof each interface", "Set attachment height/alignment before modules cover it", "Clamp modules only in approved zones", "Fit bonding and cable support from the same system"],
    checks: ["No attachment relies on cladding alone", "Modules are aligned without twisting frames", "All torque and weather details are recorded"],
    source: "Use one complete tested mounting family and its current engineering/installation documents."
  },
  {
    group: "DC wiring and connections",
    id: "connector-compatibility",
    title: "Do not mix look-alike solar connectors",
    image: "/guides/mc4/mc4-assembly-overview.png",
    summary: "Two solar plugs can click together and still be an unapproved, high-resistance cross-mated connection.",
    keywords: ["MC4 compatible", "solar plug", "male female plug", "cross mate", "connector brand", "adapter"],
    whatItIs: "PV connectors are a matched housing, contact, seal, cable range and assembly process from a named manufacturer and product family.",
    whatItDoes: "A correctly matched pair keeps contact pressure and sealing within the tested system; a look-alike pair may not.",
    buy: ["The exact connector manufacturer and family listed for the module or equipment", "Correct contact for the selected cable cross-section", "Approved same-family transition lead if equipment ends differ"],
    tools: ["Label camera", "Manufacturer selector/compatibility table", "Exact strip, crimp and assembly tools for that connector"],
    before: ["Read the moulded manufacturer/type marks on both halves", "Check the module and equipment manuals for permitted mates", "Do not accept a generic 'MC4 compatible' description as evidence"],
    steps: ["Record the connector on every supplied module and device lead", "Choose one approved mating family for each connection", "Replace or use an approved transition lead where families differ", "Assemble new ends only with the maker's cable range and tools", "Label and photograph the completed connector family", "Keep connectors unmated and protected until testing/connection"],
    checks: ["Both mated halves are an approved pairing", "Cable diameter and conductor size fit the connector", "No improvised adaptor or cut-off warranty lead"],
    source: "Stäubli: avoid cross-mating; connect approved products from the same manufacturer/family.",
    sourceUrl: "https://www.staubli.com/global/en/electrical-connectors/industries/renewable-energy/cross-connection.html"
  },
  {
    group: "DC wiring and connections",
    id: "battery-cables-lugs",
    title: "Battery cables, lugs and terminal stacking",
    image: "/schematic-components/pv-cable-dc.jpg",
    summary: "High-current battery links need calculated cable, correctly crimped lugs, protected studs and controlled torque.",
    keywords: ["battery lead", "battery link", "cable lug", "ring terminal", "crimp lug", "terminal stack", "battery cable size"],
    whatItIs: "Short, heavy DC conductors link batteries, fuses, switches, busbars, shunts and the inverter.",
    whatItDoes: "They carry large continuous and surge currents with acceptable heating and voltage drop while remaining mechanically secure.",
    buy: ["Calculated flexible battery cable with correct insulation rating", "Tinned copper lugs sized for both conductor and stud", "Adhesive heat-shrink and identification", "Terminal boots/covers and strain support"],
    tools: ["Cable cutter", "Lug-maker-approved crimper and die", "Heat-shrink tool", "Calibrated torque wrench", "Inspection gauge where specified"],
    before: ["Calculate current, length, voltage drop, temperature and fault current", "Read every terminal's allowed lug count and torque", "Plan fuse position close to the energy source as the approved design requires"],
    steps: ["Measure the real route and allow strain-free bends", "Cut square and strip without nicking strands", "Insert the conductor fully into the correct lug", "Crimp using the stated die and number/orientation of compressions", "Seal and identify both ends", "Clean, assemble and torque the terminal stack in the maker's order", "Fit covers and support cable so weight cannot pull on the stud"],
    checks: ["No exposed strands, loose lug or rotating terminal", "Cable/lug/stud sizes and polarity match the drawing", "Terminal stack and torque follow the exact manual", "Positive conductors are protected from accidental contact"],
    source: "Use the cable/lug tooling data and exact battery, fuse, busbar, shunt and inverter terminal manuals."
  },
  {
    group: "Batteries and charging",
    id: "battery-bank-layout",
    title: "One battery or a series/parallel battery bank",
    image: "/schematic-components/lifepo4-battery-bank.jpg",
    summary: "Build voltage and capacity only from batteries permitted to operate together, with balanced current paths and individual protection where required.",
    keywords: ["battery bank", "series battery", "parallel battery", "24 volt", "48 volt", "balanced cables", "drop in lithium"],
    whatItIs: "Series connections add voltage; parallel connections add amp-hour capacity and available current. Series-parallel banks do both.",
    whatItDoes: "It forms the DC storage source expected by the inverter while sharing charge/discharge current between compatible batteries.",
    buy: ["Same approved battery model/revision and compatible state/age as required by the maker", "Equal-current-path cables or manufacturer busbar system", "Required battery-level fuses, disconnects and communication terminators"],
    tools: ["Insulated hand tools", "Correct lug crimper and torque wrench", "Battery voltage/state-of-charge measurement method", "Label and cable-length records"],
    before: ["Confirm the maker permits the proposed series and parallel counts", "Confirm BMS communications/topology", "Match bank voltage to inverter and chargers", "Plan safe isolation before assembling links"],
    steps: ["Number and record every battery", "Bring units to the maker-required state before paralleling", "Lay out equal or designed current paths", "Install battery-level protection and disconnect arrangement", "Make controlled connections in the stated safe sequence", "Connect BMS communication and termination", "Configure the inverter/chargers for the exact bank"],
    checks: ["No mixed chemistry or unsupported battery combination", "Polarity and bank voltage verified", "Current paths and protection match the approved drawing", "Every battery is visible in BMS/monitoring"],
    source: "Use the exact battery maker's parallel/series, BMS and commissioning instructions."
  },
  {
    group: "Batteries and charging",
    id: "shunt-battery-monitor",
    title: "Battery shunt and state-of-charge monitor",
    aliases: ["Coulometer", "Battery monitor", "Amp-hour counter", "Shunt monitor", "State-of-charge meter"],
    image: "/guides/battery/battery-shunt-coulometer.png",
    summary: "Put the shunt in the one negative path so it measures every charge and every load.",
    keywords: ["smart shunt", "battery gauge", "SOC", "state of charge", "battery monitor", "negative busbar"],
    whatItIs: "A shunt is a precise low-resistance measuring element placed between battery negative and the system negative busbar.",
    whatItDoes: "It measures current into and out of the bank so the monitor can estimate state of charge and energy use.",
    buy: ["Shunt rated for the maximum continuous and surge current", "Short calculated battery-negative cable", "Fused positive sense lead and communications/display parts"],
    tools: ["Correct lug/crimp tools", "Torque wrench", "Configuration app/display", "Cable labels"],
    before: ["Confirm system-negative and battery-negative sides", "Plan one path: no charger or load negative may bypass the shunt", "Check stud size, terminal count and torque"],
    steps: ["Mount the shunt close to the bank in a protected location", "Connect only the battery bank to BATTERY MINUS", "Connect the entire DC system negative busbar to SYSTEM/LOAD MINUS", "Fit the fused positive sense lead as the manual shows", "Connect communications/display", "Configure capacity, charged voltage and efficiency", "Synchronise only after a verified full charge"],
    checks: ["All chargers and loads are after the shunt", "No negative bypass exists", "Current direction and zero reading are sensible", "Settings match the actual battery bank"],
    source: "Victron SmartShunt installation example; use the exact selected monitor manual.",
    sourceUrl: "https://www.victronenergy.com/media/pg/SmartShunt/en/installation.html"
  },
  {
    group: "Inverters and power conversion",
    id: "charge-controller-selection",
    title: "Choose an MPPT solar charge controller",
    image: "/schematic-components/mppt-charge-controller.jpg",
    summary: "Match the coldest-case panel voltage and charging current to both the controller and battery—not just panel watts.",
    keywords: ["MPPT size", "solar regulator", "charge regulator", "controller amps", "controller voltage", "PV input"],
    whatItIs: "An MPPT controller converts higher-voltage PV DC into controlled battery-charging voltage and current.",
    whatItDoes: "It tracks available panel power while applying the battery maker's permitted charge profile and limits.",
    buy: ["Controller with adequate PV voltage, PV current/power and battery-charge rating", "Required PV and battery protection/isolation", "Battery temperature sensor or BMS communications where required"],
    tools: ["Cold-temperature string-voltage worksheet", "Module and controller datasheets", "Battery charge-limit data", "Cable/protection calculation"],
    before: ["Calculate maximum cold Voc", "Check operating Vmp against MPPT range", "Calculate maximum output current at bank voltage", "Check battery/BMS allowed charge current"],
    steps: ["Choose the battery-bank voltage", "Define module series/parallel arrangement", "Check absolute PV voltage and short-circuit-current limits", "Check usable PV power and output-current rating", "Select protection and cable on both sides", "Confirm ventilation, mounting and communication", "Save all assumptions and limits with the proposed schematic"],
    checks: ["Cold Voc stays below the absolute limit", "Operating voltage stays inside MPPT range", "Controller and battery charge-current limits are respected", "The device is compatible with the battery/BMS"],
    source: "Use the exact module, controller and battery datasheets; PV input limits and battery output limits are separate checks."
  },
  {
    group: "AC wiring and connections",
    id: "backup-loads-changeover",
    title: "Backup loads board and changeover",
    image: "/schematic-components/automatic-transfer-switch-ats.jpg",
    summary: "Decide exactly which circuits stay on, then use an approved changeover arrangement that cannot backfeed an unsafe source.",
    keywords: ["essential loads", "critical loads", "backup board", "transfer switch", "changeover", "blackout", "island mode"],
    whatItIs: "A dedicated backup/essential-loads board and manual or automatic transfer arrangement separates selected circuits from ordinary supply paths.",
    whatItDoes: "It allows a suitable inverter or generator to supply chosen loads during an outage while controlling source transfer, neutral and earthing behaviour.",
    buy: ["Approved transfer/changeover equipment", "Dedicated distribution/protection equipment", "Labels and interlocks required by the design", "Load-shedding control where the source cannot supply everything"],
    tools: ["Circuit/load schedule", "Inverter backup-output data", "Fault/earthing design", "Authorised AC test equipment"],
    before: ["List each backed-up circuit and starting surge", "Confirm inverter neutral/earth behaviour in every mode", "Confirm grid/generator interlock and local connection rules"],
    steps: ["Create the source and load single-line drawing", "Separate selected circuits into the planned board", "Install the approved changeover and protection", "Label every source and shutdown point", "Test normal supply, outage transfer, overload and restoration", "Record the final circuit schedule and operating instructions"],
    checks: ["No possible unsafe backfeed", "Neutral/earth arrangement is correct in every mode", "Backup load stays within inverter continuous and surge limits", "The user can perform shutdown and restart safely"],
    source: "This is mains-voltage work: use the exact inverter/transfer manuals, local electrical rules and authorised installer/inspection process."
  },
  {
    group: "Protection and isolation",
    id: "surge-protection",
    title: "Surge protection devices (SPD)",
    image: "/schematic-components/surge-protection-device-spd.jpg",
    summary: "Select and place surge protection as a coordinated system; a random SPD does not protect every circuit.",
    keywords: ["SPD", "lightning protection", "surge arrester", "transient", "type 1", "type 2"],
    whatItIs: "An SPD diverts short-duration overvoltage toward the designed earthing path. DC and AC devices, voltage ratings and system arrangements differ.",
    whatItDoes: "It limits transient stress on inverters, controllers and connected equipment when correctly selected, connected and earthed.",
    buy: ["Correct DC or AC SPD type and voltage configuration", "Upstream protection required by its manual", "Shortest practical conductors and compatible enclosure/indicator contacts"],
    tools: ["System voltage/earthing data", "Manufacturer coordination table", "Cable routing and torque tools"],
    before: ["Assess lightning/exposure and local requirements", "Identify every protected zone and conductor", "Check maximum continuous operating voltage and short-circuit rating"],
    steps: ["Place SPD locations on the schematic", "Select AC/DC type and pole arrangement", "Plan very short, direct connection paths", "Coordinate backup protection", "Install, torque and label", "Record indicator state and replacement method"],
    checks: ["No AC SPD substituted on PV DC", "Voltage and topology match the circuit", "Earth path is short and intentional", "Status indication remains visible"],
    source: "Use the SPD coordination/application guide, inverter requirements, local lightning assessment and wiring rules."
  },
  {
    group: "DC wiring and connections",
    id: "cable-route-planning",
    title: "Plan every cable run before buying cable",
    image: "/schematic-components/pv-cable-dc.jpg",
    summary: "Draw the real route from source to destination, including protection, bends, entries, heat, movement and service loops.",
    keywords: ["wire run", "cable run", "cable route", "voltage drop", "wire length", "homerun", "service loop", "cable path"],
    whatItIs: "A cable-run plan records where each positive, negative, AC, earth and communication cable starts, ends and physically travels.",
    whatItDoes: "It provides the actual length and installation conditions needed to choose cable size, protection and containment—and prevents a safe-looking schematic from becoming an unsafe physical route.",
    buy: ["No cable until route length, circuit current/voltage and installation method are known", "Route-specific supports, conduit, glands, junctions and labels", "Edge, heat, animal and impact protection for each exposed section"],
    tools: ["Site plan and proposed schematic", "Tape/laser measure", "Camera and route labels", "Cable-sizing and voltage-drop worksheet"],
    before: ["Separate the electrical circuit calculation from the physical route survey", "Identify hot roofs, insulated walls, wet areas, buried sections, movement joints and public access", "Locate isolation/protection so it remains reachable"],
    steps: ["Give every circuit a plain name and unique ID", "Walk from its source to destination and mark each change of environment", "Measure the complete path including vertical rises, bends and service loops", "Mark where containment begins/ends and every roof, wall or floor entry", "Record grouped circuits and surrounding temperature for derating", "Calculate conductor size and voltage drop from the real route", "Add support, pull/access points, glands and labels", "Transfer the physical route onto the proposed schematic and build sheet"],
    checks: ["Every conductor has a source, destination and purpose", "Actual route—not straight-line distance—was used", "Cable remains supported, protected and replaceable where required", "Ratings account for heat, grouping, enclosure and environment"],
    source: "Final cable selection and installation method must follow the cable/equipment data and electrical rules for the Site."
  },
  {
    group: "DC wiring and connections",
    id: "conduit-containment-types",
    title: "Conduit, trunking and cable protection: what each is for",
    image: "/schematic-components/pv-cable-dc.jpg",
    summary: "Choose containment for sunlight, water, impact, heat, movement and access—not by colour or whatever tube is nearby.",
    keywords: ["conduit type", "PVC conduit", "flex conduit", "metal conduit", "trunking", "cable tray", "wire loom", "duct", "cable protection"],
    whatItIs: "Containment is the conduit, duct, trunking, tray, sleeve or guarded route around a cable. It may provide mechanical, UV, weather, segregation or fire protection, but one product rarely provides every function.",
    whatItDoes: "It keeps cable supported and protected while allowing suitable bends, drainage, inspection and replacement.",
    buy: ["Rigid UV/weather-rated conduit for exposed fixed runs where appropriate", "Flexible conduit only where movement or equipment entry requires it and its rating permits", "Metallic containment where the design needs higher mechanical/fire protection, with required bonding", "Fittings, swept bends, couplers, glands, supports, bushes and drain/breather parts from a compatible system", "Cable tray or trunking sized and rated for the location when multiple supported cables need an accessible path"],
    tools: ["Conduit cutter/saw and deburring tool", "Approved bender or swept fittings", "Draw wire/pull tape and suitable pulling method", "Spacing/layout tools and correct fixing hardware"],
    before: ["Read the cable's own UV, wet-location and mechanical ratings", "Check conduit fill, bend radius, pulling distance and conductor derating", "Plan drainage so outdoor conduit cannot become a water trap", "Check whether metallic containment must be bonded/earthed"],
    steps: ["Divide the cable route into environmental sections", "Choose containment whose listed purpose covers each section", "Size it for cable fill, heat and a practical pull", "Use swept changes and add accessible draw points rather than forcing tight bends", "Deburr every cut and fit bushes/glands before cable enters", "Support containment at the product/local-rule intervals and near fittings", "Seal building entries as required without trapping water inside outdoor runs", "Label the contained circuit at both ends and access points"],
    checks: ["No sharp edge or crushed/tight bend", "Outdoor sections resist UV and water and can drain as designed", "Fill/grouping/temperature were included in cable sizing", "Fittings and glue/seals belong to the selected containment system", "Metallic parts are bonded where the design requires"],
    source: "Use the selected containment manufacturer's application tables and the Site's local wiring, fire and building requirements."
  },
  {
    group: "DC wiring and connections",
    id: "cable-separation-data",
    title: "Separate DC, AC, earth and data cables",
    image: "/schematic-components/wifi-communication-module.jpg",
    summary: "Keep different circuit types identified and separated as the design requires so faults, noise and maintenance do not become tangled together.",
    keywords: ["cable separation", "segregation", "data cable", "RS485", "CAN bus", "ethernet", "communication cable", "AC DC same conduit"],
    whatItIs: "Segregation is the planned spacing, barrier or separate containment between circuits with different voltages, insulation systems, purposes or interference risks.",
    whatItDoes: "It controls fault transfer and electrical noise, preserves insulation requirements and makes cables traceable during service.",
    buy: ["Separate or divided containment where required", "Communication cable specified by the equipment maker", "Correct shields, drain-wire termination and communication terminators", "Distinct durable circuit labels"],
    tools: ["Cable-route plan", "Equipment communications manual", "Label printer/markers", "Continuity/network test method appropriate to the cable"],
    before: ["Identify PV DC, battery DC, mains/backup AC, protective earth, control and communication circuits", "Check which data buses require twisted pair, shielding, termination or maximum length", "Check the local separation/barrier rules"],
    steps: ["Assign each circuit to a route or divided compartment", "Cross noisy power and data routes only in the permitted way when unavoidable", "Keep communication cable away from hot power equipment and sharp metal", "Terminate shields and bus terminators exactly as the equipment manual states", "Label both ends before concealment", "Test communications before closing walls, trenches or equipment covers"],
    checks: ["Power and data do not share an unapproved space", "Shield and drain wires are not improvised earth conductors", "Bus topology, length and terminators match the manufacturer design", "Every cable can be identified at both ends"],
    source: "Separation and communication topology come from local wiring rules and the exact inverter, battery/BMS, meter and gateway manuals."
  },
  {
    group: "DC wiring and connections",
    id: "underground-cable-runs",
    title: "Underground cable routes and trenches",
    image: "/schematic-components/pv-cable-dc.jpg",
    summary: "Treat a buried run as a designed underground service with location checks, suitable cable/duct, drainage, depth, warning and future identification.",
    keywords: ["trench", "buried cable", "underground conduit", "solar shed cable", "direct burial", "duct", "warning tape"],
    whatItIs: "An underground run carries power or data between arrays, buildings or equipment through direct-burial cable or a suitable duct system.",
    whatItDoes: "It protects services from weather and surface damage while controlling excavation risk, water, pulling forces and heat dissipation.",
    buy: ["Cable and/or duct specifically approved for the wet underground environment and circuit", "Swept bends, draw pits/boxes and glands suited to the run", "Required bedding, mechanical protection, marker/warning system and route markers", "Separate communications duct where required"],
    tools: ["Current underground-services locate information", "Route/depth survey tools", "Duct draw rope and cable-pulling equipment", "Camera and as-built measurement record"],
    before: ["Locate existing electricity, gas, water, drainage and communications services", "Obtain permissions and confirm local depth/separation requirements", "Calculate cable rating/voltage drop for the burial and grouping method", "Plan where water will go"],
    steps: ["Set out the approved route and exclusion area", "Excavate using the required safe method around known services", "Prepare bedding/duct gradient and wide swept bends", "Install duct and draw system without low points that defeat the drainage design", "Pull cable within its tension and bend limits", "Test and photograph before covering", "Install specified mechanical/warning layers", "Measure the final route from permanent reference points and update the Site record"],
    checks: ["Existing services were located and protected", "Cable/duct and joints are rated for underground wet conditions", "Depth, separation, warning and mechanical protection meet local requirements", "Both ends are sealed, supported and labelled", "The owner has an accurate buried-route record"],
    source: "Underground depth, separation and prescribed-work rules vary globally; use the local utility/building/electrical requirements and the selected cable/duct data."
  },
  {
    group: "Monitoring and communications",
    id: "system-monitoring",
    title: "Inverter, battery and energy monitoring",
    image: "/schematic-components/monitoring-device-data-logger.jpg",
    summary: "Choose what must be measured, then place meters, CT clamps, shunts and gateways where their data means what the label says.",
    keywords: ["app", "wifi dongle", "data logger", "energy meter", "CT clamp", "remote monitoring", "internet"],
    whatItIs: "A monitoring system combines device data, battery current, AC energy meters or CT clamps, communications and a local/cloud display.",
    whatItDoes: "It shows solar production, battery state, building use, grid/generator flow and faults so problems can be understood early.",
    buy: ["Gateway/logger compatible with installed equipment", "Correct CT/energy meter and shunt where required", "Communication cable, terminators and network connection", "Local display or remote-access plan"],
    tools: ["System flow diagram", "CT orientation labels", "Network setup device", "Commissioning account and privacy choices"],
    before: ["Define each value the user needs to see", "Check meter/CT phase count, rating and direction", "Plan local operation when internet/cloud is unavailable"],
    steps: ["Place each sensor on the schematic", "Install CTs/meters in the designed direction and phase", "Connect equipment communication buses with correct termination", "Configure Site, timezone, tariff and battery data", "Compare app values with local device readings", "Set useful alarms and user access", "Save a plain-language map of what each number represents"],
    checks: ["Import/export signs are correct", "Battery monitor sees all charge and loads", "Every device reports under the correct Site", "The owner can access data without installer-only credentials"],
    source: "Use the selected meter, CT, shunt, gateway and equipment communication manuals."
  },
  {
    group: "Tools and workmanship",
    id: "torque-tools",
    title: "Use a torque wrench instead of guessing",
    image: "/schematic-components/roof-mounting-system.jpg",
    summary: "Every clamp, terminal and busbar has a stated tightening value and sometimes a stated sequence.",
    keywords: ["tighten bolt", "torque setting", "Nm", "inch pounds", "click wrench", "terminal torque"],
    whatItIs: "A torque wrench or torque screwdriver applies a measured turning force to a fastener.",
    whatItDoes: "It reduces loose hot joints and damaged threads, clamps, terminals, seals and equipment studs.",
    buy: ["Torque tool whose working range covers the required values", "Correct sockets/bits and extensions permitted by the tool", "Calibration/check service appropriate to use"],
    tools: ["Current product torque table", "Paint marker or digital record", "Backup wrench where a terminal must not rotate"],
    before: ["Read whether the value is dry, lubricated or product-specific", "Confirm units: N·m is not lb-ft or in-lb", "Inspect threads and replace damaged hardware"],
    steps: ["Select a tool that measures the value near the middle of its range", "Set the correct unit and value", "Seat parts by hand without cross-threading", "Hold any opposing terminal as the manual requires", "Pull smoothly until the tool indicates the setting", "Do not click repeatedly", "Mark and record the completed value, then return the tool to its storage setting"],
    checks: ["Correct fastener and stated torque used", "Terminal or clamp did not rotate/damage", "Tool remains in calibration", "Every concealed connection has a record"],
    source: "The exact equipment or mounting manual controls torque, sequence, lubricant and recheck requirements."
  },
  {
    group: "Testing and commissioning",
    id: "labels-photos-records",
    title: "Labels, photos and the as-built record",
    image: "/schematic-components/ac-distribution-board.jpg",
    summary: "Record each hidden fixing, cable end, setting and test result so the finished system can be understood and maintained.",
    keywords: ["documentation", "photos", "labels", "serial number", "as built", "wiring diagram", "commission sheet"],
    whatItIs: "A traceable pack containing the final schematic, component models/serials, cable routes, protection, torque, settings, photos, tests and certificates.",
    whatItDoes: "It turns a collection of equipment into a maintainable system and shows where the installed build differs from the proposal.",
    buy: ["Durable labels suitable for the environment", "Cable/terminal markers", "Document storage accessible to the owner"],
    tools: ["Camera with a consistent naming method", "Schematic and circuit schedule", "Torque/test record forms"],
    before: ["Agree naming for arrays, strings, batteries, devices and circuits", "Keep proposed and installed records visibly separate"],
    steps: ["Photograph labels and serials before installation", "Photograph roof/structural fixings before modules cover them", "Label both ends of every cable", "Record torque and test results against the same identifier", "Update the schematic for every approved change", "Save firmware/settings and shutdown instructions", "Give the owner the final pack and access credentials"],
    checks: ["Every installed item appears on the as-built", "Photos can be matched to physical locations", "Proposal values are not presented as installed facts", "Owner holds certificates and recovery/access details"],
    source: "Documentation requirements vary locally; also retain every selected manufacturer commissioning record."
  }
] as const;
