// Low-voltage DC guides use the original product photographs supplied by the user.
export const lowVoltageDcHowToGuides = [
  {
    group: "12/24 V boats, vehicles and small systems",
    id: "battery-master-isolator",
    title: "Battery master switch / manual battery isolator",
    image: "/guides/low-voltage-dc/removable-key-isolator.png",
    summary: "Use a rated manual switch to disconnect a battery circuit; the switch does not replace circuit protection.",
    keywords: ["battery shut off", "battery cutoff", "master switch", "isolator", "kill switch", "removable key"],
    whatItIs: "A manually operated high-current battery switch commonly used in boats, vehicles, caravans and compact 12 or 24 V systems.",
    whatItDoes: "It provides a deliberate OFF position for a selected battery circuit. Solar, charging or intentionally unswitched circuits may remain live.",
    questions: [
      { question: "Does this protect the cable?", answer: "No. Provide correctly selected overcurrent protection wherever the circuit design requires it." },
      { question: "Does OFF make the whole system dead?", answer: "Not necessarily. Trace solar, alternator, charger and unswitched circuits on the actual schematic." },
    ],
    before: ["Confirm system voltage and maximum continuous and surge current", "Trace every source and load on the Site schematic", "Check terminal guarding and environmental suitability"],
    steps: ["Select the switch from the actual circuit ratings", "Mount it where it is accessible and protected", "Use specified lugs, terminal covers and torque", "Label what it isolates", "Test and record which circuits remain live"],
    checks: ["Switch rating suits the circuit", "Terminals are guarded", "Required fuses or breakers remain present", "The label matches actual isolation"],
    source: "Use the exact switch instructions, accepted schematic and rules applicable at the system location.",
  },
  {
    group: "12/24 V boats, vehicles and small systems",
    id: "battery-selector-switch",
    title: "1–2–BOTH–OFF battery selector switch",
    image: "/guides/low-voltage-dc/battery-selector-switch.png",
    summary: "Select battery bank 1, bank 2, both compatible banks or neither without guessing what BOTH means.",
    keywords: ["battery selector", "1 2 both off", "boat battery switch", "dual battery switch"],
    whatItIs: "A rotary high-current switch connecting a common circuit to battery bank 1, bank 2, both banks or OFF.",
    whatItDoes: "It manually selects which battery bank supplies or receives power according to the actual wiring arrangement.",
    types: [
      { name: "Selector switch", image: "/guides/low-voltage-dc/battery-selector-switch.png", description: "The front control shows the selectable operating positions.", bestFor: "Compatible dual-bank systems with a documented operating method.", watchFor: "BOTH directly parallels the banks and must not join incompatible batteries." },
      { name: "Rear terminals and dimensions", image: "/guides/low-voltage-dc/battery-selector-switch-reference.png", description: "The supplied reference view shows the rear studs and physical size.", bestFor: "Planning terminal access and enclosure space.", watchFor: "The photograph does not prove electrical ratings; verify the exact label and manual." },
    ],
    questions: [
      { question: "Can I leave it on BOTH?", answer: "Only when both batteries and the charging arrangement are explicitly compatible." },
      { question: "Can I turn through OFF while charging?", answer: "Only if the exact switch and alternator or charger instructions permit it." },
    ],
    before: ["Identify both battery chemistries, voltages and protection", "Confirm the switch transition behaviour", "Draw every switch terminal and connection"],
    steps: ["Choose a switch rated for the actual DC circuit", "Mount it with guarded, serviceable rear terminals", "Connect only to the accepted schematic", "Label banks 1 and 2 by purpose", "Test every position"],
    checks: ["Every position matches its label", "Incompatible banks cannot be paralleled", "Cables are protected as designed", "Operating instructions are visible"],
    source: "Use the exact switch, battery and charging-equipment manuals plus rules applicable at the system location.",
  },
  {
    group: "12/24 V boats, vehicles and small systems",
    id: "automatic-battery-isolator",
    title: "VSR / ACR automatic battery isolator",
    image: "/guides/low-voltage-dc/automatic-battery-isolator.png",
    summary: "Automatically combine compatible banks while charging and separate them when voltage falls.",
    keywords: ["VSR", "ACR", "smart battery isolator", "dual battery relay", "automatic isolator"],
    whatItIs: "A voltage-sensitive or automatic charging relay used in many marine and vehicle dual-battery systems.",
    whatItDoes: "It connects or separates compatible banks at specified voltage thresholds; it is not a complete battery charger.",
    questions: [
      { question: "Is it suitable for a smart alternator or lithium battery?", answer: "Not automatically. Confirm alternator behaviour, battery chemistry and relay thresholds; a DC-DC charger may be required." },
      { question: "Does it replace fuses?", answer: "No. Provide the source protection required by the circuit design." },
    ],
    before: ["Confirm battery chemistries and permitted charge profiles", "Check current ratings", "Check thresholds and smart-alternator compatibility"],
    steps: ["Verify compatibility", "Place protection as designed", "Mount and wire to the exact diagram", "Protect and label conductors", "Test combine and separate behaviour"],
    checks: ["Threshold behaviour is correct", "No cable is unprotected", "Charging voltage suits both banks", "The as-built schematic records the relay"],
    source: "Use the exact relay, alternator and battery manuals; requirements follow the system location and use.",
  },
  {
    group: "12/24 V boats, vehicles and small systems",
    id: "dc-switch-distribution-panel",
    title: "12/24 V DC switch and distribution panel",
    image: "/guides/low-voltage-dc/dc-switch-panel.png",
    summary: "Distribute small DC loads through labelled switches and suitable branch protection.",
    keywords: ["DC panel", "boat switch panel", "12v switches", "24v distribution", "USB panel", "voltmeter"],
    whatItIs: "A grouped panel of switches and, depending on the product, fuses, breakers, indicators, a voltmeter or accessory sockets.",
    whatItDoes: "It gives small DC loads a labelled control point, but appearance does not prove branch or feeder protection is included.",
    questions: [
      { question: "Are the switches also circuit breakers?", answer: "Only if the exact documentation says so. Many panels need separate fuses or breakers." },
      { question: "Can a 12 V panel be used at 24 V?", answer: "Only when every switch, lamp, meter, USB converter, socket and protective device is rated for 24 V." },
    ],
    before: ["List each load, current and cable route", "Confirm whether protection is built in", "Check every accessory voltage rating", "Size the feeder and branches"],
    steps: ["Create a labelled circuit schedule", "Install designed feeder and branch protection", "Mount the panel suitably", "Terminate and support conductors", "Test every switch and accessory"],
    checks: ["Every label matches its load", "Protection is present", "No 12 V-only accessory is exposed to 24 V", "Voltage drop and polarity are verified"],
    source: "Use the exact panel documentation, accepted schematic and rules applicable at the system location.",
  },
] as const;
