// Further component and workmanship records for the universal How-to library.

export const componentHowToGuides = [
  {
    group: "Roofing and roof structure",
    id: "roof-asphalt-shingle",
    title: "Asphalt or composition shingle roof",
    image: "/guides/mounting/asphalt-composition-shingle-types.png",
    summary: "Use a listed flashed attachment fixed into confirmed framing without relying on shingles or decking alone.",
    keywords: ["asphalt roof", "shingle roof", "composition roof", "flashed foot", "rafter mount"],
    whatItIs: "A layered roof of shingles over underlay and deck, normally attached to rafters or trusses below.",
    whatItDoes: "The shingle sheds water; the selected flashing integrates the solar attachment into that water-shedding layer.",
    usedFor: ["Three-tab asphalt shingles", "Architectural or laminated composition shingles", "Patterned asphalt shingles", "Residential pitched roofs with a compatible flashed solar attachment"],
    types: [
      { name: "Three-tab shingle", image: "/guides/mounting/asphalt-composition-shingle-types.png", description: "A comparatively flat strip with repeated rectangular tabs and regular slots.", bestFor: "Identification only; the roof condition, deck, underlay and framing still decide whether solar can be attached.", watchFor: "Brittleness, lifted tabs, exposed fasteners, multiple roof layers and limited room to slide flashing." },
      { name: "Architectural or laminated shingle", image: "/guides/mounting/asphalt-composition-shingle-types.png", description: "A thicker layered composition shingle with a varied shadow line and less uniform tab pattern.", bestFor: "Compatible flashed attachments that can sit without distorting the thicker shingle build-up.", watchFor: "Do not force or notch layers unless the exact roof/attachment instructions permit it." },
      { name: "Patterned or designer asphalt shingle", image: "/guides/mounting/asphalt-composition-shingle-types.png", description: "A composition product formed to imitate slate, shake or another pattern.", bestFor: "Only after the exact product and approved flashing method are identified.", watchFor: "Appearance can be confused with real slate, fibre cement or another brittle covering; confirm material before lifting or drilling." }
    ],
    questions: [
      { question: "Are all the patterns in the picture installed the same way?", answer: "No. The picture helps identify common appearances only. Thickness, number of layers, underlay, deck, framing, age and the selected attachment manual control the actual method." },
      { question: "Does the solar fixing screw into the shingle?", answer: "The shingle is the weather covering, not normally the structural anchor. The selected structural fastener must reach confirmed framing or another expressly engineered substrate through a flashed attachment." },
      { question: "Can sealant replace the metal flashing?", answer: "Not by default. Use the tested attachment's complete flashing and water-shedding method. Sealant is used only where that system specifies it." },
      { question: "What if the shingles crack or will not lift?", answer: "Stop. Brittle, bonded, curled or damaged shingles may need roofing work, a different attachment method or replacement before solar mounting continues." }
    ],
    buy: ["Attachment/flashing listed for the exact roof and mounting family", "Structural fastener specified for confirmed framing", "Compatible sealant only where the flashing manual requires it", "Rails/clamps/bonding parts from the engineered system"],
    tools: ["Rafter-location and inspection method", "Shingle/flashing tools", "Correct pilot/driver and torque tools", "Roof access/fall controls"],
    before: ["Record shingle layers, age, condition and warranty", "Confirm rafter position and deck condition", "Stop for brittle, curled, leaking or structurally uncertain roofs"],
    steps: ["Set out engineered attachment positions over confirmed framing", "Lift/separate shingles using the product method", "Prepare the fixing point without damaging surrounding underlay", "Fix the attachment into framing to the specified embedment", "Lap flashing beneath upper courses and over lower courses as designed", "Apply only specified sealant details", "Fit rail, bonding and cable support", "Photograph each completed flashing before modules conceal it"],
    checks: ["Fastener enters confirmed framing", "Flashing laps follow water flow", "No lifted, split or unsealed shingle", "Attachment spacing and torque match engineering"],
    source: "Use the exact flashed-attachment, roof-covering and structural engineering instructions for the Site."
  },
  {
    group: "Roofing and roof structure",
    id: "roof-brittle-asbestos-stop",
    title: "Brittle, damaged or asbestos-suspect roof: stop",
    image: "/guides/mounting/failed-corrugated-roof.png",
    summary: "Do not walk, drill, cut or disturb a roof that may be brittle or contain asbestos until it is professionally identified and managed.",
    keywords: ["asbestos roof", "asbestos cement", "fibro", "fibre cement", "fiber cement", "brittle roof", "old roof", "cracked roof", "damaged roof", "stop work"],
    aliases: ["fibro roof", "asbestos-cement roof", "AC sheet", "fibre-cement sheet", "cement corrugated sheet"],
    whatItIs: "Older fibre-cement sheets, translucent panels, corroded metal, damaged tiles and some rooflights may fail under a person's weight or release hazardous fibres when disturbed.",
    whatItDoes: "A stop decision prevents an ordinary solar survey from becoming a fall, contamination or structural incident.",
    usedFor: ["Recognising roofs that need specialist assessment before solar work", "Recording visible damage without climbing onto the roof", "Preventing drilling, cutting or pressure-cleaning of suspect materials", "Deciding when the proposed array needs another location"],
    types: [
      { name: "Collapsed or badly failed corrugated roof", image: "/guides/mounting/failed-corrugated-roof.png", description: "Broken sheets, open holes, failed supports, heavy growth or widespread decay are clear stop signs.", bestFor: "Visual recognition from a safe location only.", watchFor: "Do not assume intact-looking areas can support a person; failure may extend beyond the obvious damage." },
      { name: "Asbestos-suspect corrugated fibre-cement sheet", image: "/guides/mounting/asbestos-suspect-fibre-cement-sheet.png", description: "Older profiled cement sheet may contain asbestos, but appearance or a photograph cannot confirm whether it does.", bestFor: "Flagging an unknown sheet for competent identification before it is touched or disturbed.", watchFor: "Do not lift, break, drill, cut, scrape, sand, pressure-wash or collect a sample outside the applicable local process." },
      { name: "Severely deteriorated roof covering and structure", image: "/guides/mounting/severely-deteriorated-roof.png", description: "Missing pieces, exposed battens, rot, sagging edges and extensive surface breakdown mean the roof is not ready for a solar installation.", bestFor: "Showing why roof repair or replacement must come before array mounting.", watchFor: "The covering, deck, battens and framing can present separate hazards and may all require assessment." }
    ],
    questions: [
      { question: "Can Wattson identify asbestos from a photo?", answer: "No. A photo can flag a material as asbestos-suspect, but identification must follow the competent testing or records process required where the Site is located." },
      { question: "Can I walk only on the screws, purlins or apparently solid parts?", answer: "Do not use that as a safety method. A brittle covering or weakened support can fail without warning, and the safe-access method must be established by a competent person." },
      { question: "Can I drill one small pilot hole to see what it is?", answer: "No. Drilling is disturbance and may release hazardous fibres or further weaken the roof. Stop and use the local identification process." },
      { question: "Does moss or staining prove asbestos?", answer: "No. Age, shape, colour, moss and texture are clues only. They do not prove the material contains—or does not contain—asbestos." },
      { question: "What happens to the solar plan?", answer: "Keep the Site discovery, but mark this roof unavailable until the hazard and structure are resolved. Wattson can compare another roof face, a shed, carport or ground-mounted option." }
    ],
    before: ["Treat unknown older fibre-cement products as suspect", "Keep people away from the roof surface and area below", "Do not climb onto it merely to obtain a closer photograph", "Do not take a sample unless the local authorised process permits it", "Check available building records, product markings and roof history without disturbing the material"],
    steps: ["Stop roof access and any drilling/cutting", "Photograph only from a safe location", "Record age, product clues and damaged areas", "Arrange competent identification and a structural/roof condition assessment", "Obtain the required remediation/removal/access plan", "Redesign for another mounting area if the roof cannot be safely used", "Resume only under the approved controls"],
    checks: ["Hazard status is recorded", "The image is labelled suspect rather than confirmed unless evidence exists", "The roof is excluded from ordinary access and mounting tasks", "No generic mounting guide overrides the stop", "Required specialist documents are attached to the Site"],
    source: "Work-at-height and asbestos controls are location-specific; use the local workplace/building authority before disturbing suspect material."
  },
  {
    group: "DC wiring and connections",
    id: "pv-series-versus-parallel",
    title: "Series versus parallel solar-panel connections",
    image: "/guides/panels/series-vs-parallel.svg",
    summary: "Series adds panel voltage; parallel adds string current. The proposed schematic must show both counts and the exact inverter or controller input they feed.",
    keywords: ["series panels", "parallel panels", "series vs parallel", "panels per string", "number of strings", "string voltage", "array current", "combiner", "branch connectors", "MPPT input"],
    aliases: ["string layout", "series-parallel array", "PV string configuration", "panel wiring arrangement"],
    whatItIs: "A series string connects panels end-to-end so their voltages add. Parallel wiring joins two or more complete, compatible strings or sources so their currents add at approximately the same voltage.",
    whatItDoes: "The chosen series and parallel counts turn individual panel ratings into the voltage and current presented to an MPPT, charge controller or inverter input.",
    usedFor: ["Choosing panels per PV string", "Splitting an array across inverter MPPT inputs", "Combining equal strings", "Checking controller/inverter voltage and current limits", "Determining when string fuses or a combiner may be required", "Making the proposed and as-built schematics unambiguous"],
    types: [
      { name: "Panels connected in series", image: "/guides/panels/series-vs-parallel.svg", description: "The positive lead of one panel connects to the negative lead of the next, creating one string with two free ends.", bestFor: "Building the DC voltage needed to operate inside the selected inverter or controller's MPPT window.", watchFor: "Add voltage across every panel and temperature condition. String current remains governed by the connected panels; shade or mismatch can change the operating point." },
      { name: "Equal strings connected in parallel", image: "/schematic-components/dc-combiner-box.jpg", description: "The positive outputs of compatible strings join together and their negative outputs join together through the designed branch, input or combiner arrangement.", bestFor: "Increasing array current or feeding supported parallel strings into an input after each individual string is valid.", watchFor: "Currents add. Check MPPT operating-current and Isc limits, conductor ratings, connector/combiner ratings, reverse-current paths and required string protection." },
      { name: "Series-parallel array", image: "/guides/panels/series-vs-parallel.svg", description: "Panels first form equal series strings, then two or more compatible strings are combined in parallel or assigned to suitable MPPT inputs.", bestFor: "Larger arrays that need both higher voltage and more total current/power.", watchFor: "Keep each parallel string electrically compatible and clearly labelled. Do not hide unequal panel counts, mixed orientations or different module ratings behind one combined total." }
    ],
    questions: [
      { question: "What adds in series?", answer: "Panel voltage adds. For a first-pass illustration, a string of equal panels has approximately the sum of their Vmp values while operating and the sum of their Voc values when open circuit. The string current is approximately the panel/string current, not the sum of every panel's current." },
      { question: "What adds in parallel?", answer: "Current adds across compatible parallel strings while their voltage remains approximately the string voltage. Both operating current and short-circuit-current limits must be checked at the destination input." },
      { question: "Can I just connect as many panels in series as possible?", answer: "No. Cold-weather string Voc must remain below every applicable absolute voltage limit, while hot-weather operating voltage must remain high enough for the MPPT to work. Maximum and minimum string lengths come from the exact panel, temperature and inverter/controller data." },
      { question: "Can strings with different panel counts be paralleled?", answer: "Not as a casual arrangement. Parallel sources must operate at compatible voltages, and unequal strings can behave poorly or create unsafe current paths. Use only an architecture explicitly checked for the exact equipment." },
      { question: "Do parallel strings need fuses?", answer: "Sometimes. It depends on the number of current sources, possible reverse current, module maximum series-fuse rating, conductor ratings, equipment instructions and local requirements. A combiner box does not automatically mean every chosen fuse value is correct." },
      { question: "Can I use Y or branch connectors instead of a combiner box?", answer: "Only when the approved connector arrangement, source count, current, voltage, environmental rating, protection and destination input all permit it. A branch connector is not a substitute for required fusing, isolation, surge protection or accessible grouping." },
      { question: "Is battery series and parallel wiring the same?", answer: "The basic voltage/current arithmetic is related, but batteries add major restrictions: chemistry, state of charge, age, BMS topology, balancing, fault current, cable symmetry and manufacturer series/parallel limits. Use the separate battery-bank guide and exact battery instructions." }
    ],
    buy: ["Nothing until the exact panel and inverter/controller inputs are identified", "Matching approved PV cable and connector family", "Rated branch connectors or combiner only where the checked design uses them", "Required string fuses, isolation, surge protection, glands and labels from the complete design", "A durable string and MPPT identification scheme"],
    tools: ["Exact panel label, datasheet and temperature coefficients", "Exact inverter/controller MPPT voltage, operating-current and Isc limits", "Site minimum and maximum design temperatures", "String-sizing worksheet or verified manufacturer design tool", "Proposed schematic showing every string and input", "Appropriate authorised PV test equipment and safe-work method"],
    before: ["Record panel Voc, Vmp, Isc, Imp and maximum series-fuse rating", "Confirm panel quantity, roof groups, direction, tilt and shade pattern", "Map the inverter/controller's independent MPPTs and input relationships", "Calculate cold maximum Voc and hot minimum operating voltage", "Calculate current and Isc for every parallel group", "Determine protection, isolation and combiner requirements", "Do not assemble or disconnect illuminated PV circuits outside the applicable safe-work process"],
    steps: ["Group compatible panels by model, direction, tilt and shade", "Choose a candidate number of panels in each series string", "Prove each string remains inside the destination voltage window across Site temperatures", "Choose how many equal strings feed each MPPT or combiner", "Prove operating current and Isc remain inside every input and component limit", "Add any required string protection, isolation, surge protection and cable sizing", "Draw every string separately and label its panel count, polarity and MPPT destination", "Build and test one identified string at a time under the required safe-work process", "Record measured polarity and voltage before combining", "Save the final arrangement and test results on the as-built schematic"],
    checks: ["Panels per series string are shown", "Number of parallel strings is shown", "Every string has a named MPPT or controller destination", "Cold voltage, hot operating voltage, current and Isc limits pass", "Parallel strings are compatible and individually identifiable", "Protection and conductor ratings cover all current paths", "Proposed values remain marked proposed until the real panels, wiring and tests are confirmed"],
    source: "Use the exact module, inverter/controller, connector, combiner and protection manuals together with Site temperature data and applicable local PV wiring requirements."
  },
  {
    group: "Solar panels and module types",
    id: "read-module-label",
    title: "Read a solar-panel label and datasheet",
    image: "/guides/panels/solar-module-rating-label.png",
    summary: "Capture the numbers Wattson needs: Voc, Vmp, Isc, Imp, power, fuse limit, system voltage, dimensions and clamp zones.",
    keywords: ["panel sticker", "solar label", "nameplate", "Pmax", "Voc", "Vmp", "Isc", "Imp", "panel watts", "datasheet", "maximum series fuse", "temperature coefficient", "clamp zone"],
    aliases: ["module nameplate", "rating label", "specification sticker", "panel data plate"],
    whatItIs: "The rear label identifies the module model and electrical ratings at stated test conditions; the datasheet/manual adds temperature coefficients and mechanical limits.",
    whatItDoes: "These values determine string voltage/current, inverter compatibility, conductor/protection design and mounting method.",
    usedFor: ["Identifying an existing panel", "Checking string length and inverter compatibility", "Sizing conductors and protection", "Finding the exact datasheet and installation manual", "Recording a panel in Site Inventory"],
    types: [
      { name: "Module rating label or nameplate", image: "/guides/panels/solar-module-rating-label.png", description: "The permanent rear label normally shows the exact model and core electrical ratings measured under stated test conditions.", bestFor: "Identifying the physical panel and capturing its Voc, Vmp, Isc, Imp, Pmax and other printed limits.", watchFor: "This picture is an example only. Never copy its sample values into another panel record; photograph and read that panel's own label." },
      { name: "Product datasheet", image: "/guides/panels/solar-module-rating-label.png", description: "The maker's document expands the label into temperature coefficients, tolerances, dimensions, weight, construction, connector and rating details.", bestFor: "Electrical design, equipment matching and confirming differences between similar model suffixes.", watchFor: "Use the current document for the exact manufacturer, model and regional version—not a visually similar panel or marketplace listing." },
      { name: "Installation manual", image: "/guides/panels/module-installation-manual.svg", description: "The maker's instructions state handling, mounting orientation, approved clamp or bolt zones, loading, bonding, wiring and service restrictions.", bestFor: "Designing how the identified module can actually be mounted and connected.", watchFor: "The datasheet's dimensions are not a mounting method. Clamp zones and permitted loads may be in a separate manual or certificate." }
    ],
    questions: [
      { question: "What is Pmax?", answer: "Rated maximum power in watts at the label's stated test conditions. It is a comparison/design rating, not a promise that the panel will continuously produce that number outdoors." },
      { question: "What are Vmp and Imp?", answer: "Voltage and current at the panel's maximum-power operating point under the stated test conditions. Their product is approximately the rated power and they help define normal MPPT operation." },
      { question: "What are Voc and Isc?", answer: "Voc is open-circuit voltage when the panel is illuminated but not supplying a load. Isc is short-circuit current under stated conditions. They are limit-check inputs—not the same as ordinary operating voltage and current—and design factors and temperature conditions still apply." },
      { question: "What does maximum system voltage mean?", answer: "It is an upper insulation/system rating for the module, not the voltage Wattson should automatically design the array to reach. The inverter, connectors, cable, protection and local rules can impose lower limits." },
      { question: "What does maximum series-fuse rating mean?", answer: "It is the largest series protective-device rating the module permits under its certification; it is not an instruction to install that fuse size. Required string protection and its rating come from the complete parallel-source and conductor design." },
      { question: "Why does Wattson need temperature coefficients?", answer: "Panel voltage changes with cell temperature. The cold-condition Voc check protects against excessive input voltage, while hot-condition operating voltage helps prove the string can remain inside the MPPT range." },
      { question: "What if the label is faded or missing?", answer: "Do not guess from panel size or cell appearance. Record clear photos of the panel, junction box, connectors, serial marks and any model clues, then seek manufacturer or supplier evidence. Keep all unproven values marked unknown." }
    ],
    tools: ["Clear camera/label scanner", "Current manufacturer datasheet and installation manual", "Cold-temperature and current worksheet"],
    before: ["Do not infer ratings from panel size or appearance", "Keep the complete model suffix and connector type—small suffix changes can matter", "Treat every displayed example as education rather than data for the user's equipment", "Clean or photograph the label only by a method that does not create unsafe roof or electrical access"],
    steps: ["Photograph the entire label square-on in focus", "Take a second close image if small print is not readable", "Record manufacturer, complete model and serial number", "Record Pmax, Voc, Vmp, Isc and Imp with their units", "Record maximum system voltage and maximum series-fuse rating without treating them as chosen design values", "Find the matching manufacturer datasheet and installation manual", "Record voltage/current temperature coefficients and tolerances", "Record dimensions, weight, frame thickness, permitted mounting orientation and clamp/bolt zones", "Record factory connector manufacturer/family and lead information", "Attach the label photo and exact documents to the Site component record"],
    checks: ["Every value is tied to the exact manufacturer and model suffix", "No number was copied from the educational example image", "Voc is not confused with Vmp and Isc is not confused with Imp", "Units and decimal points have been checked against the photo", "Temperature and mechanical data are present before design", "Unknown or unreadable values remain explicitly unverified"],
    source: "Use the exact module label, current datasheet and installation manual."
  },
  {
    group: "Solar panels and module types",
    id: "shade-bypass-strings",
    title: "Shade, bypass diodes and string grouping",
    image: "/guides/panels/string-inverter-layout.png",
    summary: "See how strings, bypass diodes, separate MPPTs, DC optimisers and microinverters respond differently to shade and mixed roof faces.",
    keywords: ["tree shade", "chimney shade", "panel shadow", "bypass diode", "substring", "string inverter", "power optimiser", "optimizer", "microinverter", "panel level electronics", "MLPE", "multiple roof faces", "MPPT", "mismatch"],
    aliases: ["shade management", "module-level power electronics", "MLPE", "panel-level optimisation", "module mismatch"],
    whatItIs: "A solar array can connect panels in a conventional DC string, add compatible DC optimisers at the panels, or convert each panel's power to AC with microinverters. Bypass diodes are a different feature built into most modules: they can let current pass around a shaded or damaged section of cells when their operating threshold is reached.",
    whatItDoes: "Good grouping keeps panels with similar direction, tilt and shade on a suitable MPPT. Panel-level electronics may reduce some mismatch and add monitoring or shutdown functions, but they cannot recover sunlight that never reaches the panel.",
    usedFor: ["Comparing ordinary string, optimiser and microinverter layouts", "Planning arrays with chimneys, trees, vents or several roof faces", "Keeping different directions and shade patterns on suitable MPPTs", "Understanding why bypass diodes do not make a shaded panel produce normally", "Checking module-level equipment compatibility before purchase"],
    types: [
      { name: "Conventional DC string and string inverter", image: "/guides/panels/string-inverter-layout.png", description: "Panels connect in series to form a higher-voltage DC string, which feeds a central string or hybrid inverter.", bestFor: "Simple, similarly oriented arrays with appropriate string lengths and limited shade, or designs that can separate roof groups across inverter MPPT inputs.", watchFor: "One string's operating point is shared. Check cold Voc, hot operating voltage, current, string length, parallel inputs and whether unlike directions are being mixed on one tracker." },
      { name: "DC power optimiser", image: "/guides/panels/dc-power-optimiser.png", description: "A compatible electronic unit sits behind a panel or small panel group and conditions its DC output before the optimiser string reaches a supported central inverter.", bestFor: "Product-specific panel monitoring, mismatch control or shutdown functions where the complete module–optimiser–inverter combination is approved.", watchFor: "An optimiser is not universal. Module current, Isc, voltage and power; optimiser output; inverter input limits; string counts; connectors and firmware must all be compatible." },
      { name: "Microinverter", image: "/guides/panels/rooftop-microinverter.png", description: "A small inverter beneath a panel or panel group converts that local DC power into AC and joins an approved AC branch/trunk system.", bestFor: "Some multi-direction, partly shaded or module-level monitoring layouts where the chosen unit and local AC arrangement are suitable.", watchFor: "It moves active electronics and AC connections onto the roof. Check module input limits, units per branch, trunk components, protection, communications, access and local electrical requirements." },
      { name: "Module bypass diodes", image: "/guides/panels/module-bypass-diodes.svg", description: "Diodes inside a panel's junction box divide its cells into sections and may carry current around a section that is sufficiently shaded or impaired.", bestFor: "Reducing severe reverse stress and allowing the remaining string current a path under the conditions designed by the module maker.", watchFor: "They are not shade optimisers. A bypassed section loses its contribution, creates a voltage step, can become warm and may indicate a layout, debris, damage or diode fault that needs investigation." }
    ],
    questions: [
      { question: "Does shade on one panel stop the entire string?", answer: "Not always, and not in one fixed way. The result depends on which cells are shaded, bypass-diode operation, irradiance, the other panels, inverter tracking and the string layout. Output can fall by more than the shaded area suggests, so model the actual time and shape of shade rather than applying a slogan." },
      { question: "Do I need optimisers or microinverters whenever there is shade?", answer: "No. First avoid shade, change panel position, split roof faces across suitable MPPTs or reduce the affected array area. Compare the measured or modelled energy benefit with cost, compatibility, rooftop complexity and future service access." },
      { question: "Is a separate MPPT enough for different roof directions?", answer: "Often it can be, if each roof group forms a valid string and the inverter has suitable independent inputs. Check the exact inverter's MPPT arrangement—two input sockets do not always mean two independent trackers." },
      { question: "Can an optimiser work with any inverter?", answer: "No. Use an explicitly supported module–optimiser–inverter combination and prove every input/output voltage, current, Isc, power and string-count limit. A connector that fits does not prove electrical or platform compatibility." },
      { question: "Can I mix microinverters with a battery inverter?", answer: "Possibly, through a specifically supported AC-coupled architecture. Backup behaviour, frequency control, charging limits, islanding, protection and communications must be designed as one system; do not assume two AC products automatically coordinate." },
      { question: "Which option is best?", answer: "There is no automatic winner. Wattson should first show the plain-string layout, shade and roof groups, then explain what an optimiser or microinverter changes, what it costs, which limits apply and what remains on the roof to maintain." }
    ],
    tools: ["Seasonal shade survey or modelling", "Roof-face direction and tilt record", "Exact module bypass-diode/cell layout", "Inverter MPPT map and electrical limits", "Current optimiser or microinverter compatibility documentation", "Module-position and serial-number map"],
    before: ["Map trees, chimneys, vents, ridges, aerials and future vegetation growth", "Check morning, midday and afternoon shade across seasons—not just at the survey time", "Group modules by direction, tilt, module type and shade pattern", "Do not promise that panel electronics erase lost sunlight", "Record where rooftop electronics can be reached after the panels are installed"],
    steps: ["Draw every roof face and obstruction, then plot the shade windows", "Create a valid conventional-string and MPPT grouping first", "Check cold maximum voltage, hot minimum operating voltage, current, Isc and parallel-string limits", "Estimate the energy affected by shade and mismatch", "Compare avoidance, separate MPPTs, optimisers and microinverters using the exact supported equipment", "Include rooftop connections, protection, shutdown behaviour, monitoring and replacement access", "Map each panel and electronic serial number where panel-level equipment is selected", "Save assumptions and the chosen architecture on the proposed schematic"],
    checks: ["Different directions or shade patterns are not casually mixed on one tracker", "Every string remains inside the inverter's operating limits in the Site conditions", "Every optimiser or microinverter remains inside both module-side and system-side limits", "Connector families and branch/string counts are approved", "Production estimates include real shade rather than an assumed marketing gain", "The schematic clearly distinguishes DC string, optimised DC and microinverter AC architectures"],
    source: "Use the exact module bypass layout, inverter MPPT rules and any optimiser/microinverter compatibility documentation."
  },
  {
    group: "Mounting systems and hardware",
    id: "carport-pergola-canopy",
    title: "Solar carport, pergola or canopy",
    image: "/guides/mounting/manufactured-metal-ground-rack.png",
    summary: "Design the supporting structure, waterproofing, vehicle/public clearance and cable protection as one building—not as panels added later.",
    keywords: ["solar carport", "solar pergola", "canopy", "patio solar", "shade structure", "waterproof panels"],
    whatItIs: "A freestanding or building-attached structure where the solar array may also provide shade or shelter.",
    whatItDoes: "It supports panels at a useful orientation while managing rain, wind, impact, access and exposed cable routes.",
    buy: ["Engineered posts, beams, bracing, foundations and module supports", "Designed drainage/gutter or weather-sealing system", "Impact/UV-protected cable pathways and guarded equipment", "Bonding/earthing and required vehicle-clearance protection"],
    before: ["Check planning/building approval, boundaries and vehicle movement", "Assess wind/snow/seismic and foundation conditions", "Decide whether it must be weatherproof or only provide shade"],
    steps: ["Set usable clearance and footprint", "Engineer foundations and frame", "Plan panel joints, drainage and gutters", "Plan protected DC/AC routes before enclosing posts/beams", "Build and inspect the structure", "Install supports, modules, bonding and cable guards", "Water-test where shelter is claimed", "Record buried foundations/services and clearances"],
    checks: ["Structure and foundations are approved", "No reachable exposed connector or cable", "Drainage does not discharge into unsafe areas", "Vehicle impact and maintenance access are addressed"],
    source: "Use local building/planning requirements and the exact structural, mounting, module and electrical designs."
  },
  {
    group: "Batteries and charging",
    id: "battery-bms",
    title: "Battery management system (BMS)",
    image: "/schematic-components/bms-battery-management-system.jpg",
    summary: "The BMS protects and reports on battery cells; inverter settings and communications must respect its limits.",
    keywords: ["BMS", "battery communication", "CAN", "battery protect", "cell voltage", "charge limit", "discharge limit"],
    whatItIs: "Electronics that measure cells and temperature, balance cells where designed, communicate limits and open or command protection under unsafe conditions.",
    whatItDoes: "It prevents operation outside the battery maker's cell, temperature, charge and discharge limits—but it does not replace all required fuses, isolation or correct inverter settings.",
    buy: ["Battery/BMS combination supported by the battery maker", "Inverter communication cable/interface and terminators", "Required contactors, pre-charge and external protection"],
    before: ["Confirm exact battery-inverter compatibility and firmware", "Identify CAN/RS485 pinout—physical plug shape is not proof", "Record maximum charge/discharge currents and temperature limits"],
    steps: ["Set battery addresses and bank topology", "Connect communication in the stated daisy-chain/star arrangement", "Fit correct terminators", "Configure inverter battery protocol", "Confirm reported voltage, current, temperature and state", "Test charge/discharge limit response", "Save firmware and configuration"],
    checks: ["No homemade communication pinout without manufacturer approval", "Inverter obeys dynamic BMS limits", "Every battery appears correctly", "Independent overcurrent protection remains present"],
    source: "Use the exact battery, BMS and inverter compatibility/communication manuals."
  },
  {
    group: "Batteries and charging",
    id: "dc-busbars-distribution",
    title: "Positive and negative DC busbars",
    aliases: ["Bus bar", "Power distribution bar", "Battery distribution bar", "Common connection bar"],
    image: "/schematic-components/busbar.jpg",
    summary: "Use a rated, covered distribution point when several cables must share the same positive or negative battery connection.",
    keywords: ["bus bar", "battery distribution", "positive bar", "negative bar", "terminal block", "too many battery lugs", "busbar size", "mount busbar", "busbar height"],
    whatItIs: "A busbar is a solid copper or plated conductive bar with several studs or terminals. Every connection on one bar is electrically the same point—so a positive bar and a negative bar must never touch or be confused.",
    whatItDoes: "It replaces an unsafe pile of cable lugs on a battery or inverter stud with an orderly, coverable distribution point. It also makes fusing, balanced battery connections, shunt measurement, labels and later servicing easier to understand.",
    usedFor: ["Battery-bank DC distribution", "Connecting several chargers or DC loads", "Parallel battery connections", "Feeding an inverter through a main protected path", "Creating one measured system-negative point after a shunt"],
    types: [
      { name: "Positive DC busbar", image: "/guides/connections/positive-dc-busbar.svg", description: "Distributes battery positive to protected outgoing circuits.", bestFor: "One covered positive point feeding inverter, chargers and DC distribution.", watchFor: "It normally sits after the designed main battery protection; each smaller outgoing cable may need its own protection." },
      { name: "Negative DC busbar", image: "/guides/connections/negative-dc-busbar.svg", description: "Collects return conductors from chargers, inverter and DC loads.", bestFor: "Keeping all system returns together and, with a battery monitor, on the system side of the shunt.", watchFor: "A return connected directly to battery negative can bypass the shunt and make state-of-charge readings wrong." },
      { name: "Combined distribution module", image: "/guides/connections/combined-dc-distribution.svg", description: "A covered assembly may contain separate positive and negative bars, fuse positions, a disconnect or a shunt.", bestFor: "Compact, documented battery systems using one compatible product family.", watchFor: "The internal ratings and diagram still control; a shared enclosure does not mean positive and negative are electrically joined." },
      { name: "AC, neutral and earth bars", image: "/schematic-components/earthing-ground-bar.jpg", description: "Switchboards also contain busbars, neutral bars and protective-earth bars designed for AC distribution.", bestFor: "Their exact approved switchboard purpose only.", watchFor: "Do not substitute an AC neutral/earth bar or generic terminal strip for a high-current battery DC busbar unless it is explicitly rated and approved for that duty." }
    ],
    questions: [
      { question: "Why would I use a busbar?", answer: "Use one when several cables need the same electrical connection and the battery/equipment terminal cannot safely or neatly accept them. It gives each cable a proper stud, makes covers and labels possible, and creates a clear place for distribution and testing." },
      { question: "Do I have to use one?", answer: "Not always. A very simple system may have one correctly fused cable connected directly between the battery and one device if both manuals permit it. Once there are several batteries, chargers, inverters or DC loads, a correctly rated busbar or purpose-built distribution module is usually the clearer solution. The approved schematic decides." },
      { question: "Does its size matter?", answer: "Yes. Check maximum system voltage, continuous current, short-duration or fault duty, conductor/stud size, allowed number of lugs, enclosure temperature and environment. The bar must carry the worst combined current without excessive heating; physical length alone is not its rating." },
      { question: "Do I need both a positive and a negative busbar?", answer: "Only if the circuit layout needs distribution on both sides. Many multi-device battery systems use both. Some use a positive fused distribution module but only a negative bar, or vice versa. They remain separate components and must never be bridged together." },
      { question: "Can I use only one side of a two-bar unit?", answer: "Possibly, if the manufacturer permits it and unused live parts are safely covered, but the unused bar must not create confusion or an accidental connection. Record it on the schematic and label it clearly." },
      { question: "Is a busbar DC or AC?", answer: "It is only suitable for the voltage, current, fault duty and application stated by its manufacturer. Battery bars must be rated for the intended DC system. Switchboard AC busbars, neutral bars and earth bars have different approved jobs and are not automatic substitutes." },
      { question: "Where should it be mounted?", answer: "Mount it on a rigid, non-conductive or purpose-designed insulated base, normally inside a suitable covered enclosure close enough to the battery/distribution equipment to keep high-current cables short. Keep it dry, ventilated as required, protected from dropped tools and metal objects, away from fuel or ignition hazards, and positioned so cable weight cannot pull sideways on studs." },
      { question: "Is there a regulated mounting height?", answer: "There is no single global busbar height. The correct height and accessibility depend on the country, installation type, enclosure, battery/equipment manual, touch-protection rules and who may access the space. Use the Site location rules. Regardless of height, live parts must be guarded, serviceable and inaccessible to children or untrained people where required." }
    ],
    buy: ["Busbar explicitly rated for the system DC voltage, combined continuous current and expected fault duty", "Enough correctly sized studs/terminals without unsupported lug stacking", "Insulated base, finger-safe cover or suitable enclosure", "Correct lugs, washers/nuts specified by the maker, boots and durable positive/negative labels"],
    tools: ["Approved DC schematic and maximum-current calculation", "Correct cable-lug crimper", "Insulated hand tools", "Calibrated torque wrench", "Drill/template for the enclosure mounting pattern"],
    before: ["Sum simultaneous continuous and surge currents through each section of bar", "Check voltage, fault rating, terminal count, stud size, lug stacking and torque limits", "Choose a dry, guarded and serviceable mounting position", "Place positive distribution relative to main and branch protection exactly as designed", "Place system negative after the battery shunt where fitted so no load or charger bypasses measurement"],
    steps: ["Draw every proposed cable on the positive and negative bars before drilling", "Choose the bar ratings and number of terminals from that drawing", "Mount each bar rigidly on its insulated base inside the selected enclosure", "Keep positive and negative separated and unmistakably labelled", "Route cables with bend radius and strain support so lugs sit flat", "Fit one lug per stud where possible or only the stack expressly permitted", "Hold the stud as required and torque the nut to the maker's value", "Fit all covers and terminal boots", "Photograph, label and update the schematic before energising"],
    checks: ["Voltage, continuous current and fault-duty ratings exceed the designed duty", "Positive and negative bars cannot touch or be mistaken for each other", "Positive live metal is fully guarded", "No load or charger bypasses the shunt", "No unsupported lug stack or cable strain", "Mounting position meets local access/touch-protection requirements", "Every terminal torque and connected circuit is recorded"],
    source: "Use the exact busbar, fuse, shunt and connected-equipment terminal manuals."
  },
  {
    group: "Protection and isolation",
    id: "dc-fuse-types",
    title: "DC fuse types and fuse holders",
    aliases: ["Battery fuse", "Solar fuse", "gPV fuse", "MEGA fuse", "ANL fuse", "Class T fuse", "MIDI fuse", "Bolt-down fuse"],
    image: "/guides/protection/gpv-cylindrical-fuse.png",
    summary: "Choose a fuse family for the circuit's job, voltage and available fault current—similar amp ratings do not make different fuse types interchangeable.",
    keywords: ["which DC fuse", "fuse size", "interrupt rating", "breaking capacity", "AIC", "battery short circuit", "PV string fuse", "fuse holder"],
    whatItIs: "A DC fuse contains a calibrated element that permanently opens when current and time exceed its designed curve. The fuse body and its matching holder form one protection system.",
    whatItDoes: "It limits damage to a cable or component when excessive current flows. It cannot make an undersized cable safe, and it does not automatically provide a suitable everyday isolation switch.",
    usedFor: ["PV string reverse-current protection", "Battery main-cable protection", "Protecting inverter and charger branches", "Small DC control and monitoring feeds"],
    types: [
      { name: "Cylindrical gPV solar fuse", image: "/guides/protection/gpv-cylindrical-fuse.png", description: "A PV-specific cartridge, commonly fitted in a touch-safe holder or combiner, designed to interrupt photovoltaic DC fault current at a stated high DC voltage.", bestFor: "PV strings or array circuits where the design requires string/array overcurrent protection.", watchFor: "Use the correct gPV class, physical size, DC voltage, current and matching holder. It is not automatically a battery fuse." },
      { name: "MEGA-style battery fuse", image: "/guides/protection/mega-battery-fuse.png", description: "A compact bolt-down high-current fuse used in many low-voltage battery and mobile power systems.", bestFor: "A specifically calculated inverter, charger or DC distribution branch within its published voltage and interrupt rating.", watchFor: "Do not substitute an ANL or MIDI fuse. Battery prospective fault current may exceed a MEGA product's interrupt capability even when its amp rating looks correct." },
      { name: "ANL-style battery fuse", image: "/guides/protection/anl-battery-fuse.png", description: "An elongated bolt-down fuse family used for high-current battery conductors with its own matching holder and ratings.", bestFor: "A battery branch whose voltage, time-current behaviour and calculated fault current pass the exact ANL product data.", watchFor: "ANL dimensions, ratings and holders differ from MEGA, MIDI and Class-T families; the name alone does not establish adequate interrupt capacity." },
      { name: "Class-T / high-interrupt battery fuse", image: "/guides/protection/class-t-battery-fuse.png", description: "A compact current-limiting fuse family available with high DC interrupt ratings for severe fault energy.", bestFor: "Battery/inverter circuits where the calculated fault current and selected product data require high interrupt capability.", watchFor: "Class name alone is insufficient: verify DC voltage, amp rating, time-current behaviour, holder and the exact manufacturer's DC interrupt rating." },
      { name: "MRBF terminal-mounted battery fuse", image: "/guides/protection/mrbf-terminal-fuse.jpg", description: "A compact high-current fuse mounted directly on a compatible battery terminal stud or purpose-built surface block.", bestFor: "Short source-side protection in 12, 24 or other DC battery systems that remain within the selected MRBF voltage/current/fault ratings.", watchFor: "Terminal fit does not prove electrical suitability. Check maximum DC voltage, interrupt rating, terminal stack, cover, torque and ignition/environment rating." },
      { name: "MIDI compact bolt-down fuse", image: "/guides/protection/midi-battery-fuse.png", description: "A smaller bolt-down fuse family used for lower-current DC branches and auxiliary distribution.", bestFor: "Control, charging or DC-load branches that fit the selected product's voltage, current and fault-duty ratings.", watchFor: "Product voltages vary. Match the actual 12, 24, 36, 48, 60 V or higher circuit maximum—never infer suitability from the MIDI shape." },
      { name: "MINI, ATO/ATC and MAXI blade fuses", image: "/guides/protection/blade-fuse-sizes.png", description: "Colour-coded plug-in fuse families widely used in automotive, marine, caravan and low-voltage solar/battery DC distribution.", bestFor: "12 or 24 V auxiliary loads—and other circuits only when the exact fuse/block ratings cover the real maximum voltage and fault current.", watchFor: "Many common blade products are rated around 32 V. A solar-equipped system may use them, but they are not automatically suitable for 36, 48, 60 V, high-voltage PV strings or high-fault battery mains." }
    ],
    questions: [
      { question: "Why do I need a fuse?", answer: "A battery or parallel solar source can push damaging current into a failed or shorted cable. A correctly placed fuse opens before the protected cable or equipment exceeds its safe damage limit." },
      { question: "Does the fuse amp rating just match the appliance?", answer: "No. Selection coordinates the cable capacity, normal and surge current, equipment maximum protection, ambient temperature and the fuse time-current curve. A motor or inverter surge may require a permitted delay without leaving the cable unprotected." },
      { question: "What is interrupt or breaking capacity?", answer: "It is the maximum prospective fault current the fuse can safely interrupt under stated voltage conditions. A large battery bank can deliver extremely high short-circuit current, so this rating is separate from the fuse's normal amp number and can control the fuse family." },
      { question: "Can I put a solar gPV fuse on a battery cable?", answer: "Do not substitute by appearance or amp rating. gPV fuses are designed for PV-source behaviour; battery circuits can have very different fault energy. Use a fuse explicitly suitable for the calculated battery DC voltage and prospective fault current." },
      { question: "Do I also need a fuse holder?", answer: "Yes, unless the fuse is installed inside a purpose-designed fused device. The holder must be approved for that exact fuse size/family, DC voltage, current, heat, terminal and enclosure conditions." },
      { question: "Where should a DC fuse be mounted?", answer: "Place it so it protects the intended conductor from the energy source—commonly close to a battery positive source or at the designed PV combining point—inside a suitable guarded enclosure with short unprotected conductor length, cable strain relief and service access. The exact distance and location come from local rules and the approved design." },
      { question: "Is there one regulated mounting height?", answer: "No single height applies globally. Local access, touch-protection, battery enclosure, switchgear and service-clearance rules decide. Mount it where it stays dry/cool within rating, cannot be reached or shorted accidentally, remains identifiable and can be safely isolated before fuse replacement." },
      { question: "Can a fuse be used as an on/off switch?", answer: "Normally the circuit should be isolated by the designed disconnect procedure before a fuse is removed. Use a fuse-switch combination only when that exact product is rated for the circuit and switching duty." }
    ],
    buy: ["Fuse class/family explicitly suitable for the circuit source", "Calculated amp rating and time-current characteristic", "DC voltage rating above the circuit maximum", "Interrupt rating above calculated prospective fault current", "Matching fuse holder, cover/enclosure and terminal hardware", "A labelled spare of the exact approved replacement type where appropriate"],
    tools: ["Approved schematic and fault-current/cable calculation", "Current fuse and holder datasheets", "Correct lug/crimp tools", "Insulated tools and calibrated torque wrench", "Safe isolation and test equipment appropriate to local rules"],
    before: ["Identify every source that can feed the fault", "Calculate maximum normal/surge current and cable capacity", "Calculate or obtain prospective fault current", "Check equipment maximum permitted protection", "Confirm enclosure temperature and grouping derating", "Plan safe replacement without touching live DC"],
    steps: ["Mark the protected conductor and source on the schematic", "Select the fuse class for PV, battery or auxiliary duty", "Coordinate amp rating and time-current curve with cable and equipment", "Verify maximum DC voltage and interrupt capacity", "Select the exact matching holder and enclosure", "Mount close to the source as the approved design/local rule requires", "Prepare and support cables so terminals carry no mechanical strain", "Fit clean lugs, tighten to the holder's stated torque and install the cover", "Label circuit, fuse family, amp/voltage rating and shutdown method", "Record the exact replacement part and completed torque"],
    checks: ["Fuse protects the intended conductor from every relevant source", "DC voltage and interrupt ratings pass", "Holder and fuse are an approved pair", "No dangerous exposed live stud or excessive unprotected cable", "Cable lugs sit flat without strain", "Replacement requires a defined safe-isolation process", "Fuse type and rating match the as-built schematic"],
    source: "Eaton gPV application data and Victron MIDI/MEGA/ANL examples illustrate distinct fuse families; use the exact chosen fuse/holder documents and Site fault calculation.",
    sourceUrl: "https://www.eaton.com/content/dam/eaton/products/electrical-circuit-protection/fuses/bussmann-iec-high-speed-semi-conductors-fuses/bussmann-iec-photovoltaic-high-speed-fuses/eaton-bussmann-series-photovoltaic-fuses-catalogue-ca135004en.pdf"
  },
  {
    group: "DC wiring and connections",
    id: "dc-voltage-classes",
    title: "12 V, 24 V, 36 V, 48 V, 60 V and higher DC systems",
    aliases: ["System voltage", "Battery voltage", "Nominal voltage", "Maximum DC voltage", "Extra-low voltage"],
    image: "/schematic-components/pv-cable-dc.jpg",
    summary: "Name the actual circuit and its maximum voltage before choosing cable, connectors, fuses, breakers, switches, controllers or inverters.",
    keywords: ["12 volt solar", "24 volt solar", "36 volt battery", "48 volt battery", "60 volt DC", "high voltage battery", "maximum charge voltage"],
    whatItIs: "System voltage is the nominal battery or circuit family; maximum operating and fault voltages are the higher real values equipment must safely withstand. A '48 V' battery, for example, does not remain exactly 48.0 V.",
    whatItDoes: "Voltage class determines compatible equipment, insulation, switching difficulty, shock/access rules, series battery arrangement and current required for a given power level.",
    usedFor: ["Vehicle and marine 12/24 V systems", "Small 12/24/36 V off-grid systems", "Common 48 V nominal storage systems", "60 V and other specialist DC systems", "Manufacturer-integrated high-voltage batteries", "High-voltage PV strings"],
    types: [
      { name: "12 V nominal", image: "/guides/voltage/12v-system.svg", description: "Common in vehicles, boats and small DC systems with a large accessory ecosystem.", bestFor: "Small loads and short cable runs where equipment compatibility supports it.", watchFor: "High power means very high current, large cable and severe voltage-drop/fault-current demands." },
      { name: "24 V nominal", image: "/guides/voltage/24v-system.svg", description: "Uses roughly half the current of 12 V for the same power.", bestFor: "Larger mobile, marine and modest off-grid systems using 24 V-compatible equipment.", watchFor: "Do not connect ordinary 12 V loads without a designed converter or separate supply." },
      { name: "36 V nominal", image: "/guides/voltage/36v-system.svg", description: "Used by some mobility, marine and specialist battery systems.", bestFor: "Only an equipment family expressly designed around that voltage.", watchFor: "The component ecosystem may be smaller; never substitute 24 or 48 V parts by assumption." },
      { name: "48 V nominal", image: "/guides/voltage/48v-system.svg", description: "Common in larger off-grid and stationary storage because current is lower than 12/24 V for the same power.", bestFor: "Compatible inverter/charger and battery platforms with controlled installation.", watchFor: "Maximum charged voltage can approach or exceed product boundaries; ordinary low-voltage automotive parts may not qualify." },
      { name: "60 V nominal or other intermediate DC", image: "/guides/voltage/60v-system.svg", description: "Used in some specialist equipment and battery arrangements.", bestFor: "A deliberately matched product ecosystem.", watchFor: "Touch/access rules and common 'low-voltage' accessory ratings can change at boundaries; use actual maximum voltage and local definitions." },
      { name: "High-voltage battery or PV DC", image: "/guides/voltage/high-voltage-dc.svg", description: "Series-connected batteries or PV strings can operate at hundreds of volts DC.", bestFor: "Manufacturer-integrated and professionally designed systems.", watchFor: "DC shock and arc hazards are severe. Use specified connectors, enclosures, switching, trained/authorised work and local high-voltage procedures." }
    ],
    questions: [
      { question: "Which voltage should my system use?", answer: "Choose from load power, cable length/current, available compatible batteries/inverters/chargers, expandability, installation environment and local safety requirements. PVIntell should compare valid complete architectures rather than defaulting everyone to 48 V." },
      { question: "Is nominal voltage the number I use to rate parts?", answer: "No. Use the highest possible circuit voltage under charging, temperature, regeneration or open-circuit conditions, plus whatever design margin/local rule applies. Nominal voltage is only the family name." },
      { question: "Can I use a higher-voltage-rated fuse or switch on a lower-voltage circuit?", answer: "Voltage rating is only one check. Current, interrupt capacity, poles/polarity, time-current curve, switching category, terminals and application approval must also pass." },
      { question: "Why does voltage change cable size?", answer: "For the same power, raising voltage reduces current, which can reduce conductor size and voltage drop. Higher voltage also raises insulation, switching, access and shock requirements." }
    ],
    buy: ["No component until both nominal and maximum circuit voltage are recorded", "Equipment sharing one complete supported voltage ecosystem", "DC protection and isolation rated for maximum voltage and fault duty", "Converters for loads requiring another voltage"],
    tools: ["Battery and equipment datasheets", "Maximum charge/discharge and PV cold-voltage worksheet", "Load power/current and voltage-drop calculation", "Local voltage-class and permitted-work guidance"],
    before: ["List every separate voltage domain on the schematic", "Calculate real minimum/maximum values", "Mark boundaries requiring conversion or isolation", "Confirm who may access or work on each domain"],
    steps: ["Choose the battery/system voltage from whole-system requirements", "Calculate operating current for major loads", "Check every battery, inverter, controller and charger range", "Check every fuse, breaker, isolator, connector, cable and meter maximum voltage", "Add converters for unmatched loads", "Apply local access/enclosure/work boundaries", "Label voltage domains on the proposed and as-built schematics"],
    checks: ["No hidden 48 V assumption", "Every component exceeds actual maximum voltage", "Fault interruption and switching ratings pass separately", "No 12/24 V accessory is placed on a higher-voltage circuit by shape alone", "High-voltage domains have suitable access controls"],
    source: "Use exact equipment voltage ranges and the Site jurisdiction's definitions; nominal labels never replace maximum-voltage and fault-duty checks."
  },
  {
    group: "Protection and isolation",
    id: "resettable-dc-circuit-breakers",
    title: "Resettable DC circuit breakers",
    aliases: ["Manual-reset breaker", "Thermal breaker", "Waterproof DC breaker", "Battery breaker", "DC trip switch"],
    image: "/guides/protection/resettable-dc-breaker.png",
    summary: "A reset button or lever makes this a circuit breaker, not a reusable fuse; it still needs the correct DC voltage, interrupt capacity and trip behaviour.",
    keywords: ["30A reset", "waterproof breaker", "solar breaker", "caravan breaker", "marine breaker", "manual reset"],
    whatItIs: "A mechanical overcurrent device that trips open and can be manually reset. Some models are ignition-protected, weather-resistant or suitable as a switch; those are separate stated ratings.",
    whatItDoes: "It can protect a compatible cable/circuit from overload or fault and may provide manual disconnection when expressly rated for that duty.",
    usedFor: ["12/24 V vehicle and marine circuits", "Low-voltage solar auxiliary loads", "Compatible battery branches", "Pumps, lighting and DC distribution"],
    types: [
      { name: "Surface-mount manual-reset breaker", image: "/guides/protection/resettable-dc-breaker.png", description: "Two-stud enclosed breaker with a push button, lever or reset arm.", bestFor: "A low-voltage DC branch within its exact environmental, voltage and interrupt ratings.", watchFor: "Cheap look-alikes may state an amp value without adequate DC interrupt or ignition/environment certification." },
      { name: "DIN-rail DC breaker", image: "/schematic-components/dc-circuit-breaker-mcb.jpg", description: "Enclosed modular breaker mounted in a compatible electrical enclosure.", bestFor: "Designed PV, controller or battery circuits using a genuinely DC-rated model and correct poles.", watchFor: "Polarity, series poles, maximum voltage, trip curve and interrupt rating must follow the exact diagram." },
      { name: "Blade-fuse-form resettable breaker", image: "/guides/protection/blade-fuse-sizes.png", description: "A small manual-reset breaker designed to fit some ATO/ATC fuse blocks.", bestFor: "Compatible low-voltage auxiliary circuits and fuse blocks.", watchFor: "It is not the same as a blade fuse and remains limited by its own voltage, interrupt and thermal ratings." }
    ],
    questions: [
      { question: "Is this a fuse?", answer: "No. A fuse melts once and is replaced. A circuit breaker uses a trip mechanism and can be reset after the cause is found and the circuit is safe." },
      { question: "Can I use one instead of any fuse?", answer: "No. The breaker must coordinate with the cable/equipment and safely interrupt the circuit's prospective DC fault current. Some high-energy battery circuits require a fuse family with much higher interrupt capacity." },
      { question: "Can I use it as the on/off switch?", answer: "Only if the exact product is rated for the required manual switching/isolation duty and expected number of operations. A reset lever alone does not prove isolation capability." },
      { question: "What voltages can it protect?", answer: "Whatever maximum DC voltage the exact model states—not whatever its case shape suggests. Select separately for 12, 24, 36, 48, 60 V or higher circuits using actual maximum voltage." },
      { question: "Where should it be mounted?", answer: "Near enough to the source to protect the outgoing conductor as the approved design requires, on a rigid surface or DIN rail, covered against accidental shorts, within temperature/environment ratings and accessible for safe reset after isolation and fault investigation." }
    ],
    buy: ["Breaker explicitly DC-rated above maximum circuit voltage", "Amp/trip curve coordinated with cable and load surge", "Interrupt rating above prospective fault current", "Correct pole count/polarity and switching category", "Suitable enclosure, terminal boots and mounting hardware"],
    tools: ["Circuit and fault-current calculation", "Exact breaker datasheet", "Cable lug/crimp tools", "Calibrated torque tool", "Safe test/isolation equipment"],
    before: ["Identify all sources feeding the fault", "Check whether fuse-level interrupt performance is required", "Confirm environmental and ignition-protection needs", "Investigate why an existing breaker tripped before resetting"],
    steps: ["Mark the protected conductor on the schematic", "Select voltage, current/trip and interrupt ratings", "Confirm required switching/isolation function", "Mount in the stated orientation and enclosure", "Terminate supported conductors to stated torque", "Fit covers and circuit labels", "Test trip/reset or prescribed checks without creating a fault", "Record exact model and rating"],
    checks: ["Correct maximum DC voltage and polarity", "Adequate interrupt capacity", "Cable remains protected through load surges", "No exposed live studs", "Reset does not substitute for fault diagnosis"],
    source: "Use the exact breaker application data. ATO-form and surface-mount examples commonly serve low-voltage auto, marine and solar auxiliary circuits, not every solar DC domain."
  },
  {
    group: "AC wiring and connections",
    id: "rcd-rcbo-selection",
    title: "RCD, RCBO and inverter leakage requirements",
    image: "/schematic-components/rcd-rccb.jpg",
    summary: "Residual-current protection type and arrangement must match the inverter, circuit, earthing system and local rules.",
    keywords: ["RCD", "RCBO", "GFCI", "earth leakage", "nuisance tripping", "type A", "type B"],
    whatItIs: "An RCD/GFCI detects current imbalance to earth; an RCBO combines residual-current and overcurrent protection. Different sensing types respond to different residual waveforms.",
    whatItDoes: "It provides additional shock/fire protection where required, but incorrect type, neutral routing or grouping can cause loss of protection or unwanted tripping.",
    buy: ["Protection type and rating required by inverter and local design", "Correct poles, breaking capacity and enclosure", "Dedicated neutral arrangement and labels where required"],
    before: ["Read the inverter's stated residual-current protection requirements", "Confirm earthing/neutral arrangement in grid and backup modes", "Calculate/select overcurrent protection separately"],
    steps: ["Mark protected circuits and all active/neutral paths", "Select required RCD/RCBO sensing type", "Coordinate rating with cable and upstream protection", "Keep circuit neutrals in their correct protected group", "Install and torque through the authorised process", "Perform required trip-time/current tests", "Record device type and results"],
    checks: ["No shared/misrouted neutral defeats protection", "Type matches inverter residual behaviour", "Test button and instrument tests both pass", "Backup/changeover modes are included in testing"],
    source: "This is local regulated AC work; use the exact inverter manual, protection maker data and local wiring/test requirements."
  },
  {
    group: "Monitoring and communications",
    id: "ct-clamp-direction",
    title: "CT clamps: location, direction and phase",
    image: "/schematic-components/current-transformer-ct-clamp.jpg",
    summary: "A CT on the wrong conductor, backwards or assigned to the wrong phase makes import look like export and breaks control decisions.",
    keywords: ["CT", "current transformer", "clamp meter sensor", "import export wrong", "meter arrow", "phase mapping"],
    whatItIs: "A current transformer clips around one conductor and reports current direction/magnitude to a meter, inverter or export controller.",
    whatItDoes: "Correctly placed CTs measure grid flow, load or generation without being placed in series with the conductor.",
    buy: ["CT model/rating specified by the meter or inverter", "Correct cable/extension and connector", "Required multi-phase set and meter/gateway"],
    before: ["Identify the exact measurement point and conductor", "Confirm arrow/source-load convention", "Match each CT to its voltage phase", "Use an authorised person where enclosure access is restricted"],
    steps: ["Label phases and planned CT IDs", "Open the CT and close it fully around one permitted conductor only", "Orient the arrow/mark as the selected manual states", "Route the CT lead away from damage and interference", "Connect each CT to the matching meter input", "Apply known load/generation and verify direction", "Correct configuration/orientation before enabling export control"],
    checks: ["CT surrounds one conductor, not an entire multicore cable", "Jaw is fully closed", "Phase mapping and direction are proven by a test", "Loss/disconnection behaviour is understood"],
    source: "Use the exact meter/inverter/export-control CT installation and commissioning manual."
  },
  {
    group: "Tools and workmanship",
    id: "meter-safe-use",
    title: "Meters and testers: know the safe boundary",
    image: "/schematic-components/energy-meter.jpg",
    summary: "Choose a correctly rated instrument and test method; a familiar multimeter can still be unsafe on PV strings, batteries or mains.",
    keywords: ["multimeter", "test voltage", "clamp meter", "CAT rating", "prove dead", "insulation tester", "PV tester"],
    whatItIs: "Meters measure voltage, current, resistance or insulation, but their category, voltage, leads, fusing and method must suit the energy source.",
    whatItDoes: "A controlled test confirms circuit condition without exposing the user or instrument to energy beyond its rating.",
    buy: ["Instrument with suitable voltage/category and DC capability", "Approved fused/shrouded leads and probes", "Proving unit or approved known-source method", "PV-specific tester where required by the test plan"],
    before: ["Know whether the work is legally restricted", "Check maximum possible PV open-circuit voltage and battery fault energy", "Inspect case, leads, tips, fuses and battery", "Never use resistance/current modes on an energised voltage source"],
    steps: ["Select the required test from the approved plan", "Confirm instrument and lead ratings", "Inspect and prove the tester", "Select function/range before touching the circuit", "Use controlled probe placement and required PPE/access controls", "Read and record the result", "Withdraw safely and prove the tester again where required", "Stop for unexpected readings"],
    checks: ["Instrument rating exceeds the circuit duty", "Correct sockets/function/range used", "Test-before/test-after process completed where required", "Result is tied to the correct circuit and conditions"],
    source: "Follow the exact test-instrument manual and local safe-isolation/licensing rules; this guide does not authorise live electrical work."
  }
] as const;
