import { ArrowLeft, BatteryCharging, CloudSun, Fuel, Gauge, Heart, HousePlug, Leaf, ShieldCheck, Sun } from "lucide-react";
import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";

const approaches = [
  { icon: BatteryCharging, title: "Off-grid", text: "Your home makes and stores its own power. Most days can feel entirely normal with a well-sized system; you simply learn to notice the weather, do flexible jobs in sunshine and keep a sensible reserve." },
  { icon: HousePlug, title: "Grid-connected", text: "The electricity network is still there when solar is not enough. You can still save money by using your own solar during the day, but a cloudy week usually changes the bill rather than forcing you to stop using power." },
  { icon: Gauge, title: "Solar with a battery", text: "A battery lets you use daytime sunshine later and may keep important things working during an outage. Understanding which larger appliances use the most energy helps that stored power go further." },
  { icon: Leaf, title: "Low-power living", text: "This does not have to mean going without. It means choosing efficient appliances, avoiding unnecessary waste and deciding which comforts matter most when the available energy is limited." },
];

const lowYield = [
  ["Check today and tomorrow", "Look at the battery and the weather forecast together. A full battery on a sunny morning is different from the same battery before three wet days."],
  ["Keep the important things running", "Refrigeration, water pumps, communications, medical needs, security and lighting often come first. Decide what is essential in your household before energy gets tight."],
  ["Do big jobs while the sun is out", "Laundry, pumping, workshop tools, charging and other flexible jobs are easier on the battery when the panels are producing well."],
  ["Be careful with large appliances", "Heaters, hot-water systems, ovens, kettles, dryers, pumps and power tools can use a lot of energy. Several running together can matter as much as how long they run."],
  ["Slow down early", "Turning off optional loads before the battery is nearly empty is far easier than suddenly losing power late at night."],
];

export default function LivingWithSolarPage() {
  return <main className="min-h-screen bg-canvas text-ink"><header className="border-b border-line bg-white"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 md:px-6"><Link href="/settings" className="inline-flex items-center gap-2 text-xs font-bold text-muted"><ArrowLeft size={15}/>Settings</Link><BrandLogo compact/></div></header><div className="mx-auto max-w-5xl space-y-6 p-4 pb-16 md:p-6">
    <section className="overflow-hidden rounded-3xl bg-[linear-gradient(105deg,#0b3456,#1768a6)] p-6 text-white shadow-xl md:p-9"><div className="eyebrow text-[#ffd44f]">A different way to think about power</div><h1 className="mt-3 font-display text-3xl font-extrabold tracking-[-.05em] md:text-4xl">Living with Solar</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/90">Moving from city life to a rural or off-grid home can bring more independence, resilience and control over energy costs. The main change is becoming aware of where electricity comes from. Most people soon settle into a simple rhythm: make power in daylight, store some for later and match flexible jobs to better days.</p></section>

    <section className="card p-5 md:p-7"><div className="eyebrow">What would it actually be like?</div><h2 className="mt-2 text-xl font-extrabold">Imagine your first winter living off-grid</h2><div className="mt-4 space-y-3 text-sm leading-6 text-muted"><p>On most days, life feels normal. The panels run the house, charge the battery and provide energy for washing, pumping water or using tools. There is a genuine satisfaction in seeing the home quietly powered by sunlight—and in being less affected by outside power cuts or rising electricity prices.</p><p>After a few dull days, you check the battery and forecast. You may move the laundry to tomorrow, avoid running several large appliances together or choose a less energy-hungry way to cook. These choices soon become familiar rather than burdensome, much like checking the fuel gauge before a long drive.</p><p>If poor weather continues, a generator may recharge the battery and restore breathing room. It costs money, makes noise and needs maintenance, but in a well-planned system it is an occasional safety net rather than the centre of daily life.</p><p>Before long, you know your home’s rhythm. You know which appliances are hungry, when the battery usually fills and how much reserve makes you comfortable. That awareness often feels empowering: you are managing your own small power supply rather than simply receiving a bill.</p></div></section>

    <section className="grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-[#9bd2ad] bg-[#f2fbf5] p-5"><h2 className="text-lg font-extrabold text-[#17603b]">What people often enjoy</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-xs leading-5 text-muted"><li>Greater independence from power cuts, electricity prices or a distant grid.</li><li>Low everyday running costs when the system and sunshine meet the household’s needs.</li><li>Quiet generation with no fuel delivery required for normal sunny-day operation.</li><li>The satisfaction of producing, storing and managing your own energy.</li><li>Freedom to live comfortably in places where bringing in grid power would be difficult or expensive.</li><li>Better awareness of waste, often without any meaningful loss of comfort.</li></ul></article><article className="rounded-2xl border border-[#e6cc74] bg-[#fff9df] p-5"><h2 className="text-lg font-extrabold text-[#765918]">The adjustments to expect</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-xs leading-5 text-muted"><li>Checking the battery and forecast becomes part of planning during poor weather.</li><li>Some flexible jobs may wait for a brighter day.</li><li>Several large appliances may need to be used one after another rather than together.</li><li>A backup generator brings fuel, noise and servicing, although a suitable system may need it only occasionally.</li><li>Equipment needs basic care, and eventual battery or inverter replacement should be budgeted for.</li><li>Good sizing matters: enough generation and storage makes the lifestyle far easier.</li></ul></article></section>

    <section><div className="eyebrow">What changes?</div><h2 className="mt-2 text-xl font-extrabold">The difference is what happens when solar is not enough</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{approaches.map(({ icon: Icon, title, text }) => <article key={title} className="card p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#eaf2fb] text-brand"><Icon size={19}/></span><h3 className="mt-3 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-muted">{text}</p></article>)}</div></section>

    <section className="card p-5 md:p-7"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#fff2ba] text-[#9a6800]"><CloudSun size={21}/></span><div><div className="eyebrow">Low-yield periods</div><h2 className="mt-1 text-xl font-extrabold">Use less, shift loads, protect your reserve</h2></div></div><div className="mt-5 grid gap-3">{lowYield.map(([title, text], index) => <div key={title} className="flex gap-3 rounded-xl border border-line bg-[#f8fbfe] p-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-brand text-[10px] font-extrabold text-white">{index + 1}</span><div><h3 className="text-xs font-extrabold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted">{text}</p></div></div>)}</div></section>

    <div className="grid gap-4 md:grid-cols-2"><section className="card p-5 md:p-6"><Fuel className="text-brand"/><h2 className="mt-3 text-lg font-extrabold">Where a generator fits</h2><p className="mt-2 text-xs leading-5 text-muted">In an off-grid home, a generator is often the rainy-week safety net. It can recharge the battery or help carry unusually large demand when solar is low.</p><ul className="mt-4 list-disc space-y-2 pl-5 text-xs leading-5 text-muted"><li>Do not wait until everything has gone flat before using it.</li><li>Keep enough fuel available for the kind of weather and isolation you experience.</li><li>Run and maintain it exactly as its maker requires, especially around fumes and ventilation.</li><li>Have its connection to the home installed correctly—never improvise a lead into household wiring.</li></ul></section><section className="card p-5 md:p-6"><Sun className="text-[#d79500]"/><h2 className="mt-3 text-lg font-extrabold">Becoming comfortably self-sufficient</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-xs leading-5 text-muted"><li>Learn which appliances use the most power.</li><li>Choose efficient replacements when appliances wear out.</li><li>Notice how the system behaves in summer, winter and long cloudy periods.</li><li>Make sunny days your washing, pumping, charging and workshop days.</li><li>Keep simple backup plans for water, cooking, heating and communication.</li><li>Add more equipment only after you know what is regularly running short.</li></ul></section></div>

    <section className="grid gap-3 sm:grid-cols-3"><article className="rounded-2xl border border-[#9bd2ad] bg-[#f2fbf5] p-5"><Heart className="text-[#20724b]"/><h3 className="mt-3 text-sm font-extrabold">Comfort and resilience</h3><p className="mt-2 text-xs leading-5 text-muted">Well-planned solar can keep important services available and make energy use more predictable.</p></article><article className="rounded-2xl border border-[#9fc6e7] bg-[#eef6fd] p-5"><Leaf className="text-brand"/><h3 className="mt-3 text-sm font-extrabold">Lower energy impact</h3><p className="mt-2 text-xs leading-5 text-muted">Using locally generated renewable energy can reduce fuel use and grid imports, depending on the system and regional electricity mix.</p></article><article className="rounded-2xl border border-[#e6cc74] bg-[#fff9df] p-5"><ShieldCheck className="text-[#8b6512]"/><h3 className="mt-3 text-sm font-extrabold">Informed control</h3><p className="mt-2 text-xs leading-5 text-muted">Understanding where energy goes helps you respond to faults, weather and changing needs with confidence.</p></article></section>

    <section className="rounded-2xl border border-line bg-white p-5 text-xs leading-5 text-muted"><strong className="text-ink">This is a lifestyle introduction.</strong> Every home, climate and electricity arrangement is different. Follow the instructions supplied with your equipment and use qualified local help for electrical work, generator connections or anything you are unsure about.</section>
  </div></main>;
}
