import { BatteryCharging, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { login, signup } from "./actions";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const notice = await searchParams;
  return <main className="grid min-h-screen bg-[#f4f6f1] lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden bg-[#183c2e] p-14 text-white lg:flex lg:flex-col">
      <div className="absolute -right-28 -top-28 size-[420px] rounded-full bg-[#d7f05f]/15 blur-2xl"/><div className="relative flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#d7f05f] text-[#173c2d]"><Zap size={21} fill="currentColor"/></span><div><div className="font-display text-xl font-extrabold">PVIntell</div><div className="text-[9px] font-bold uppercase tracking-[.2em] text-white/55">Power, made clear</div></div></div>
      <div className="relative my-auto max-w-xl"><div className="text-xs font-bold uppercase tracking-[.16em] text-[#d7f05f]">Meet Wattson</div><h1 className="mt-5 font-display text-5xl font-extrabold leading-[1.08] tracking-[-.055em]">Describe the life you want.<br/>We’ll design the power.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/65">From first idea to commissioning and daily diagnostics, Wattson keeps your system knowledge in one secure place.</p><div className="mt-10 grid grid-cols-2 gap-4"><Feature icon={Sparkles} title="Beginner first" text="No electrical jargon required."/><Feature icon={BatteryCharging} title="One system record" text="Design through monitoring."/></div></div>
      <div className="relative flex items-center gap-2 text-[11px] text-white/45"><ShieldCheck size={14}/>Your projects are private by default.</div>
    </section>
    <section className="flex items-center justify-center p-6 md:p-12"><div className="w-full max-w-[430px]"><div className="mb-9 lg:hidden"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand text-white"><Zap size={20} fill="currentColor"/></span><strong className="font-display text-xl">PVIntell</strong></div></div><div className="eyebrow">Welcome</div><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-.045em]">Your power system starts here</h2><p className="mt-3 text-sm leading-6 text-muted">Sign in, or create an account to start designing with Wattson.</p>
      {(notice.error||notice.message)&&<div className={`mt-6 rounded-xl border p-3 text-xs ${notice.error?"border-[#e7c3b8] bg-[#fff1ed] text-[#8b432f]":"border-[#bad5c3] bg-[#eaf5ed] text-[#286143]"}`}>{notice.error??notice.message}</div>}
      <button type="button" disabled title="Google sign-in will be enabled after OAuth setup" className="mt-7 flex h-12 w-full cursor-not-allowed items-center justify-center gap-3 rounded-xl border border-[#ccd4cc] bg-white text-sm font-bold text-[#36413b] opacity-65"><span className="grid size-6 place-items-center rounded-full border border-[#d7dcd7] font-bold text-[#4285f4]">G</span>Continue with Google <span className="rounded-full bg-[#edf0eb] px-2 py-0.5 text-[8px] uppercase tracking-wider text-muted">Soon</span></button><div className="my-5 flex items-center gap-3 text-[10px] uppercase tracking-wider text-muted"><span className="h-px flex-1 bg-line"/>or use email<span className="h-px flex-1 bg-line"/></div>
      <form className="space-y-4"><label className="block text-xs font-bold">Email<input name="email" type="email" autoComplete="email" required className="mt-2 h-12 w-full rounded-xl border border-line bg-white px-4 font-normal outline-none focus:border-brand" placeholder="you@example.com"/></label><label className="block text-xs font-bold">Confirm email <span className="font-normal text-muted">(new accounts)</span><input name="emailConfirm" type="email" autoComplete="email" className="mt-2 h-12 w-full rounded-xl border border-line bg-white px-4 font-normal outline-none focus:border-brand" placeholder="Type your email again"/></label><label className="block text-xs font-bold">Password<input name="password" type="password" autoComplete="current-password" required minLength={8} className="mt-2 h-12 w-full rounded-xl border border-line bg-white px-4 font-normal outline-none focus:border-brand" placeholder="At least 8 characters"/></label><button formAction={login} formNoValidate className="h-12 w-full rounded-xl bg-brand text-sm font-bold text-white hover:bg-[#15583b]">Sign in</button><button formAction={signup} className="h-12 w-full rounded-xl border border-[#b9c8bc] bg-white text-sm font-bold text-ink hover:bg-[#f3f6f1]">Create account</button></form><p className="mt-6 text-center text-[10px] leading-4 text-muted">By creating an account, you agree to use PVIntell as guidance—not as a substitute for required licensed electrical work.</p></div></section>
  </main>;
}
function Feature({icon:Icon,title,text}:{icon:typeof Sparkles;title:string;text:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><Icon className="text-[#d7f05f]" size={18}/><div className="mt-3 text-sm font-bold">{title}</div><div className="mt-1 text-[11px] text-white/55">{text}</div></div>}
