import type { Metadata } from "next";
import { ArrowRight, BatteryCharging, BookOpen, Bot, Cable, ChartNoAxesCombined, Check, CloudSun, Compass, Menu, Network, ShieldCheck, Sparkles, Sun, WalletCards, Zap } from "lucide-react";
import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";
import { InstallAppButton } from "@/components/install-app-button";
import { LocalDevFooter } from "@/components/localdev-footer";
import { getSupabaseConfig } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/server";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://pv-intell.vercel.app";
const description = "Brand-independent solar planning and guidance for DIYers and experienced users. Document, build, monitor and understand any solar power system with PVIntell and Wattson.";

export const metadata: Metadata = {
  title: "PVIntell | Solar design, guidance and system intelligence", description,
  keywords: ["DIY solar planning", "brand independent solar advice", "solar system design", "solar planning software", "solar monitoring", "off-grid solar", "battery system planning", "solar schematic", "solar calculator", "PV system management"],
  alternates: { canonical: "/" }, robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } },
  openGraph: { type: "website", url: siteUrl, siteName: "PVIntell", title: "Your solar system, made easier", description, images: [{ url: "/backgrounds/haniaipics-ai-generated-8886042_1920.jpg", width: 1920, height: 960, alt: "Solar panels beneath a bright sunset" }] },
  twitter: { card: "summary_large_image", title: "PVIntell | Your solar. Answered.", description, images: ["/backgrounds/haniaipics-ai-generated-8886042_1920.jpg"] },
};

const features = [
  [Sparkles, "Guided discovery", "Start with what you want to power. Plain-language answers become an evidence-led system brief."],
  [Compass, "Design calculator", "Explore panel, battery and inverter requirements while assumptions and unknowns stay visible."],
  [Network, "Living schematics", "Build proposed and as-installed system maps, move components and follow every connection."],
  [CloudSun, "Solar weather", "See five-day hourly irradiance, cloud, rain, wind and estimated solar yield for each Site."],
  [ChartNoAxesCombined, "System monitoring", "Bring current readings, battery state and system records together for clearer diagnostics."],
  [WalletCards, "Solar finances", "Record purchases, costs, rebates and buy-back payments with a running net total."],
  [BookOpen, "Practical how-to library", "Search visual guidance across panels, batteries, wiring, mounting, EV charging and more."],
  [Bot, "Ask Wattson", "Talk through forecasts, equipment, designs and faults using context already recorded in PVIntell."],
] as const;

export default async function Home() {
  let signedIn = false;
  if (getSupabaseConfig().configured) { const supabase = await createClient(); const claims = await supabase.auth.getClaims(); signedIn = !claims.error && typeof claims.data?.claims?.sub === "string"; }
  const primaryHref = signedIn ? "/dashboard" : "/login?mode=signup";
  const primaryLabel = signedIn ? "Open your dashboard" : "Create your account";
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "PVIntell", applicationCategory: "UtilitiesApplication", operatingSystem: "Web", url: siteUrl, description, featureList: features.map(([, title]) => title) };

  return <div className="min-h-screen overflow-hidden bg-[#071525] text-white">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }}/>
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#071525]/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1240px] items-center gap-5 px-4 sm:px-6"><Link href="/" aria-label="PVIntell home"><BrandLogo inverse/></Link><nav className="ml-auto hidden items-center gap-6 text-xs font-bold text-white/70 md:flex"><a href="#platform">Platform</a><a href="#wattson">Wattson</a><a href="#features">Features</a><a href="#how-it-works">How it works</a></nav><Link href="/login" className="ml-auto text-xs font-bold md:ml-3">Sign in</Link><Link href={primaryHref} className="hidden rounded-xl bg-[#f6c945] px-4 py-2.5 text-xs font-extrabold text-[#11395e] sm:inline-flex">{signedIn ? "Dashboard" : "Create account"}</Link><Menu className="text-white/70 md:hidden" size={20}/></div></header>

    <div className="fixed right-4 top-20 z-50 w-auto sm:right-6">
      <InstallAppButton/>
    </div>
    <main>
      <section className="relative flex min-h-[min(860px,100dvh)] items-center pt-16"><div className="absolute inset-0 bg-cover bg-[65%_center]" style={{ backgroundImage: "url('/backgrounds/haniaipics-ai-generated-8886042_1920.jpg')" }}/><div className="absolute inset-0 bg-[linear-gradient(90deg,#071525_4%,rgba(7,21,37,.94)_36%,rgba(7,21,37,.55)_68%,rgba(7,21,37,.25))]"/><div className="absolute inset-x-0 bottom-0 h-52 bg-gradient-to-t from-[#071525] to-transparent"/><div className="relative mx-auto grid w-full max-w-[1240px] items-center gap-12 px-5 py-20 sm:px-6 lg:grid-cols-[.92fr_1.08fr]"><div className="animate-rise"><div className="inline-flex items-center gap-2 rounded-full border border-[#f6c945]/30 bg-[#f6c945]/10 px-3 py-2 text-[10px] font-extrabold uppercase tracking-[.18em] text-[#ffe174]"><Sun size={14}/> From first idea to daily operation</div><h1 className="mt-6 max-w-3xl font-display text-[clamp(3rem,7vw,6.5rem)] font-extrabold leading-[.92] tracking-[-.07em]">Build solar<br/><span className="text-[#f6c945]">with confidence.</span></h1><p className="mt-6 max-w-xl text-base font-medium leading-7 text-white/75 sm:text-lg sm:leading-8">PVIntell brings design, system records, schematics, forecasts, monitoring and practical guidance into one intelligent solar workspace.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={primaryHref} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl bg-[#f6c945] px-6 text-sm font-extrabold text-[#11395e] shadow-[0_18px_45px_rgba(246,201,69,.2)]">{primaryLabel}<ArrowRight size={17}/></Link>{!signedIn ? <Link href="/login" className="inline-flex min-h-13 items-center justify-center rounded-2xl border border-white/25 bg-white/8 px-6 text-sm font-bold backdrop-blur">Sign in</Link> : null}</div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-[11px] font-semibold text-white/60"><span className="flex items-center gap-2"><Check size={14} className="text-[#f6c945]"/>DIY-friendly</span><span className="flex items-center gap-2"><Check size={14} className="text-[#f6c945]"/>Any brand or starting point</span><span className="flex items-center gap-2"><Check size={14} className="text-[#f6c945]"/>Built around real records</span></div></div><AppPreview/></div></section>

      <section id="platform" className="relative py-24"><div className="mx-auto max-w-[1180px] px-5 sm:px-6"><div className="mx-auto max-w-3xl text-center"><div className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#69b9f2]">One connected solar record</div><h2 className="mt-4 font-display text-3xl font-extrabold tracking-[-.05em] sm:text-5xl">Not another disconnected calculator.</h2><p className="mt-5 text-sm leading-7 text-white/60 sm:text-base">A solar system changes from an idea into physical equipment, then into something you operate for years. PVIntell keeps that journey connected.</p></div><div id="features" className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,text]) => <article key={title} className="group rounded-2xl border border-white/10 bg-white/[.045] p-5 transition hover:-translate-y-1 hover:border-[#65b7ef]/40 hover:bg-white/[.075]"><span className="grid size-11 place-items-center rounded-2xl bg-[#123b61] text-[#72bff4] group-hover:bg-[#f6c945] group-hover:text-[#11395e]"><Icon size={20}/></span><h3 className="mt-5 text-base font-extrabold">{title}</h3><p className="mt-2 text-xs leading-6 text-white/55">{text}</p></article>)}</div></div></section>

      <section className="px-5 pb-24 sm:px-6"><div className="mx-auto grid max-w-[1180px] overflow-hidden rounded-[30px] border border-[#69b9f2]/25 bg-[linear-gradient(120deg,#0d2d4a,#10243a)] lg:grid-cols-[.8fr_1.2fr]"><div className="flex min-h-64 items-end bg-cover bg-center p-7" style={{ backgroundImage: "linear-gradient(0deg,rgba(7,21,37,.9),rgba(7,21,37,.18)),url('/backgrounds/vilkasss-ai-generated-8897488_1920.jpg')" }}><div><div className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#f6c945]">Independent by design</div><p className="mt-3 max-w-sm font-display text-2xl font-extrabold leading-tight">Your system. Your equipment. Your starting point.</p></div></div><div className="p-7 sm:p-10"><h2 className="font-display text-3xl font-extrabold tracking-[-.045em] sm:text-4xl">No brand allegiance. No judgement.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/65">PVIntell is not affiliated with a solar manufacturer. We do not care which logo is on the equipment, where you bought it, or whether you are opening your first datasheet or maintaining a system you built years ago. Bring what you already have and start from what you know.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["DIY curious","Learn the language and explore safely before buying."],["Hands-on builder","Plan, compare, document and keep unknowns visible."],["Experienced owner","Record, monitor and understand a mixed or evolving system."]].map(([title,text]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><strong className="text-sm text-[#f6c945]">{title}</strong><p className="mt-2 text-xs leading-5 text-white/55">{text}</p></div>)}</div><p className="mt-5 text-[11px] leading-5 text-white/45">PVIntell helps you make informed decisions; product manuals, local requirements and appropriately qualified people still control regulated or hazardous work.</p></div></div></section>

      <section id="wattson" className="relative py-20"><div className="absolute inset-0 bg-cover bg-center opacity-25" style={{ backgroundImage: "url('/backgrounds/vilkasss-ai-generated-8897488_1920.jpg')" }}/><div className="absolute inset-0 bg-[linear-gradient(90deg,#081727,rgba(8,23,39,.82),#081727)]"/><div className="relative mx-auto grid max-w-[1180px] items-center gap-12 px-5 sm:px-6 lg:grid-cols-2"><div><div className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#f6c945]">Meet Wattson</div><h2 className="mt-4 font-display text-4xl font-extrabold leading-tight tracking-[-.055em] sm:text-5xl">Your system already has the context. Just ask.</h2><p className="mt-5 text-sm leading-7 text-white/65">Wattson can use the Site, system records, monitoring data and the same five-day forecast shown in PVIntell—keeping answers grounded in what the app actually knows.</p><div className="mt-6 space-y-3">{["Will today’s forecast give the battery a useful charge window?","What changed in the latest monitoring readings?","Help me understand this inverter label.","What is still missing from my proposed design?"].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold"><span className="grid size-7 place-items-center rounded-full bg-[#f6c945] text-[#11395e]"><Zap size={13}/></span>{item}</div>)}</div></div><div className="rounded-[28px] border border-white/15 bg-[#eef4f8] p-4 text-[#14233a] shadow-[0_30px_80px_rgba(0,0,0,.35)]"><div className="border-b border-[#d7e1ea] pb-4"><div className="text-[9px] font-extrabold uppercase tracking-[.16em] text-[#165d9c]">Wattson · River Views</div><strong className="mt-1 block">Solar assistant</strong></div><div className="space-y-3 py-5"><div className="ml-auto max-w-[82%] rounded-2xl rounded-br-md bg-[#165d9c] px-4 py-3 text-xs leading-5 text-white">How is tomorrow looking for solar?</div><div className="max-w-[88%] rounded-2xl rounded-bl-md bg-white px-4 py-3 text-xs leading-6 shadow-sm">Tomorrow has its best solar window around midday. I’ll compare the hourly irradiance with your current battery reserve and separate forecast values from live readings.</div></div><div className="flex items-center gap-2 rounded-2xl border border-[#d7e1ea] bg-white p-2"><span className="flex-1 px-2 text-xs text-[#728195]">Ask about weather, design or your system…</span><span className="grid size-9 place-items-center rounded-xl bg-[#165d9c] text-white"><ArrowRight size={15}/></span></div></div></div></section>

      <section id="how-it-works" className="py-24"><div className="mx-auto grid max-w-[1180px] gap-12 px-5 sm:px-6 lg:grid-cols-[.85fr_1.15fr]"><div><div className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#69b9f2]">From blank page to useful system</div><h2 className="mt-4 font-display text-4xl font-extrabold tracking-[-.055em]">A practical path - not a wall of electrical jargon.</h2><p className="mt-4 text-sm leading-7 text-white/60">Start at your own level. PVIntell keeps confirmed facts, estimates and unknowns distinct while helping you move forward.</p></div><div className="grid gap-3">{[["Discover","Describe the Site, what you want to power and what matters most."],["Design","Turn evidence into a proposed arrangement and staged sizing plan."],["Build & document","Use visual guides, component records, photos and a working schematic."],["Monitor & understand","Combine forecasts, readings, maintenance context and saved knowledge."]].map(([title,text]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><h3 className="text-base font-extrabold text-[#f6c945]">{title}</h3><p className="mt-1 text-xs leading-6 text-white/55">{text}</p></div>)}</div></div></section>

      <section className="px-5 pb-24 sm:px-6"><div className="relative mx-auto max-w-[1180px] overflow-hidden rounded-[32px] border border-[#f6c945]/25 bg-[#0f3b66] px-6 py-14 text-center sm:px-10"><ShieldCheck className="mx-auto text-[#f6c945]" size={32}/><h2 className="mx-auto mt-5 max-w-3xl font-display text-3xl font-extrabold tracking-[-.05em] sm:text-5xl">Give your solar system one place to make sense.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-white/65">Plan it, record it, understand it and keep the knowledge useful long after installation day.</p><Link href={primaryHref} className="mt-8 inline-flex min-h-13 items-center gap-2 rounded-2xl bg-[#f6c945] px-7 text-sm font-extrabold text-[#11395e]">{primaryLabel}<ArrowRight size={17}/></Link></div></section>
    </main><div className="border-t border-white/10 bg-[#06111e] text-white [&_a]:text-white/65 [&_div]:border-white/10 [&_span]:text-white/45"><LocalDevFooter/></div>
  </div>;
}

function AppPreview() { return <div className="relative hidden lg:block"><div className="absolute -inset-12 rounded-full bg-[#f6c945]/15 blur-3xl"/><div className="relative rotate-[1.5deg] rounded-[28px] border border-white/20 bg-[#eaf1f6]/95 p-3 shadow-[0_45px_100px_rgba(0,0,0,.42)]"><div className="flex items-center gap-1.5 px-2 pb-3"><span className="size-2.5 rounded-full bg-[#ff746c]"/><span className="size-2.5 rounded-full bg-[#f6c945]"/><span className="size-2.5 rounded-full bg-[#43c178]"/></div><div className="overflow-hidden rounded-2xl bg-[#102b44]"><div className="h-44 bg-cover bg-center p-5" style={{ backgroundImage: "linear-gradient(90deg,rgba(7,31,53,.92),rgba(7,31,53,.25)),url('/backgrounds/haniaipics-ai-generated-8886042_1920.jpg')" }}><span className="text-[8px] font-extrabold uppercase tracking-[.15em] text-[#f6c945]">Today at River Views</span><h3 className="mt-3 font-display text-2xl font-extrabold">Good to see you.</h3><p className="mt-2 text-[9px] font-semibold text-white/75">Your solar system, made easier to build, understand and manage.</p><div className="mt-5 flex gap-2"><PreviewPill icon={Sun} text="427 W/m²"/><PreviewPill icon={CloudSun} text="7% cloud"/><PreviewPill icon={BatteryCharging} text="73% battery"/></div></div><div className="grid grid-cols-3 gap-2 bg-[#eaf1f6] p-3 text-[#14233a]"><PreviewMetric label="Expected solar" value="27.7 kWh"/><PreviewMetric label="Best solar hour" value="3 pm"/><PreviewMetric label="Systems" value="2 live"/></div><div className="grid grid-cols-2 gap-2 bg-[#eaf1f6] px-3 pb-3 text-[#14233a]"><div className="rounded-xl bg-[#f6c945] p-3"><Cable size={15} className="text-[#165d9c]"/><strong className="mt-4 block text-[10px]">System schematic</strong></div><div className="rounded-xl bg-white p-3"><ChartNoAxesCombined size={15} className="text-[#165d9c]"/><strong className="mt-4 block text-[10px]">Live monitoring</strong></div></div></div></div></div>; }
function PreviewPill({ icon: Icon, text }: { icon: typeof Sun; text: string }) { return <span className="flex items-center gap-1.5 rounded-lg border border-white/25 bg-[#0a2944]/75 px-2 py-1.5 text-[8px] font-bold"><Icon size={10} className="text-[#f6c945]"/>{text}</span>; }
function PreviewMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white p-3"><span className="block text-[7px] font-bold text-[#728195]">{label}</span><strong className="mt-2 block text-xs">{value}</strong></div>; }
