"use client";

import { ArrowLeft, Camera, LoaderCircle, ScanLine, Sun, Trash2, Zap } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import type { EquipmentLabelExtraction } from "@/ai/equipment-label";
import type { PVArray } from "@/domain/models";

const optionalNumber = (form: FormData, name: string) => { const value = String(form.get(name) ?? "").trim(); return value ? Number(value) : undefined; };
const parseSpecs = (value: FormDataEntryValue | null) => Object.fromEntries(String(value ?? "").split("\n").map((line) => line.split(":")) .filter((parts) => parts.length > 1 && parts[0].trim()).map(([key, ...rest]) => [key.trim(), rest.join(":").trim()]));
function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) { return <label className="text-xs font-bold">{label}{children}{help && <span className="mt-1 block text-[9px] font-normal leading-4 text-muted">{help}</span>}</label>; }

export function PVStringDetail({ siteId, systemId, systemName, string }: { siteId: string; systemId: string; systemName: string; string?: PVArray }) {
  const router = useRouter(); const [saving,setSaving] = useState(false); const [analyzing,setAnalyzing] = useState(false); const [error,setError] = useState(""); const [extraction,setExtraction] = useState<EquipmentLabelExtraction>(); const [photoPath,setPhotoPath] = useState(string?.labelPhotoPath ?? ""); const formRef = useRef<HTMLFormElement>(null); const back = `/sites/${siteId}/systems/${systemId}`;
  function setField(name: string, value: string) { if (!value) return; const field = formRef.current?.elements.namedItem(name); if (field instanceof HTMLInputElement || field instanceof HTMLSelectElement || field instanceof HTMLTextAreaElement) field.value = value; }
  const numberFrom = (value: string) => value.match(/-?\d+(?:\.\d+)?/)?.[0] ?? "";
  function applyExtraction(result: EquipmentLabelExtraction) {
    setField("manufacturer", result.manufacturer); setField("panelModel", result.model); setField("panelWatts", numberFrom(result.ratedPower));
    const panelType = result.panelType.toLowerCase(); if (["monofacial","bifacial","thin-film","flexible","other"].includes(panelType)) setField("panelType", panelType);
    setField("maximumPowerVoltageV", numberFrom(result.maximumPowerVoltage)); setField("maximumPowerCurrentA", numberFrom(result.maximumPowerCurrent)); setField("openCircuitVoltageV", numberFrom(result.openCircuitVoltage)); setField("shortCircuitCurrentA", numberFrom(result.shortCircuitCurrent)); setField("maximumSystemVoltageV", numberFrom(result.maximumSystemVoltage)); setField("nominalOperatingCellTempC", numberFrom(result.nominalOperatingCellTemperature)); setField("maximumSeriesFuseA", numberFrom(result.maximumSeriesFuseRating));
    const extra = [["Power tolerance",result.powerTolerance],["Module efficiency",result.moduleEfficiency],["Temperature coefficient Pmax",result.temperatureCoefficientPmax],["Temperature coefficient Voc",result.temperatureCoefficientVoc],["Temperature coefficient Isc",result.temperatureCoefficientIsc],["Dimensions",result.dimensions],["Weight",result.weight],...result.otherSpecifications.map((item) => [item.label,item.value])].filter(([,value]) => value).map(([label,value]) => `${label}: ${value}`).join("\n");
    if (extra) setField("specifications", extra);
  }
  async function analyze(file?: File) { if (!file) return; setAnalyzing(true); setError(""); setExtraction(undefined); const body = new FormData(); body.set("file", file); body.set("projectId", systemId); try { const response = await fetch("/api/equipment/analyze-label", { method: "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not read the panel label"); setExtraction(result.extraction); setPhotoPath(result.photoPath); applyExtraction(result.extraction); } catch (problem) { setError(problem instanceof Error ? problem.message : "Could not read the panel label"); } finally { setAnalyzing(false); } }
  async function save(form: FormData) {
    setSaving(true); setError("");
    const payload = { projectId: systemId, name: form.get("name"), manufacturer: form.get("manufacturer") || undefined, panelModel: form.get("panelModel") || undefined, panelType: form.get("panelType") || undefined, supplier: form.get("supplier") || undefined, purchasedOn: form.get("purchasedOn") || undefined, installedOn: form.get("installedOn") || undefined, maximumPowerVoltageV: optionalNumber(form,"maximumPowerVoltageV"), maximumPowerCurrentA: optionalNumber(form,"maximumPowerCurrentA"), openCircuitVoltageV: optionalNumber(form,"openCircuitVoltageV"), shortCircuitCurrentA: optionalNumber(form,"shortCircuitCurrentA"), maximumSystemVoltageV: optionalNumber(form,"maximumSystemVoltageV"), nominalOperatingCellTempC: optionalNumber(form,"nominalOperatingCellTempC"), maximumSeriesFuseA: optionalNumber(form,"maximumSeriesFuseA"), labelPhotoPath: photoPath || undefined, panelWatts: optionalNumber(form,"panelWatts"), panelCount: optionalNumber(form,"panelCount"), orientationDegrees: optionalNumber(form,"orientationDegrees"), tiltDegrees: optionalNumber(form,"tiltDegrees"), cableSizeMm2: optionalNumber(form,"cableSizeMm2"), cableLengthM: optionalNumber(form,"cableLengthM"), connectorType: form.get("connectorType") || undefined, breakerDetails: form.get("breakerDetails") || undefined, isolatorDetails: form.get("isolatorDetails") || undefined, combinerDetails: form.get("combinerDetails") || undefined, installationNotes: form.get("installationNotes") || undefined, specifications: parseSpecs(form.get("specifications")) };
    try { const response = await fetch(string ? `/api/pv-arrays/${string.id}` : "/api/pv-arrays", { method: string ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not save PV string"); router.push(back); router.refresh(); }
    catch (problem) { setError(problem instanceof Error ? problem.message : "Could not save PV string"); }
    finally { setSaving(false); }
  }
  async function remove() { if (!string || !window.confirm(`Remove ${string.name} from ${systemName}? This cannot be undone.`)) return; const response = await fetch(`/api/pv-arrays/${string.id}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not remove PV string"); return; } router.push(back); router.refresh(); }

  return <main className="min-h-screen bg-[#f4f6f1] px-5 py-8 md:px-10"><div className="mx-auto max-w-3xl">
    <div className="flex items-center justify-between gap-4"><Link href={back} className="inline-flex items-center gap-2 text-xs font-bold text-brand"><ArrowLeft size={15}/>Back to system overview</Link><Link href={`${back}?view=wattson`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#213c30] px-4 text-xs font-bold text-white"><Zap size={14}/>Ask Wattson</Link></div>
    <div className="my-7 flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-brand text-white"><Sun size={22}/></span><div><div className="eyebrow">PV string</div><h1 className="mt-2 font-display text-3xl font-extrabold tracking-[-.04em]">{string?.name ?? "Add PV string"}</h1><p className="mt-2 text-sm text-muted">One independently documented string feeding {systemName}.</p></div></div>
    <form ref={formRef} action={save} className="space-y-4">
      <label className="flex cursor-pointer items-center gap-4 rounded-2xl border border-dashed border-[#9db1a2] bg-[#f5f8f2] p-4"><span className="grid size-11 place-items-center rounded-xl bg-white text-brand"><Camera size={20}/></span><span className="flex-1"><strong className="block text-xs">Show Wattson the panel label</strong><span className="mt-1 block text-[10px] text-muted">Wattson will prefill visible nameplate values for review. Nothing is saved until you confirm.</span></span>{analyzing ? <LoaderCircle className="animate-spin text-brand" size={19}/> : <ScanLine className="text-brand" size={19}/>}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" disabled={analyzing} onChange={(event) => void analyze(event.target.files?.[0])}/></label>
      {extraction && <div className="rounded-xl border border-line bg-[#f7f9f5] p-3 text-[10px]"><div className="flex items-center justify-between"><strong>Panel label values added for review</strong><span className="uppercase text-brand">{extraction.confidence} confidence</span></div>{extraction.warnings.length > 0 && <p className="mt-2 text-[#8b6512]">{extraction.warnings.join(" ")}</p>}{extraction.unreadableFields.length > 0 && <p className="mt-1 text-muted">Could not read: {extraction.unreadableFields.join(", ")}</p>}</div>}
      <section className="card p-6"><div className="eyebrow">Panels in this string</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="String name" help="Use PV1, PV2, East roof, Shed roof, etc."><input name="name" required defaultValue={string?.name ?? "PV1"} className="field"/></Field><Field label="Panel construction"><select name="panelType" defaultValue={string?.panelType ?? "unknown"} className="field"><option value="unknown">Not confirmed</option><option value="monofacial">Monofacial</option><option value="bifacial">Bifacial</option><option value="thin-film">Thin-film</option><option value="flexible">Flexible</option><option value="other">Other</option></select></Field><Field label="Panel manufacturer"><input name="manufacturer" defaultValue={string?.manufacturer} className="field"/></Field><Field label="Panel model"><input name="panelModel" defaultValue={string?.panelModel} className="field"/></Field><Field label="Wattage per panel"><input name="panelWatts" type="number" step="any" defaultValue={string?.panelWatts} className="field"/></Field><Field label="Panels in this string"><input name="panelCount" type="number" min="1" defaultValue={string?.panelCount} className="field"/></Field></div></section>

      <details className="card group p-6"><summary className="cursor-pointer list-none text-sm font-bold">Panel electrical nameplate <span className="float-right text-brand group-open:rotate-45">+</span></summary><p className="mt-2 text-[10px] text-muted">Values below are for one panel. PVIntell can later calculate the string totals from the panel count.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Maximum power voltage — Vmp (V)"><input name="maximumPowerVoltageV" type="number" step="any" defaultValue={string?.maximumPowerVoltageV} className="field"/></Field><Field label="Maximum power current — Imp (A)"><input name="maximumPowerCurrentA" type="number" step="any" defaultValue={string?.maximumPowerCurrentA} className="field"/></Field><Field label="Open-circuit voltage — Voc (V)"><input name="openCircuitVoltageV" type="number" step="any" defaultValue={string?.openCircuitVoltageV} className="field"/></Field><Field label="Short-circuit current — Isc (A)"><input name="shortCircuitCurrentA" type="number" step="any" defaultValue={string?.shortCircuitCurrentA} className="field"/></Field><Field label="Maximum system voltage (V)"><input name="maximumSystemVoltageV" type="number" step="any" defaultValue={string?.maximumSystemVoltageV} className="field"/></Field><Field label="NOCT (°C)"><input name="nominalOperatingCellTempC" type="number" step="any" defaultValue={string?.nominalOperatingCellTempC} className="field"/></Field><Field label="Maximum series fuse (A)"><input name="maximumSeriesFuseA" type="number" step="any" defaultValue={string?.maximumSeriesFuseA} className="field"/></Field></div></details>

      <details className="card group p-6"><summary className="cursor-pointer list-none text-sm font-bold">Purchase and installation <span className="float-right text-brand group-open:rotate-45">+</span></summary><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Purchased from"><input name="supplier" defaultValue={string?.supplier} className="field" placeholder="Company or previous owner"/></Field><Field label="Purchase date"><input name="purchasedOn" type="date" defaultValue={string?.purchasedOn} className="field"/></Field><Field label="Installation date"><input name="installedOn" type="date" defaultValue={string?.installedOn} className="field"/></Field><Field label="Direction / azimuth (°)"><input name="orientationDegrees" type="number" min="0" max="360" step="any" defaultValue={string?.orientationDegrees} className="field"/></Field><Field label="Panel tilt (°)"><input name="tiltDegrees" type="number" min="0" max="90" step="any" defaultValue={string?.tiltDegrees} className="field"/></Field></div></details>

      <details className="card group p-6"><summary className="cursor-pointer list-none text-sm font-bold">Cabling and protection <span className="float-right text-brand group-open:rotate-45">+</span></summary><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="PV cable size (mm²)"><input name="cableSizeMm2" type="number" step="any" defaultValue={string?.cableSizeMm2} className="field"/></Field><Field label="One-way cable length (m)"><input name="cableLengthM" type="number" step="any" defaultValue={string?.cableLengthM} className="field"/></Field><Field label="Connector type"><input name="connectorType" defaultValue={string?.connectorType} className="field"/></Field><Field label="Breaker / fuse"><input name="breakerDetails" defaultValue={string?.breakerDetails} className="field"/></Field><Field label="Isolator / shutoff"><input name="isolatorDetails" defaultValue={string?.isolatorDetails} className="field"/></Field><Field label="Combiner box"><input name="combinerDetails" defaultValue={string?.combinerDetails} className="field"/></Field></div></details>

      <details className="card group p-6"><summary className="cursor-pointer list-none text-sm font-bold">Advanced values and notes <span className="float-right text-brand group-open:rotate-45">+</span></summary><div className="mt-5 space-y-4"><Field label="Other technical values" help="One Name: Value per line, such as Voc: 247 V."><textarea name="specifications" rows={7} defaultValue={Object.entries(string?.specifications ?? {}).map(([key,value]) => `${key}: ${value}`).join("\n")} className="field py-3 font-mono"/></Field><Field label="Installation notes"><textarea name="installationNotes" rows={5} defaultValue={string?.installationNotes} className="field py-3"/></Field></div></details>

      {error && <div className="rounded-xl bg-[#fff0eb] p-3 text-xs text-[#913e31]">{error}</div>}<div className="flex gap-3">{string && <button type="button" onClick={() => void remove()} className="grid size-11 place-items-center rounded-xl border border-[#e3b9b1] text-[#9b4033]"><Trash2 size={16}/></button>}<button disabled={saving} className="h-11 flex-1 rounded-xl bg-brand text-xs font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Save PV string"}</button></div>
    </form>
  </div></main>;
}
