"use client";

import { BatteryCharging, ClipboardCheck, CloudSun, MapPin, Package, PlugZap, Settings2, Sun, Wrench, X, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { ComponentSpec, Site, SiteEquipment, SystemSummary } from "@/domain/models";
import { useSolarWeather } from "@/weather/use-solar-weather";
const iconFor = (type: string) => type === "inverter" ? PlugZap : type === "battery" ? BatteryCharging : type === "panel" || type === "pv_string" ? Sun : Package;

export function SiteOverview({ site, systems, activeSystemId, components, equipment, solarArrayKw, onAddSystem, onOpenSystem, onOpenWeather, onOpenEquipment }: { site: Site; systems: SystemSummary[]; activeSystemId: string; components: ComponentSpec[]; equipment: SiteEquipment[]; solarArrayKw: number; onAddSystem: () => void; onOpenSystem: () => void; onOpenWeather: () => void; onOpenEquipment: (id: string) => void }) {
  const { data: weatherData, error: weatherError, hasLocation } = useSolarWeather(site);
  const router = useRouter(); const [editing, setEditing] = useState<ComponentSpec>(); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const weather = useMemo(() => weatherData?.hours ?? [], [weatherData]);
  const forecast = useMemo(() => { const next = weather.slice(0, 24); return { current: next[0], yieldKwh: next.reduce((sum, hour) => sum + Math.max(0, hour.irradiance ?? 0) / 1000, 0) * solarArrayKw * 0.8 }; }, [solarArrayKw, weather]);
  async function saveComponent(formData: FormData) { if (!editing) return; setSaving(true); setError(""); const specs = Object.fromEntries(String(formData.get("specifications") ?? "").split("\n").map((line) => line.split(":")).filter((parts) => parts.length > 1 && parts[0].trim()).map(([key, ...rest]) => [key.trim(), rest.join(":").trim()])); try { const response = await fetch(`/api/components/${editing.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: activeSystemId, type: formData.get("type"), name: formData.get("name"), manufacturer: formData.get("manufacturer"), model: formData.get("model"), quantity: Number(formData.get("quantity")), installationLocation: formData.get("installationLocation"), specifications: specs }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not update component"); setEditing(undefined); router.refresh(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Could not update component"); } finally { setSaving(false); } }
  const siteSystems = systems.filter((system) => system.siteId === site.id);

  return <div className="animate-rise space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="eyebrow">Site overview</div><h1 className="mt-3 font-display text-3xl font-extrabold tracking-[-.05em] md:text-[38px]">{site.name}</h1><p className="mt-2 flex items-center gap-2 text-sm text-muted"><MapPin size={14}/>{site.location}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => router.push(`/sites/${site.id}/discovery`)} className="flex h-11 items-center gap-2 rounded-xl border border-line bg-white px-5 text-xs font-bold text-brand"><ClipboardCheck size={15}/>Review discovery</button><button onClick={onOpenWeather} className="flex h-11 items-center gap-2 rounded-xl border border-line bg-white px-5 text-xs font-bold"><Settings2 size={15}/>Edit site and weather location</button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Sun} label="Solar now" value={forecast.current?.irradiance != null ? `${forecast.current.irradiance.toFixed(0)} W/m²` : "—"} detail={weatherError || (hasLocation ? "Current irradiance" : "Set the site location")}/><Metric icon={CloudSun} label="Cloud cover" value={forecast.current?.cloudCover != null ? `${forecast.current.cloudCover.toFixed(0)}%` : "—"} detail={forecast.current?.temperature != null ? `${forecast.current.temperature.toFixed(1)} °C at site` : "Weather-backed monitoring"}/><Metric icon={Zap} label="Expected solar · 24 h" value={weather.length ? `${forecast.yieldKwh.toFixed(1)} kWh` : "—"} detail={`${solarArrayKw.toFixed(1)} kW selected system`}/><Metric icon={Wrench} label="Systems at site" value={String(siteSystems.length)} detail={`${siteSystems.filter((system) => ["build", "commission"].includes(system.phase)).length} being built or commissioned`}/></div>
    <section><div className="flex items-end justify-between"><div><div className="eyebrow">Technical records</div><h2 className="mt-2 text-xl font-extrabold">As-built records at this Site</h2></div><button onClick={onAddSystem} className="rounded-xl bg-brand px-4 py-2.5 text-xs font-bold text-white">Start a new independent Site</button></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{siteSystems.map((system) => <article key={system.id} className={`card p-5 ${system.id === activeSystemId ? "ring-2 ring-[#8db4d8]" : ""}`}><div className="flex justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#eaf2fb] text-brand"><Zap size={18}/></span><span className="rounded-full bg-[#edf2f7] px-2 py-1 text-[9px] font-bold uppercase">{system.phase}</span></div><h3 className="mt-4 font-bold">{system.name}</h3><p className="mt-1 text-[10px] uppercase text-muted">{system.projectType}</p>{system.id === activeSystemId ? <button onClick={onOpenSystem} className="mt-4 w-full rounded-xl bg-brand py-2.5 text-[10px] font-bold text-white">Open as-built record</button> : <a href={`/sites/${site.id}?system=${system.id}`} className="mt-4 grid h-9 place-items-center rounded-xl border border-line text-[10px] font-bold">Select technical record</a>}</article>)}</div></section>
    <section><div className="flex items-end justify-between"><div><div className="eyebrow">Equipment</div><h2 className="mt-2 text-xl font-extrabold">Current components and site inventory</h2></div><button onClick={() => equipment[0] ? onOpenEquipment(equipment[0].id) : onOpenEquipment("")} className="text-xs font-bold text-brand">Open site inventory →</button></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{components.map((component) => { const Icon = iconFor(component.kind); return <button key={component.id} onClick={() => setEditing(component)} className="card p-5 text-left hover:border-[#7ea8ce]"><div className="flex justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#eaf2fb] text-brand"><Icon size={18}/></span><span className="text-[9px] font-bold uppercase text-muted">{component.status}</span></div><h3 className="mt-4 text-sm font-bold">{component.name}</h3><p className="mt-1 text-[10px] text-muted">{[component.manufacturer, component.model].filter(Boolean).join(" • ") || component.kind} · Qty {component.quantity}</p><span className="mt-4 block text-[10px] font-bold text-brand">View or edit specifications →</span></button>; })}{equipment.map((item) => { const Icon = iconFor(item.type); return <button key={item.id} onClick={() => onOpenEquipment(item.id)} className="card p-5 text-left hover:border-[#7ea8ce]"><span className="grid size-10 place-items-center rounded-xl bg-[#fff4d6] text-[#8b6512]"><Icon size={18}/></span><h3 className="mt-4 text-sm font-bold">{item.name}</h3><p className="mt-1 text-[10px] text-muted">Site inventory · {[item.manufacturer, item.model].filter(Boolean).join(" • ") || item.type}</p><span className="mt-4 block text-[10px] font-bold text-brand">View or edit specifications →</span></button>; })}{!components.length && !equipment.length && <div className="card p-6 text-sm text-muted">No equipment recorded yet. Open Site equipment to add it manually or scan a rating label.</div>}</div></section>
    {editing && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#0b2740]/45 p-5 backdrop-blur-sm"><form action={saveComponent} className="card my-8 w-full max-w-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><div className="eyebrow">System component</div><h2 className="mt-2 text-xl font-extrabold">Current specifications</h2></div><button type="button" onClick={() => setEditing(undefined)}><X size={18}/></button></div>{error && <div className="mt-4 rounded-xl bg-[#fff0eb] p-3 text-xs text-[#913e31]">{error}</div>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Type<select name="type" defaultValue={editing.kind} className="field">{["panel","pv_string","battery","inverter","generator","protection","meter"].map((type) => <option key={type} value={type}>{type.replace("_", " ")}</option>)}</select></label><label className="text-xs font-bold">Name<input name="name" defaultValue={editing.name} className="field" required/></label><label className="text-xs font-bold">Manufacturer<input name="manufacturer" defaultValue={editing.manufacturer} className="field"/></label><label className="text-xs font-bold">Model<input name="model" defaultValue={editing.model} className="field"/></label><label className="text-xs font-bold">Quantity<input name="quantity" type="number" min="1" defaultValue={editing.quantity} className="field"/></label><label className="text-xs font-bold">Installed location<input name="installationLocation" defaultValue={editing.location} className="field"/></label><label className="text-xs font-bold sm:col-span-2">Specifications <span className="font-normal text-muted">(one Name: Value per line)</span><textarea name="specifications" rows={7} defaultValue={Object.entries(editing.specs).map(([key, value]) => `${key}: ${value}`).join("\n")} className="field py-3 font-mono"/></label></div><button disabled={saving} className="mt-6 h-11 w-full rounded-xl bg-brand text-xs font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Save component specifications"}</button></form></div>}
  </div>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Sun; label: string; value: string; detail: string }) { return <div className="card flex min-h-36 flex-col justify-between p-5"><div className="flex justify-between"><span className="text-xs font-semibold text-muted">{label}</span><span className="grid size-8 place-items-center rounded-xl bg-[#e6f0fa] text-brand"><Icon size={16}/></span></div><div><div className="font-display text-[26px] font-extrabold">{value}</div><div className="text-[10px] text-muted">{detail}</div></div></div>; }
