"use client";

import { CloudRain, LoaderCircle, LocateFixed, MapPin, Wind } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import type { Site } from "@/domain/models";
import { formatRainfall, formatTemperature, formatWindSpeed, useUnitPreferences, type UnitPreferences } from "@/preferences/units";
import { fiveDaySolarOutlook, latestForecastHour, type SolarArrayForecastInput, type SolarWeatherHour } from "@/weather/forecast";
import { useForecastNow, useSolarWeather } from "@/weather/use-solar-weather";

const number = (value: number | null | undefined, digits = 0) => typeof value === "number" ? value.toFixed(digits) : "—";

export function SolarWeather({ site, solarArrayKw, solarArrays = [] }: { site: Site; solarArrayKw: number; solarArrays?: SolarArrayForecastInput[] }) {
  const { data, loading, error: weatherError, hasLocation } = useSolarWeather(site);
  const forecastNow = useForecastNow();
  const { preferences: units } = useUnitPreferences();
  const router = useRouter(); const [error, setError] = useState(""); const [editing, setEditing] = useState(!hasLocation); const [locating, setLocating] = useState(false); const [saving, setSaving] = useState(false);
  const displayedError = error || weatherError;
  const timezone = data?.site.timezone || site.timezone;
  const forecastInput = solarArrays.length ? solarArrays : solarArrayKw;
  const days = useMemo(() => fiveDaySolarOutlook(
    data?.hours ?? [],
    timezone,
    forecastInput,
    forecastNow,
    { latitude: site.latitude, longitude: site.longitude, timezone },
  ), [data, forecastInput, forecastNow, site.latitude, site.longitude, timezone]);
  const outlook = days[0];
  const current = outlook ? latestForecastHour(outlook.hours, forecastNow, { latitude: site.latitude, longitude: site.longitude, timezone }) : undefined;
  const daylightHours = outlook?.hours.filter((hour) => (hour.irradiance ?? 0) > 0) ?? [];
  const forecastBasisDetail = outlook?.forecastBasis === "array-geometry" ? "recorded panel angle" : "basic horizontal estimate";

  async function saveLocation(formData: FormData) { setSaving(true); setError(""); try { const response = await fetch(`/api/sites/${site.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ location: formData.get("location"), latitude: Number(formData.get("latitude")), longitude: Number(formData.get("longitude")), timezone: formData.get("timezone"), locationSource: formData.get("locationSource") || "manual" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not save location"); setEditing(false); router.refresh(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Could not save location"); } finally { setSaving(false); } }
  function useDeviceLocation() { setLocating(true); navigator.geolocation.getCurrentPosition((position) => { const form = document.getElementById("site-location-form") as HTMLFormElement | null; const lat = form?.elements.namedItem("latitude"); const lon = form?.elements.namedItem("longitude"); const source = form?.elements.namedItem("locationSource"); if (lat instanceof HTMLInputElement) lat.value = String(position.coords.latitude); if (lon instanceof HTMLInputElement) lon.value = String(position.coords.longitude); if (source instanceof HTMLInputElement) source.value = "device"; setLocating(false); }, () => { setError("Location access was not available. Enter the coordinates manually."); setLocating(false); }, { enableHighAccuracy: true, timeout: 12_000 }); }

  return <div className="animate-rise space-y-4"><div className="overflow-hidden rounded-2xl bg-cover bg-center p-5 text-white shadow-[0_12px_30px_rgba(12,39,65,.16)] sm:p-6" style={{ backgroundImage: "linear-gradient(90deg, rgba(8,35,58,.95), rgba(8,35,58,.62)), url('/backgrounds/hpgruesen-sauerland-2873920_1920.jpg')" }}><div><div className="eyebrow text-[#ffd44f]">Solar weather</div><p className="mt-2 max-w-2xl text-xs font-medium leading-5 text-white/90">A site-specific solar outlook using irradiance and cloud data. Weather also informs sensible maintenance and safe-work timing.</p></div></div>
    {displayedError && <div className="rounded-2xl border border-[#edc7bc] bg-[#fff0eb] p-4 text-xs text-[#913e31]">{displayedError}</div>}
    {!hasLocation ? <div className="card grid min-h-72 place-items-center p-8 text-center"><div><MapPin className="mx-auto text-brand"/><h2 className="mt-4 text-lg font-bold">Set this site’s coordinates</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-muted">PVIntell needs a latitude, longitude and timezone so forecasts follow this property rather than your current device.</p><button onClick={() => setEditing(true)} className="mt-5 rounded-xl bg-brand px-5 py-3 text-xs font-bold text-white">Set site location</button></div></div> : loading && !data ? <div className="card grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-brand"/></div> : data && outlook ? <>
      <div className="grid grid-cols-2 gap-1.5 sm:gap-4 xl:grid-cols-6"><WeatherMetric emoji={<SolarYieldCurve/>} label="Expected solar today" value={`${number(outlook.expectedKwh, 1)} kWh`} detail={`${solarArrayKw.toFixed(1)} kW array · ${forecastBasisDetail}`}/><WeatherMetric emoji={<SolarYieldCurve/>} label="Solar remaining today" value={`${number(outlook.remainingKwh, 1)} kWh`} detail="Forecast energy still available"/><WeatherMetric emoji={forecastWeatherEmoji(current)} label="Irradiance now" value={`${number(current?.irradiance)} W/m²`} detail={`${number(current?.cloudCover)}% cloud cover`}/><WeatherMetric emoji={forecastWeatherEmoji(outlook.peak)} label="Best solar hour" value={outlook.peak ? new Intl.DateTimeFormat(undefined, { hour: "numeric", timeZone: timezone }).format(new Date(outlook.peak.time)) : "—"} detail={`${number(outlook.peak?.irradiance)} W/m² forecast`}/><WeatherMetric emoji="🌧️" label="Rain today" value={formatRainfall(outlook.rainMm, units)} detail={`${formatTemperature(current?.temperature, units, 1)} now`}/><WeatherMetric emoji="💨" label="Wind today" value={formatWindSpeed(outlook.maxWind, units)} detail={current?.windSpeed != null ? `${formatWindSpeed(current.windSpeed, units)} right now` : "Peak forecast speed"}/></div>
      <SolarCurves days={days} timezone={timezone} arrayKw={solarArrayKw} units={units}/>
      <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line p-5"><div><div className="eyebrow">Hourly detail</div><h2 className="mt-2 text-lg font-extrabold">Today’s solar window by hour</h2></div><span className="text-[9px] text-muted">Updated {new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit", timeZone: timezone, timeZoneName: "short" }).format(new Date(data.fetchedAt))}</span></div><div className="thin-scrollbar flex gap-2 overflow-x-auto p-5">{daylightHours.map((hour) => { const height = Math.max(4, Math.min(100, (hour.irradiance ?? 0) / 10)); return <div key={hour.time} className="min-w-20 rounded-2xl border border-line bg-white p-3 text-center"><div className="text-[9px] font-bold text-muted">{new Intl.DateTimeFormat(undefined, { hour: "numeric", timeZone: timezone }).format(new Date(hour.time))}</div><div className="mx-auto mt-3 flex h-20 w-7 items-end rounded-full bg-[#eef3f8] p-1"><div className="w-full rounded-full bg-[linear-gradient(#f6c945,#e0a800)]" style={{ height: `${height}%` }}/></div><strong className="mt-2 block text-[10px]">{number(hour.irradiance)} W/m²</strong><span className="mt-1 block text-[9px] text-muted">{number(hour.cloudCover)}% cloud</span></div>; })}</div></section>
      <section className="grid gap-4 lg:grid-cols-2"><div className="card p-5"><div className="flex items-center gap-2"><CloudRain size={17} className="text-brand"/><div className="eyebrow">Maintenance context</div></div><h2 className="mt-3 text-base font-bold">{outlook.rainMm >= 3 ? "Rain is likely today" : "A mostly dry day is forecast"}</h2><p className="mt-2 text-xs leading-5 text-muted">{outlook.rainMm >= 3 ? "Rain may remove loose dust, so a cleaning decision can wait until output is checked afterward. Rain does not replace inspection for bird droppings, lichen or stubborn soiling." : "If monitored output is below its weather-adjusted baseline, inspect for dirt or shading before recommending cleaning. PVIntell will combine this with performance history as monitoring is connected."}</p></div><div className="card p-5"><div className="flex items-center gap-2"><Wind size={17} className="text-brand"/><div className="eyebrow">Work safety detail</div></div><h2 className="mt-3 text-base font-bold">Peak wind {formatWindSpeed(outlook.maxWind, units)}</h2><p className="mt-2 text-xs leading-5 text-muted">Wind remains a secondary detail. Wet, windy or otherwise unsafe conditions should defer roof inspection or maintenance, regardless of the solar forecast.</p></div></section>
    </> : null}
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0b2740]/45 p-5 backdrop-blur-sm"><form id="site-location-form" action={saveLocation} className="card w-full max-w-lg bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><div className="eyebrow">Site settings</div><h2 className="mt-2 text-xl font-extrabold">Solar forecast location</h2></div><button type="button" onClick={() => setEditing(false)} className="grid size-8 place-items-center rounded-lg hover:bg-[#eef3f8]">×</button></div><button type="button" onClick={useDeviceLocation} disabled={locating} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-line py-3 text-xs font-bold"><LocateFixed size={15}/>{locating ? "Finding location…" : "Use this device’s location"}</button><input type="hidden" name="locationSource" defaultValue="manual"/><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Location name<input name="location" required defaultValue={site.location === "Location not set" ? "" : site.location} className="field" placeholder="e.g. Rotorua, New Zealand"/></label><label className="text-xs font-bold">Latitude<input name="latitude" type="number" step="any" required defaultValue={site.latitude} className="field"/></label><label className="text-xs font-bold">Longitude<input name="longitude" type="number" step="any" required defaultValue={site.longitude} className="field"/></label><label className="text-xs font-bold sm:col-span-2">Timezone<input name="timezone" required defaultValue={site.timezone === "UTC" ? Intl.DateTimeFormat().resolvedOptions().timeZone : site.timezone} className="field" placeholder="Pacific/Auckland"/></label></div><button disabled={saving} className="mt-6 h-11 w-full rounded-xl bg-brand text-xs font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Save site location"}</button></form></div>}
  </div>;
}

function SolarYieldCurve() { return <svg viewBox="0 0 20 20" className="size-[18px] text-[#d99500]" fill="none" aria-hidden="true"><path d="M2 16C4.4 16 5.1 5 10 5s5.6 11 8 11H2Z" fill="currentColor" opacity=".22"/><path d="M2 16c2.4 0 3.1-11 8-11s5.6 11 8 11M2 16h16" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>; }

function forecastWeatherEmoji(hour?: SolarWeatherHour) {
  if (!hour) return "—";
  if ((hour.precipitation ?? 0) >= 0.2) return "🌧️";
  if ((hour.cloudCover ?? 0) >= 75) return "☁️";
  if ((hour.cloudCover ?? 0) >= 30) return "🌤️";
  return "☀️";
}

function WeatherMetric({ emoji, label, value, detail }: { emoji: ReactNode; label: string; value: string; detail: string }) { return <div className="card flex min-w-0 flex-col justify-between overflow-hidden p-2 sm:min-h-24 sm:p-3"><div className="truncate text-[8px] font-semibold leading-3 text-muted sm:text-[10px] sm:leading-normal">{label}</div><div className="mt-1 min-w-0 sm:mt-2"><div className="flex items-center gap-1.5 sm:gap-2"><span aria-hidden="true" className="shrink-0 text-sm leading-none sm:text-xl">{emoji}</span><div className="break-words font-display text-sm font-extrabold tracking-[-.04em] sm:text-xl">{value}</div></div><div className="mt-1 hidden text-[9px] leading-4 text-muted sm:block">{detail}</div></div></div>; }

function forecastDayEmoji(day: ReturnType<typeof fiveDaySolarOutlook>[number]) {
  return day.rainMm >= 1 ? "🌧️" : day.maxCloudCover >= 75 ? "☁️" : day.maxCloudCover >= 30 ? "🌤️" : "☀️";
}

function SolarCurves({ days, timezone, arrayKw, units }: { days: ReturnType<typeof fiveDaySolarOutlook>; timezone: string; arrayKw: number; units: UnitPreferences }) {
  return <section className="card overflow-hidden">
    <div className="flex flex-col justify-between gap-1.5 border-b border-line p-3 sm:flex-row sm:items-end sm:p-4">
      <div><div className="eyebrow">Solar curves · five days</div><h2 className="mt-1.5 text-base font-extrabold">Available sunlight by day</h2><p className="mt-0.5 text-[9px] text-muted">Swipe or scroll sideways to compare each forecast day.</p></div>
      <span className="text-[9px] font-bold text-muted">{days.length} forecast days →</span>
    </div>
    <div className="thin-scrollbar flex snap-x snap-mandatory overflow-x-auto overscroll-x-contain" role="region" aria-label="Five-day solar curve forecast" tabIndex={0}>
      {days.map((day) => <SolarCurveDay key={day.dateKey} day={day} timezone={timezone} arrayKw={arrayKw} units={units}/>)}
    </div>
  </section>;
}

function SolarCurveDay({ day, timezone, arrayKw, units }: { day: ReturnType<typeof fiveDaySolarOutlook>[number]; timezone: string; arrayKw: number; units: UnitPreferences }) {
  const hours = day.hours.filter((hour) => (hour.irradiance ?? 0) > 0);
  const width = 1000; const height = 270; const left = 38; const right = 24; const top = 28; const baseline = 218;
  const peakFlux = Math.max(0, ...hours.map((hour) => hour.irradiance ?? 0));
  const maxFlux = Math.max(100, peakFlux);
  const points = hours.map((hour, index) => ({ x: left + index / Math.max(1, hours.length - 1) * (width - left - right), y: baseline - Math.max(0, hour.irradiance ?? 0) / maxFlux * (baseline - top), hour }));
  const curve = points.length ? points.slice(1).reduce((path, point, index) => { const previous = points[index]; const midpointX = (previous.x + point.x) / 2; const midpointY = (previous.y + point.y) / 2; return `${path} Q ${previous.x} ${previous.y} ${midpointX} ${midpointY}`; }, `M ${points[0].x} ${points[0].y}`) + ` T ${points.at(-1)?.x} ${points.at(-1)?.y}` : "";
  const area = points.length ? `M ${points[0].x} ${baseline} L ${points[0].x} ${points[0].y} ${curve.replace(/^M [\d.]+ [\d.]+/, "")} L ${points.at(-1)?.x} ${baseline} Z` : "";
  const peak = points.reduce((best, point) => (point.hour.irradiance ?? 0) > (best?.hour.irradiance ?? -1) ? point : best, undefined as typeof points[number] | undefined);
  const dayLabel = day.hours[0] ? new Intl.DateTimeFormat(undefined, { weekday: "long", day: "numeric", month: "short", timeZone: timezone }).format(new Date(day.hours[0].time)) : day.dateKey;
  if (hours.length < 2) return <article className="grid min-h-72 min-w-full snap-start place-items-center border-r border-line p-6 text-center"><div><strong>{dayLabel}</strong><p className="mt-3 text-sm text-muted">A complete daylight curve is not available for this forecast day.</p></div></article>;
  const labelEvery = Math.max(1, Math.round(hours.length / 6));
  const gradientId = `solar-curve-fill-${day.dateKey}`;
  return <article className="min-w-full snap-start border-r border-line last:border-r-0"><div className="flex items-center justify-between gap-3 border-b border-line px-3 py-2 sm:px-4"><div><h3 className="text-sm font-extrabold">{dayLabel}</h3><span className="text-[8px] text-muted">{arrayKw.toFixed(1)} kW configured array</span></div><div className="flex shrink-0 items-center gap-2 text-right"><span aria-hidden="true" className="text-xl leading-none">{forecastDayEmoji(day)}</span><div><strong className="block text-sm">{day.expectedKwh.toFixed(1)} kWh expected</strong><span className="block text-[8px] text-muted">{formatTemperature(day.minTemperature, units)}–{formatTemperature(day.maxTemperature, units)} · {formatRainfall(day.rainMm, units)} rain</span><span className="block text-[8px] text-muted">{formatWindSpeed(day.maxWind, units)} wind</span></div></div></div><div className="relative bg-[linear-gradient(180deg,#fffdf5,#f5f8fc)] px-2 py-2 sm:px-3"><svg viewBox={`0 0 ${width} ${height}`} className="h-[125px] w-full sm:h-[155px]" role="img" aria-label={`Solar irradiance curve for ${dayLabel}`}><defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#f6c945" stopOpacity=".65"/><stop offset="1" stopColor="#f6c945" stopOpacity=".05"/></linearGradient></defs><line x1={left} y1={baseline} x2={width-right} y2={baseline} stroke="#cdd8e3"/><line x1={left} y1={top} x2={width-right} y2={top} stroke="#e4eaf0" strokeDasharray="5 7"/><text x={left} y={top-8} fill="#65758b" fontSize="11">{Math.round(maxFlux)} W/m²</text><path d={area} fill={`url(#${gradientId})`}/><path d={curve} fill="none" stroke="#d8a000" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/>{peak && <><line x1={peak.x} y1={peak.y} x2={peak.x} y2={baseline} stroke="#8ea6bc" strokeDasharray="5 6"/><circle cx={peak.x} cy={peak.y} r="7" fill="#f5d64e" stroke="#fff" strokeWidth="3"/></>}{points.map((point, index) => index % labelEvery === 0 || index === points.length - 1 ? <text key={point.hour.time} x={point.x} y={baseline+25} textAnchor={index === 0 ? "start" : index === points.length - 1 ? "end" : "middle"} fill="#647069" fontSize="11" fontWeight="600">{new Intl.DateTimeFormat(undefined, { hour: "numeric", timeZone: timezone }).format(new Date(point.hour.time))}</text> : null)}</svg>{arrayKw <= 0 && <div className="mx-3 mb-2 rounded-xl bg-[#fff5d9] px-3 py-2 text-[9px] text-[#765c1c]">The sunlight curve is available, but expected energy remains 0.0 kWh until this system’s PV array size is recorded.</div>}</div></article>;
}
