"use client";

import { Cloud, CloudRain, CloudSun, LoaderCircle, LocateFixed, MapPin, RefreshCw, Sun, Wind } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Site } from "@/domain/models";
import { formatRainfall, formatTemperature, formatWindSpeed, useUnitPreferences, type UnitPreferences } from "@/preferences/units";
import { fiveDaySolarOutlook, latestForecastHour, type SolarWeatherHour } from "@/weather/forecast";
import { useForecastNow, useSolarWeather } from "@/weather/use-solar-weather";

const number = (value: number | null | undefined, digits = 0) => typeof value === "number" ? value.toFixed(digits) : "—";

export function SolarWeather({ site, solarArrayKw }: { site: Site; solarArrayKw: number }) {
  const { data, loading, error: weatherError, hasLocation, loadDaily } = useSolarWeather(site);
  const forecastNow = useForecastNow();
  const { preferences: units } = useUnitPreferences();
  const router = useRouter(); const [error, setError] = useState(""); const [editing, setEditing] = useState(!hasLocation); const [locating, setLocating] = useState(false); const [saving, setSaving] = useState(false);
  const displayedError = error || weatherError;
  const timezone = data?.site.timezone || site.timezone;
  const days = useMemo(() => fiveDaySolarOutlook(data?.hours ?? [], timezone, solarArrayKw, forecastNow), [data, forecastNow, solarArrayKw, timezone]);
  const outlook = days[0];
  const current = outlook ? latestForecastHour(outlook.hours, forecastNow) : undefined;
  const daylightHours = outlook?.hours.filter((hour) => (hour.irradiance ?? 0) > 0) ?? [];

  async function saveLocation(formData: FormData) { setSaving(true); setError(""); try { const response = await fetch(`/api/sites/${site.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ location: formData.get("location"), latitude: Number(formData.get("latitude")), longitude: Number(formData.get("longitude")), timezone: formData.get("timezone"), locationSource: formData.get("locationSource") || "manual" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not save location"); setEditing(false); router.refresh(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Could not save location"); } finally { setSaving(false); } }
  function useDeviceLocation() { setLocating(true); navigator.geolocation.getCurrentPosition((position) => { const form = document.getElementById("site-location-form") as HTMLFormElement | null; const lat = form?.elements.namedItem("latitude"); const lon = form?.elements.namedItem("longitude"); const source = form?.elements.namedItem("locationSource"); if (lat instanceof HTMLInputElement) lat.value = String(position.coords.latitude); if (lon instanceof HTMLInputElement) lon.value = String(position.coords.longitude); if (source instanceof HTMLInputElement) source.value = "device"; setLocating(false); }, () => { setError("Location access was not available. Enter the coordinates manually."); setLocating(false); }, { enableHighAccuracy: true, timeout: 12_000 }); }

  return <div className="animate-rise space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="eyebrow">Solar weather</div><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">A site-specific solar outlook using irradiance and cloud data. Weather also informs sensible maintenance and safe-work timing.</p></div><div className="flex gap-2"><button onClick={() => setEditing(true)} className="flex h-10 items-center gap-2 rounded-xl border border-line bg-white px-4 text-[10px] font-bold"><MapPin size={14}/>Site location</button><button onClick={() => void loadDaily()} title="Uses today's cached forecast; renews after local midnight" disabled={loading || !hasLocation} className="grid size-10 place-items-center rounded-xl bg-brand text-white disabled:opacity-40"><RefreshCw size={15} className={loading ? "animate-spin" : ""}/></button></div></div>
    {displayedError && <div className="rounded-2xl border border-[#edc7bc] bg-[#fff0eb] p-4 text-xs text-[#913e31]">{displayedError}</div>}
    {!hasLocation ? <div className="card grid min-h-72 place-items-center p-8 text-center"><div><MapPin className="mx-auto text-brand"/><h2 className="mt-4 text-lg font-bold">Set this site’s coordinates</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-muted">PVIntell needs a latitude, longitude and timezone so forecasts follow this property rather than your current device.</p><button onClick={() => setEditing(true)} className="mt-5 rounded-xl bg-brand px-5 py-3 text-xs font-bold text-white">Set site location</button></div></div> : loading && !data ? <div className="card grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-brand"/></div> : data && outlook ? <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><WeatherMetric icon={Sun} label="Expected solar today" value={`${number(outlook.expectedKwh, 1)} kWh`} detail={`${solarArrayKw.toFixed(1)} kW array · 80% planning factor`}/><WeatherMetric icon={CloudSun} label="Solar remaining today" value={`${number(outlook.remainingKwh, 1)} kWh`} detail="Forecast energy still available"/><WeatherMetric icon={CloudSun} label="Irradiance now" value={`${number(current?.irradiance)} W/m²`} detail={`${number(current?.cloudCover)}% cloud cover`}/><WeatherMetric icon={Sun} label="Best solar hour" value={outlook.peak ? new Intl.DateTimeFormat(undefined, { hour: "numeric", timeZone: timezone }).format(new Date(outlook.peak.time)) : "—"} detail={`${number(outlook.peak?.irradiance)} W/m² forecast`}/><WeatherMetric icon={CloudRain} label="Rain today" value={formatRainfall(outlook.rainMm, units)} detail={`${formatTemperature(current?.temperature, units, 1)} now`}/></div>
      <section><div className="eyebrow">Five-day outlook</div><h2 className="mt-2 text-lg font-extrabold">Weather and available solar by day</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{days.map((day) => <ForecastDayCard key={day.dateKey} day={day} timezone={timezone} units={units}/>)}</div></section>
      <SolarCurve hours={daylightHours} dateKey={outlook.dateKey} timezone={timezone} expectedKwh={outlook.expectedKwh} arrayKw={solarArrayKw}/>
      <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line p-5"><div><div className="eyebrow">Hourly detail</div><h2 className="mt-2 text-lg font-extrabold">Today’s solar window by hour</h2></div><span className="text-[9px] text-muted">Updated {new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit", timeZone: timezone, timeZoneName: "short" }).format(new Date(data.fetchedAt))}</span></div><div className="thin-scrollbar flex gap-2 overflow-x-auto p-5">{daylightHours.map((hour) => { const height = Math.max(4, Math.min(100, (hour.irradiance ?? 0) / 10)); return <div key={hour.time} className="min-w-20 rounded-2xl border border-line bg-white p-3 text-center"><div className="text-[9px] font-bold text-muted">{new Intl.DateTimeFormat(undefined, { hour: "numeric", timeZone: timezone }).format(new Date(hour.time))}</div><div className="mx-auto mt-3 flex h-20 w-7 items-end rounded-full bg-[#eef3f8] p-1"><div className="w-full rounded-full bg-[linear-gradient(#f6c945,#e0a800)]" style={{ height: `${height}%` }}/></div><strong className="mt-2 block text-[10px]">{number(hour.irradiance)} W/m²</strong><span className="mt-1 block text-[9px] text-muted">{number(hour.cloudCover)}% cloud</span></div>; })}</div></section>
      <section className="grid gap-4 lg:grid-cols-2"><div className="card p-5"><div className="flex items-center gap-2"><CloudRain size={17} className="text-brand"/><div className="eyebrow">Maintenance context</div></div><h2 className="mt-3 text-base font-bold">{outlook.rainMm >= 3 ? "Rain is likely today" : "A mostly dry day is forecast"}</h2><p className="mt-2 text-xs leading-5 text-muted">{outlook.rainMm >= 3 ? "Rain may remove loose dust, so a cleaning decision can wait until output is checked afterward. Rain does not replace inspection for bird droppings, lichen or stubborn soiling." : "If monitored output is below its weather-adjusted baseline, inspect for dirt or shading before recommending cleaning. PVIntell will combine this with performance history as monitoring is connected."}</p></div><div className="card p-5"><div className="flex items-center gap-2"><Wind size={17} className="text-brand"/><div className="eyebrow">Work safety detail</div></div><h2 className="mt-3 text-base font-bold">Peak wind {formatWindSpeed(outlook.maxWind, units)}</h2><p className="mt-2 text-xs leading-5 text-muted">Wind remains a secondary detail. Wet, windy or otherwise unsafe conditions should defer roof inspection or maintenance, regardless of the solar forecast.</p></div></section>
    </> : null}
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0b2740]/45 p-5 backdrop-blur-sm"><form id="site-location-form" action={saveLocation} className="card w-full max-w-lg bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><div className="eyebrow">Site settings</div><h2 className="mt-2 text-xl font-extrabold">Solar forecast location</h2></div><button type="button" onClick={() => setEditing(false)} className="grid size-8 place-items-center rounded-lg hover:bg-[#eef3f8]">×</button></div><button type="button" onClick={useDeviceLocation} disabled={locating} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-line py-3 text-xs font-bold"><LocateFixed size={15}/>{locating ? "Finding location…" : "Use this device’s location"}</button><input type="hidden" name="locationSource" defaultValue="manual"/><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Location name<input name="location" required defaultValue={site.location === "Location not set" ? "" : site.location} className="field" placeholder="e.g. Rotorua, New Zealand"/></label><label className="text-xs font-bold">Latitude<input name="latitude" type="number" step="any" required defaultValue={site.latitude} className="field"/></label><label className="text-xs font-bold">Longitude<input name="longitude" type="number" step="any" required defaultValue={site.longitude} className="field"/></label><label className="text-xs font-bold sm:col-span-2">Timezone<input name="timezone" required defaultValue={site.timezone === "UTC" ? Intl.DateTimeFormat().resolvedOptions().timeZone : site.timezone} className="field" placeholder="Pacific/Auckland"/></label></div><button disabled={saving} className="mt-6 h-11 w-full rounded-xl bg-brand text-xs font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Save site location"}</button></form></div>}
  </div>;
}

function WeatherMetric({ icon: Icon, label, value, detail }: { icon: typeof Sun; label: string; value: string; detail: string }) { return <div className="card flex min-h-36 flex-col justify-between p-5"><div className="flex justify-between"><span className="text-xs font-semibold text-muted">{label}</span><span className="grid size-8 place-items-center rounded-xl bg-[#eaf2fb] text-brand"><Icon size={16}/></span></div><div><div className="font-display text-[26px] font-extrabold tracking-[-.045em]">{value}</div><div className="text-[10px] text-muted">{detail}</div></div></div>; }

function ForecastDayCard({ day, timezone, units }: { day: ReturnType<typeof fiveDaySolarOutlook>[number]; timezone: string; units: UnitPreferences }) {
  const label = day.hours[0] ? new Intl.DateTimeFormat(undefined, { weekday: "short", day: "numeric", month: "short", timeZone: timezone }).format(new Date(day.hours[0].time)) : day.dateKey;
  const Icon = day.rainMm >= 1 ? CloudRain : day.maxCloudCover >= 75 ? Cloud : day.maxCloudCover >= 30 ? CloudSun : Sun;
  const iconStyle = day.rainMm >= 1 ? "bg-[#e5f1fb] text-[#1970ad]" : day.maxCloudCover >= 75 ? "bg-[#edf1f5] text-[#66788a]" : "bg-[#fff3bd] text-[#c78b00]";
  return <article className="card p-4"><div className="flex items-start justify-between gap-3"><strong className="pt-1 text-xs">{label}</strong><span className={`grid size-12 shrink-0 place-items-center rounded-2xl ${iconStyle}`}><Icon size={27} strokeWidth={2.2}/></span></div><div className="mt-3 font-display text-xl font-extrabold">{day.expectedKwh.toFixed(1)} kWh</div><div className="mt-2 space-y-1 text-[9px] text-muted"><div>{formatTemperature(day.minTemperature, units)}–{formatTemperature(day.maxTemperature, units)}</div><div>{formatRainfall(day.rainMm, units)} rain · {formatWindSpeed(day.maxWind, units)} wind</div></div></article>;
}

function SolarCurve({ hours, dateKey, timezone, expectedKwh, arrayKw }: { hours: SolarWeatherHour[]; dateKey?: string; timezone: string; expectedKwh: number; arrayKw: number }) {
  const width = 1000; const height = 270; const left = 38; const right = 24; const top = 28; const baseline = 218;
  const maxFlux = Math.max(100, ...hours.map((hour) => hour.irradiance ?? 0));
  const points = hours.map((hour, index) => ({ x: left + index / Math.max(1, hours.length - 1) * (width - left - right), y: baseline - Math.max(0, hour.irradiance ?? 0) / maxFlux * (baseline - top), hour }));
  const curve = points.length ? points.slice(1).reduce((path, point, index) => { const previous = points[index]; const midpointX = (previous.x + point.x) / 2; const midpointY = (previous.y + point.y) / 2; return `${path} Q ${previous.x} ${previous.y} ${midpointX} ${midpointY}`; }, `M ${points[0].x} ${points[0].y}`) + ` T ${points.at(-1)?.x} ${points.at(-1)?.y}` : "";
  const area = points.length ? `M ${points[0].x} ${baseline} L ${points[0].x} ${points[0].y} ${curve.replace(/^M [\d.]+ [\d.]+/, "")} L ${points.at(-1)?.x} ${baseline} Z` : "";
  const peak = points.reduce((best, point) => (point.hour.irradiance ?? 0) > (best?.hour.irradiance ?? -1) ? point : best, undefined as typeof points[number] | undefined);
  const dayLabel = hours[0] ? new Intl.DateTimeFormat(undefined, { weekday: "long", day: "numeric", month: "short", timeZone: timezone }).format(new Date(hours[0].time)) : dateKey ?? "Next solar day";
  if (hours.length < 2) return <section className="card p-6"><div className="eyebrow">Solar curve</div><p className="mt-3 text-sm text-muted">A complete daylight curve is not available in this forecast yet.</p></section>;
  const labelEvery = Math.max(1, Math.round(hours.length / 6));
  return <section className="card overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-line p-5 sm:flex-row sm:items-end"><div><div className="eyebrow">Solar curve</div><h2 className="mt-2 text-lg font-extrabold">Available sunlight · {dayLabel}</h2><p className="mt-1 text-[10px] text-muted">The higher the curve, the stronger the available solar energy.</p></div><div className="sm:text-right"><strong className="block text-lg">{expectedKwh.toFixed(1)} kWh expected</strong><span className="text-[9px] text-muted">{arrayKw.toFixed(1)} kW configured array</span></div></div><div className="relative bg-[linear-gradient(180deg,#fffdf5,#f5f8fc)] px-3 py-4"><svg viewBox={`0 0 ${width} ${height}`} className="h-[260px] w-full" role="img" aria-label={`Solar irradiance curve for ${dayLabel}`}><defs><linearGradient id="solar-curve-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#f6c945" stopOpacity=".65"/><stop offset="1" stopColor="#f6c945" stopOpacity=".05"/></linearGradient></defs><line x1={left} y1={baseline} x2={width-right} y2={baseline} stroke="#cdd8e3"/><line x1={left} y1={top} x2={width-right} y2={top} stroke="#e4eaf0" strokeDasharray="5 7"/><text x={left} y={top-8} fill="#65758b" fontSize="11">{Math.round(maxFlux)} W/m²</text><path d={area} fill="url(#solar-curve-fill)"/><path d={curve} fill="none" stroke="#d8a000" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/>{peak && <><line x1={peak.x} y1={peak.y} x2={peak.x} y2={baseline} stroke="#8ea6bc" strokeDasharray="5 6"/><circle cx={peak.x} cy={peak.y} r="7" fill="#f5d64e" stroke="#fff" strokeWidth="3"/></>}{points.map((point, index) => index % labelEvery === 0 || index === points.length - 1 ? <text key={point.hour.time} x={point.x} y={baseline+25} textAnchor={index === 0 ? "start" : index === points.length - 1 ? "end" : "middle"} fill="#647069" fontSize="11" fontWeight="600">{new Intl.DateTimeFormat(undefined, { hour: "numeric", timeZone: timezone }).format(new Date(point.hour.time))}</text> : null)}</svg>{arrayKw <= 0 && <div className="mx-3 mb-3 rounded-xl bg-[#fff5d9] px-4 py-3 text-[10px] text-[#765c1c]">The sunlight curve is available, but expected energy remains 0.0 kWh until this system’s PV array size is recorded.</div>}</div></section>;
}
