"use client";

import { Download, Plus, Trash2, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import type { FinancialEntry, FinancialEntryType, SystemFinancialsState } from "@/domain/models";

const labels: Record<FinancialEntryType, string> = { purchase: "Purchase", other_cost: "Other cost", rebate: "Rebate", buyback: "Energy buy-back", other_income: "Other income" };
const costs = new Set<FinancialEntryType>(["purchase", "other_cost"]);
const blank = { type: "purchase" as FinancialEntryType, date: new Date().toISOString().slice(0, 10), description: "", amount: "", vendor: "", notes: "" };

export function SystemFinancials({ projectId, initialState, compact = false }: { projectId: string; initialState: SystemFinancialsState; compact?: boolean }) {
  const [state, setState] = useState(initialState); const [draft, setDraft] = useState(blank); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const totals = useMemo(() => state.entries.reduce((sum, entry) => { if (costs.has(entry.type)) sum.costs += entry.amount; else sum.returns += entry.amount; return sum; }, { costs: 0, returns: 0 }), [state.entries]);
  const money = (amount: number) => new Intl.NumberFormat(undefined, { style: "currency", currency: state.currency || "NZD" }).format(amount);
  async function persist(next: SystemFinancialsState) { setSaving(true); setError(""); try { const response = await fetch("/api/system-financials", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId, financials: next }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not save financials."); setState(next); } catch (problem) { setError(problem instanceof Error ? problem.message : "Could not save financials."); } finally { setSaving(false); } }
  function addEntry(event: React.FormEvent) { event.preventDefault(); const amount = Number(draft.amount); if (!draft.description.trim() || !Number.isFinite(amount) || amount <= 0) { setError("Add a description and an amount greater than zero."); return; } const entry: FinancialEntry = { id: crypto.randomUUID(), type: draft.type, date: draft.date, description: draft.description.trim(), amount, vendor: draft.vendor.trim() || undefined, notes: draft.notes.trim() || undefined }; void persist({ ...state, entries: [entry, ...state.entries], updatedAt: new Date().toISOString() }); setDraft(blank); }
  function exportCsv() { const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const rows = [["Date", "Type", "Description", "Vendor / buyer", "Amount", "Direction", "Notes"], ...state.entries.map((e) => [e.date, labels[e.type], e.description, e.vendor ?? "", e.amount, costs.has(e.type) ? "Cost" : "Return", e.notes ?? ""])]; const blob = new Blob([rows.map((row) => row.map(quote).join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "system-financials.csv"; link.click(); URL.revokeObjectURL(url); }
  return <div className={compact ? "mt-3 space-y-0 overflow-hidden rounded-xl border border-line bg-[rgba(255,253,248,.94)] shadow-[0_5px_16px_rgba(15,59,102,.05)] [&_.field]:h-8 [&_.card]:rounded-none [&_.card]:border-0 [&_.card]:bg-transparent [&_.card]:shadow-none [&>form]:border-t [&>form]:border-line [&>form]:p-3 [&>section]:border-t [&>section]:border-line [&>section>div]:p-3" : "mt-5 space-y-4"}>
    <div className={`grid sm:grid-cols-3 ${compact ? "divide-y divide-line sm:divide-x sm:divide-y-0" : "gap-3"}`}><Summary label="Total costs" value={money(totals.costs)} tone="cost" compact={compact}/><Summary label="Rebates & buy-back" value={money(totals.returns)} tone="return" compact={compact}/><Summary label="Net system cost" value={money(totals.costs - totals.returns)} tone="net" compact={compact}/></div>
    <form onSubmit={addEntry} className="card p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#eaf2fb] text-brand"><Plus size={17}/></span><div><div className="eyebrow">New transaction</div><h2 className="mt-1 text-base font-extrabold">Add to the running total</h2></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] font-bold text-muted">Type<select className="field" value={draft.type} onChange={(e) => setDraft({ ...draft, type: e.target.value as FinancialEntryType })}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-[10px] font-bold text-muted">Date<input required type="date" className="field" value={draft.date} onChange={(e) => setDraft({ ...draft, date: e.target.value })}/></label><label className="text-[10px] font-bold text-muted lg:col-span-2">Description<input required className="field" placeholder="Panels, inverter, monthly export…" value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })}/></label><label className="text-[10px] font-bold text-muted">Amount ({state.currency})<input required type="number" min="0.01" step="0.01" className="field" value={draft.amount} onChange={(e) => setDraft({ ...draft, amount: e.target.value })}/></label><label className="text-[10px] font-bold text-muted">Vendor or buyer<input className="field" value={draft.vendor} onChange={(e) => setDraft({ ...draft, vendor: e.target.value })}/></label><label className="text-[10px] font-bold text-muted lg:col-span-2">Notes<input className="field" value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })}/></label></div><div className="mt-4 flex items-center justify-between gap-3">{error ? <p className="text-[11px] text-[#a7442d]">{error}</p> : <span/>}<button disabled={saving} className="rounded-xl bg-brand px-5 py-3 text-xs font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Add transaction"}</button></div></form>
    <section className="card overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-line p-4"><div><div className="eyebrow">Ledger</div><h2 className="mt-1 text-base font-extrabold">{state.entries.length} transaction{state.entries.length === 1 ? "" : "s"}</h2></div><button type="button" disabled={!state.entries.length} onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl border border-line px-3 py-2 text-[11px] font-bold text-brand disabled:opacity-40"><Download size={14}/>Export CSV</button></div>{state.entries.length ? <div className="divide-y divide-line">{state.entries.map((entry) => <div key={entry.id} className="grid gap-2 p-4 sm:grid-cols-[90px_minmax(0,1fr)_120px_36px] sm:items-center"><span className="text-[10px] font-bold text-muted">{new Date(`${entry.date}T12:00:00`).toLocaleDateString()}</span><div><strong className="text-xs">{entry.description}</strong><p className="mt-0.5 text-[9px] text-muted">{labels[entry.type]}{entry.vendor ? ` · ${entry.vendor}` : ""}{entry.notes ? ` · ${entry.notes}` : ""}</p></div><strong className={`text-sm ${costs.has(entry.type) ? "text-[#9b4938]" : "text-[#20724b]"}`}>{costs.has(entry.type) ? "−" : "+"}{money(entry.amount)}</strong><button type="button" disabled={saving} onClick={() => void persist({ ...state, entries: state.entries.filter((item) => item.id !== entry.id), updatedAt: new Date().toISOString() })} className="grid size-8 place-items-center rounded-lg text-muted hover:bg-[#fff0eb] hover:text-[#a7442d]" aria-label={`Delete ${entry.description}`}><Trash2 size={14}/></button></div>)}</div> : <div className="p-8 text-center"><WalletCards size={28} className="mx-auto text-muted"/><p className="mt-3 text-xs font-bold">No financial transactions yet</p><p className="mt-1 text-[10px] text-muted">Add the first purchase, cost, rebate or energy buy-back above.</p></div>}</section>
  </div>;
}

function Summary({ label, value, tone, compact = false }: { label: string; value: string; tone: "cost" | "return" | "net"; compact?: boolean }) { const colors = tone === "cost" ? "bg-[#fff2ed] text-[#8c4435]" : tone === "return" ? "bg-[#eaf8ef] text-[#20724b]" : "bg-[#eaf2fb] text-brand"; return <div className={`card ${compact ? "p-3" : "p-4"}`}><span className={`inline-flex rounded-md px-2 py-1 text-[8px] font-extrabold uppercase tracking-[.08em] ${colors}`}>{label}</span><div className={`${compact ? "mt-2 text-base" : "mt-3 text-xl"} font-extrabold tracking-[-.03em]`}>{value}</div></div>; }
