import { LegalPage } from "@/components/legal-page";

export default function TermsPage() { return <LegalPage eyebrow="Legal" title="Terms of service" intro="These terms describe the basis on which PVIntell provides its solar planning, record-keeping and Wattson assistance service." sections={[
  { title: "Planning assistance, not a substitute for qualified work", paragraphs: ["PVIntell provides planning information, calculations, records and AI-assisted explanations. Outputs may be incomplete or incorrect and are not an engineering design, electrical certification, consent, inspection or guarantee of performance.", "You remain responsible for checking product instructions, Site conditions and applicable laws, and for using appropriately qualified or authorised people where required. Do not rely on PVIntell as the sole basis for safety-critical work."] },
  { title: "Local requirements and user responsibility", paragraphs: ["PVIntell and Wattson provide planning and design assistance based on the information available. Local consent requirements, regulations and bylaws vary between locations and may change.", "Before undertaking any installation work, you are ultimately responsible for checking the requirements that apply at your Site with the relevant local authority and other responsible organisations, and for obtaining any required consents, approvals, inspections or qualified professional services. Nothing in these terms limits rights or responsibilities that cannot legally be limited."] },
  { title: "Accounts and acceptable use", paragraphs: ["You are responsible for the accuracy of information you provide, safeguarding access to your account and using the service lawfully. Do not upload content you do not have the right to use or attempt to interfere with the service or another user’s data."] },
  { title: "Paid service, pricing and refunds", paragraphs: ["PVIntell is intended to be a paid service. Plans, prices, included usage, billing periods and any trial terms will be shown before purchase when paid plans launch.", "Payments are generally non-refundable once charged, including for unused time, except where a refund or other remedy is required by applicable law. Nothing in these terms excludes rights that cannot legally be excluded, including applicable consumer guarantees."] },
  { title: "Availability and changes", paragraphs: ["The service, Wattson models, weather sources and features may change. PVIntell does not promise uninterrupted availability or that third-party forecasts, maps or integrations will always be available."] },
  { title: "Account deletion and termination", paragraphs: ["You may permanently delete your account from Account. Deletion is irreversible and removes the account data described in the Privacy Policy. PVIntell may restrict or end access for material misuse, non-payment or legal and security reasons."] },
  { title: "Contact", paragraphs: ["Questions about these terms can be sent to pvintell1@gmail.com."] },
]}/>; }
