import { LegalPage } from "@/components/legal-page";

export default function PrivacyPage() { return <LegalPage eyebrow="Privacy" title="Privacy policy" intro="This policy explains the information PVIntell uses to operate your account, Sites, systems and Wattson conversations." sections={[
  { title: "Information we hold", paragraphs: ["PVIntell may hold your account identity and contact details; Site names, locations and coordinates; system designs and installed-equipment records; settings, photos and documents you upload; Wattson conversations; support correspondence; and technical records needed to secure and operate the service."] },
  { title: "How it is used", paragraphs: ["We use this information to authenticate you, provide Site-specific weather and solar planning, maintain system records, answer Wattson questions, support the service and protect it from misuse. We do not treat an approximate device location as an exact installation position unless you confirm and save it."] },
  { title: "Wattson and retained knowledge", paragraphs: ["Your normal conversations and system knowledge remain associated with your account. Deleting an individual chat removes that transcript but does not remove facts already saved into your structured system records.", "Deleting your full account removes both conversations and structured system data. PVIntell will not silently keep a personal or linkable copy. A useful unusual setup may be retained only through a separate, informed opt-in that identifies what will be de-identified and contributed; declining that option does not affect account deletion."] },
  { title: "Service providers and maps", paragraphs: ["PVIntell uses service providers for hosting, authentication, data storage, email delivery, AI functions, weather information and OpenStreetMap-based mapping. They process the information needed to provide those functions under their own service and privacy terms."] },
  { title: "Deletion and security", paragraphs: ["The Delete account control permanently removes your authentication account, Sites, systems, equipment, uploaded project photos, settings and Wattson conversations. Deletion cannot be undone or recovered through PVIntell. Limited security, billing or legal records may be retained only where required by law or necessary to establish a transaction or resolve abuse."] },
  { title: "Contact", paragraphs: ["Privacy and data requests can be sent to pvintell1@gmail.com."] },
]}/>; }
