import { ArrowLeft, KeyRound, ShieldCheck, Zap } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { setPassword } from "./actions";
import { PasswordField } from "@/components/password-field";

export default async function AccountPage({searchParams}:{searchParams:Promise<{error?:string;message?:string;setup?:string}>}){
  const supabase=await createClient();const {data,error}=await supabase.auth.getClaims();if(error||!data?.claims?.sub)redirect("/login");const notice=await searchParams;const email=typeof data.claims.email==="string"?data.claims.email:"";
  return <main className="min-h-screen bg-canvas p-5 md:p-10"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-xs font-bold text-muted"><ArrowLeft size={15}/>Back to PVIntell</Link><div className="flex items-center gap-2 font-display text-sm font-extrabold"><span className="grid size-8 place-items-center rounded-lg bg-brand text-white"><Zap size={16} fill="currentColor"/></span>PVIntell</div></div><div className="mt-12"><div className="eyebrow">Account settings</div><h1 className="mt-3 font-display text-3xl font-extrabold tracking-[-.045em]">Sign-in and security</h1><p className="mt-2 text-sm text-muted">Manage how you access your PVIntell projects.</p></div>
  {(notice.error||notice.message||notice.setup==="password")&&<div className={`mt-6 rounded-xl border p-3 text-xs ${notice.error?"border-[#e7c3b8] bg-[#fff1ed] text-[#8b432f]":"border-[#bad5c3] bg-[#eaf5ed] text-[#286143]"}`}>{notice.error??notice.message??"Google identity confirmed. Set your PVIntell password below; afterward, either sign-in method will work."}</div>}
  <section className="card mt-6 p-6 md:p-8"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#eaf3e7] text-brand"><ShieldCheck size={19}/></span><div><div className="text-xs font-bold">Signed-in email</div><div className="mt-1 text-sm text-muted">{email}</div></div></div><div className="my-6 h-px bg-line"/><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#eaf3e7] text-brand"><KeyRound size={19}/></span><div className="flex-1"><h2 className="text-sm font-bold">Set or change your PVIntell password</h2><p className="mt-2 text-xs leading-5 text-muted">This adds email-and-password access. You can still continue with Google at any time.</p><form action={setPassword} className="mt-5 space-y-4"><PasswordField label="New password" name="password" autoComplete="new-password"/><PasswordField label="Confirm new password" name="passwordConfirm" autoComplete="new-password"/><button className="h-11 w-full rounded-xl bg-brand text-xs font-bold text-white sm:w-auto sm:px-6">Save password</button></form></div></div></section></div></main>
}
